In [ ]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.chrome.options import Options
import time
from datetime import datetime, timedelta
import pandas as pd
import urllib.parse
import random

# 봇 탐지 방지를 위해 user agnet로 설정
options = Options()
user_agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36'
options.add_argument(f'user-agent={user_agent}')

# Chrome 드라이버 자동 다운로드 및 설정
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

# 부산일보 2022-01-01 ~ 2024-12-31 기간동안 '폭염' 키워드 포함한 기사 검색 url
url = 'https://www.busan.com/search/index.php?search_string=%ED%8F%AD%EC%97%BC&page=1&cnt=0&sort=DATE/ASC&start_date=2022-01-01&end_date=2024-12-31&real_search=%ED%8F%AD%EC%97%BC&rescan_chk=0&type=B&search_writer=undefined'
driver.get(url)

In [ ]:
news_links = [] # 기사 링크를 저장할 리스트 생성

# 기사가 한 페이지당 10개 존재, 총 389페이지
# 따라서 1페이지 부터 389페이지까지 방문
for i in range(1, 390):
    # 페이지 수에 따른 url 변경 반영
    url = f'https://www.busan.com/search/index.php?search_string=%ED%8F%AD%EC%97%BC&page={i}&cnt={(i-1)*10}&sort=DATE/ASC&start_date=2022-01-01&end_date=2024-12-31&real_search=%ED%8F%AD%EC%97%BC&rescan_chk=0&type=B&search_writer=undefined'
    driver.get(url) # 페이지 이동

    time.sleep(0.8) # 페이지 로딩 대기
    
    # <ul id="search_list">로 설정된 태그 내에 <p class="title"> 태그가 존재하고 그 안에 있는 모든 <a> 태그를 찾음
    a_tags = driver.find_elements(By.XPATH, '//ul[@id="search_list"]//p[@class="title"]/a')
    page_links = [a.get_attribute('href') for a in a_tags] # 한 페이지에서 a_tags 안에 있는 href 속성 추출 (기사 링크)
    news_links.extend(page_links) # 페이지에서 추출한 링크를 전체 기사 링크에 추가

    print(len(news_links)) # 현재까지 추출된 기사 링크 수 확인

print(len(news_links)) # 전체 기사 개수
print(news_links[:5])

10
20
30
40
50
60
70
80
90
100
110
120
130
140
150
160
170
180
190
200
210
220
230
240
250
260
270
280
290
300
310
320
330
340
350
360
370
380
390
400
410
420
430
440
450
460
470
480
490
500
510
520
530
540
550
560
570
580
590
600
610
620
630
640
650
660
670
680
690
700
710
720
730
740
750
760
770
780
790
800
810
820
830
840
850
860
870
880
890
900
910
920
930
940
950
960
970
980
990
1000
1010
1020
1030
1040
1050
1060
1070
1080
1090
1100
1110
1120
1130
1140
1150
1160
1170
1180
1190
1200
1210
1220
1230
1240
1250
1260
1270
1280
1290
1300
1310
1320
1330
1340
1350
1360
1370
1380
1390
1400
1410
1420
1430
1440
1450
1460
1470
1480
1490
1500
1510
1520
1530
1540
1550
1560
1570
1580
1590
1600
1610
1620
1630
1640
1650
1660
1670
1680
1690
1700
1710
1720
1730
1740
1750
1760
1770
1780
1790
1800
1810
1820
1830
1840
1850
1860
1870
1880
1890
1900
1910
1920
1930
1940
1950
1960
1970
1980
1990
2000
2010
2020
2030
2040
2050
2060
2070
2080
2090
2100
2110
2120
2130
2140
2150
2160
2170
2180
2190
2200
2210
2220
2230
2240
2250
2260
2270
2280
2290
2300
2310
2320
2330
2340
2350
2360
2370
2380
2390
2400
2410
2420
2430
2440
2450
2460
2470
2480
2490
2500
2510
2520
2530
2540
2550
2560
2570
2580
2590
2600
2610
2620
2630
2640
2650
2660
2670
2680
2690
2700
2710
2720
2730
2740
2750
2760
2770
2780
2790
2800
2810
2820
2830
2840
2850
2860
2870
2880
2890
2900
2910
2920
2930
2940
2950
2960
2970
2980
2990
3000
3010
3020
3030
3040
3050
3060
3070
3080
3090
3100
3110
3120
3130
3140
3150
3160
3170
3180
3190
3200
3210
3220
3230
3240
3250
3260
3270
3280
3290
3300
3310
3320
3330
3340
3350
3360
3370
3380
3390
3400
3410
3420
3430
3440
3450
3460
3470
3480
3490
3500
3510
3520
3530
3540
3550
3560
3570
3580
3590
3600
3610
3620
3630
3640
3650
3660
3670
3680
3690
3700
3710
3720
3730
3740
3750
3760
3770
3780
3790
3800
3810
3820
3830
3840
3850
3860
3870
3880
3885
3885
['https://www.busan.com/view/busan/view.php?code=2022010510371992234', 'https://www.busan.com/view/busan/view.php?code=2022010711091503282', 'https://www.busan.com/view/busan/view.php?code=2022010714251327680', 'https://www.busan.com/view/busan/view.php?code=2022011114015270150', 'https://www.busan.com/view/busan/view.php?code=2022011318512753872']

### 개별 기사 접근 시작

In [ ]:
# 추출한 링크에 직접 방문하여 크롤링 진행 - 교수님 제공 코드 이용

# 크롤링 속도를 행상시키기 위해 time.sleep대신 WebDriverWait으로 변경 (다만 네트워크 불량 시 오래 걸릴 수 있음)
# WebDriverWait 이용 시 탐색 속도가 너무 빨라 봇 탐지 가능성 존재 -> time.sleep 이용 요망

# 진행상황 확인코드 추가

# 방문해야 하는 기사수가 3885로 매우 방대 하기 때문에 500개씩 끊어서 진행 (셀 단위)

all_results = dict()
i = 0
err_idx = []

for link in news_links[i:500]:
    try:
        all_results[i] = dict()

        # 실제 네이버 뉴스 웹페이지로 이동
        driver.get(link)

        # 페이지 로딩 대기
        time.sleep(0.6) 

        # 제목 추출하기
        title = driver.find_elements(By.XPATH, '/html/body/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/p')
        title = title[0].text 

        # 본문 추출하기
        body = driver.find_elements(By.CLASS_NAME, 'article_content')
        body = body[0].text.replace('\n', '') 

        # 날짜 추출하기
        pubdate_element = driver.find_elements(By.XPATH, '/html/body/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[2]')
        pubdate = pubdate_element[0].text
        pubdate = pubdate[5:24] # 숫자에 해당하는 부분만 추출

        all_results[i]['link'] = link
        all_results[i]['pubdate'] = pubdate
        all_results[i]['title'] = title
        all_results[i]['body'] = body

        # 진행 상황 확인용 코드
        print(f"[{i+1} / {len(news_links)}] \t {(i+1)/len(news_links)*100:.2f}% 진행")    
        i += 1

        # 봇 탐지 방지를 위해 0.8초에서 1.5초 사이에 랜덤한 시간을 기다림
        time.sleep(random.uniform(0.8, 1.5))

    # 오류 발생 시
    except:
        print('오류가 발생했습니다.')
        err_idx.append(i)

        print(f"[{i+1} / {len(news_links)}] \t {(i+1)/len(news_links)*100:.2f}% 진행 - 오류 발생")    
        i += 1

        # 봇 탐지 방지를 위해 0.8초에서 1.5초 사이에 랜덤한 시간을 기다림
        time.sleep(random.uniform(0.8, 1.5))

print(len(all_results))
print(err_idx)

[1 / 3885] 	 0.03% 진행
[2 / 3885] 	 0.05% 진행
[3 / 3885] 	 0.08% 진행
[4 / 3885] 	 0.10% 진행
[5 / 3885] 	 0.13% 진행
[6 / 3885] 	 0.15% 진행
[7 / 3885] 	 0.18% 진행
[8 / 3885] 	 0.21% 진행
[9 / 3885] 	 0.23% 진행
[10 / 3885] 	 0.26% 진행
[11 / 3885] 	 0.28% 진행
[12 / 3885] 	 0.31% 진행
[13 / 3885] 	 0.33% 진행
[14 / 3885] 	 0.36% 진행
[15 / 3885] 	 0.39% 진행
[16 / 3885] 	 0.41% 진행
[17 / 3885] 	 0.44% 진행
[18 / 3885] 	 0.46% 진행
[19 / 3885] 	 0.49% 진행
[20 / 3885] 	 0.51% 진행
[21 / 3885] 	 0.54% 진행
[22 / 3885] 	 0.57% 진행
[23 / 3885] 	 0.59% 진행
[24 / 3885] 	 0.62% 진행
[25 / 3885] 	 0.64% 진행
[26 / 3885] 	 0.67% 진행
[27 / 3885] 	 0.69% 진행
[28 / 3885] 	 0.72% 진행
[29 / 3885] 	 0.75% 진행
[30 / 3885] 	 0.77% 진행
[31 / 3885] 	 0.80% 진행
[32 / 3885] 	 0.82% 진행
[33 / 3885] 	 0.85% 진행
[34 / 3885] 	 0.88% 진행
[35 / 3885] 	 0.90% 진행
[36 / 3885] 	 0.93% 진행
[37 / 3885] 	 0.95% 진행
[38 / 3885] 	 0.98% 진행
[39 / 3885] 	 1.00% 진행
[40 / 3885] 	 1.03% 진행
[41 / 3885] 	 1.06% 진행
[42 / 3885] 	 1.08% 진행
[43 / 3885] 	 1.11% 진행
[44 / 3885] 	 1.13% 진행
[45 / 3885] 	 1.16% 진행
[46 / 3885] 	 1.18% 진행
[47 / 3885] 	 1.21% 진행
[48 / 3885] 	 1.24% 진행
[49 / 3885] 	 1.26% 진행
[50 / 3885] 	 1.29% 진행
[51 / 3885] 	 1.31% 진행
[52 / 3885] 	 1.34% 진행
[53 / 3885] 	 1.36% 진행
[54 / 3885] 	 1.39% 진행
[55 / 3885] 	 1.42% 진행
[56 / 3885] 	 1.44% 진행
[57 / 3885] 	 1.47% 진행
[58 / 3885] 	 1.49% 진행
[59 / 3885] 	 1.52% 진행
[60 / 3885] 	 1.54% 진행
[61 / 3885] 	 1.57% 진행
[62 / 3885] 	 1.60% 진행
[63 / 3885] 	 1.62% 진행
[64 / 3885] 	 1.65% 진행
[65 / 3885] 	 1.67% 진행
[66 / 3885] 	 1.70% 진행
[67 / 3885] 	 1.72% 진행
[68 / 3885] 	 1.75% 진행
[69 / 3885] 	 1.78% 진행
[70 / 3885] 	 1.80% 진행
[71 / 3885] 	 1.83% 진행
[72 / 3885] 	 1.85% 진행
[73 / 3885] 	 1.88% 진행
[74 / 3885] 	 1.90% 진행
[75 / 3885] 	 1.93% 진행
[76 / 3885] 	 1.96% 진행
[77 / 3885] 	 1.98% 진행
[78 / 3885] 	 2.01% 진행
[79 / 3885] 	 2.03% 진행
[80 / 3885] 	 2.06% 진행
[81 / 3885] 	 2.08% 진행
[82 / 3885] 	 2.11% 진행
[83 / 3885] 	 2.14% 진행
[84 / 3885] 	 2.16% 진행
[85 / 3885] 	 2.19% 진행
[86 / 3885] 	 2.21% 진행
[87 / 3885] 	 2.24% 진행
[88 / 3885] 	 2.27% 진행
[89 / 3885] 	 2.29% 진행
[90 / 3885] 	 2.32% 진행
[91 / 3885] 	 2.34% 진행
[92 / 3885] 	 2.37% 진행
[93 / 3885] 	 2.39% 진행
[94 / 3885] 	 2.42% 진행
[95 / 3885] 	 2.45% 진행
[96 / 3885] 	 2.47% 진행
[97 / 3885] 	 2.50% 진행
[98 / 3885] 	 2.52% 진행
[99 / 3885] 	 2.55% 진행
[100 / 3885] 	 2.57% 진행
[101 / 3885] 	 2.60% 진행
[102 / 3885] 	 2.63% 진행
[103 / 3885] 	 2.65% 진행
[104 / 3885] 	 2.68% 진행
[105 / 3885] 	 2.70% 진행
[106 / 3885] 	 2.73% 진행
[107 / 3885] 	 2.75% 진행
[108 / 3885] 	 2.78% 진행
[109 / 3885] 	 2.81% 진행
[110 / 3885] 	 2.83% 진행
[111 / 3885] 	 2.86% 진행
[112 / 3885] 	 2.88% 진행
[113 / 3885] 	 2.91% 진행
[114 / 3885] 	 2.93% 진행
[115 / 3885] 	 2.96% 진행
[116 / 3885] 	 2.99% 진행
[117 / 3885] 	 3.01% 진행
[118 / 3885] 	 3.04% 진행
[119 / 3885] 	 3.06% 진행
[120 / 3885] 	 3.09% 진행
[121 / 3885] 	 3.11% 진행
[122 / 3885] 	 3.14% 진행
[123 / 3885] 	 3.17% 진행
[124 / 3885] 	 3.19% 진행
[125 / 3885] 	 3.22% 진행
[126 / 3885] 	 3.24% 진행
[127 / 3885] 	 3.27% 진행
[128 / 3885] 	 3.29% 진행
[129 / 3885] 	 3.32% 진행
[130 / 3885] 	 3.35% 진행
[131 / 3885] 	 3.37% 진행
[132 / 3885] 	 3.40% 진행
[133 / 3885] 	 3.42% 진행
[134 / 3885] 	 3.45% 진행
[135 / 3885] 	 3.47% 진행
[136 / 3885] 	 3.50% 진행
[137 / 3885] 	 3.53% 진행
[138 / 3885] 	 3.55% 진행
[139 / 3885] 	 3.58% 진행
[140 / 3885] 	 3.60% 진행
[141 / 3885] 	 3.63% 진행
[142 / 3885] 	 3.66% 진행
[143 / 3885] 	 3.68% 진행
[144 / 3885] 	 3.71% 진행
[145 / 3885] 	 3.73% 진행
[146 / 3885] 	 3.76% 진행
[147 / 3885] 	 3.78% 진행
[148 / 3885] 	 3.81% 진행
[149 / 3885] 	 3.84% 진행
[150 / 3885] 	 3.86% 진행
[151 / 3885] 	 3.89% 진행
[152 / 3885] 	 3.91% 진행
[153 / 3885] 	 3.94% 진행
[154 / 3885] 	 3.96% 진행
[155 / 3885] 	 3.99% 진행
[156 / 3885] 	 4.02% 진행
[157 / 3885] 	 4.04% 진행
[158 / 3885] 	 4.07% 진행
[159 / 3885] 	 4.09% 진행
[160 / 3885] 	 4.12% 진행
[161 / 3885] 	 4.14% 진행
[162 / 3885] 	 4.17% 진행
[163 / 3885] 	 4.20% 진행
[164 / 3885] 	 4.22% 진행
[165 / 3885] 	 4.25% 진행
[166 / 3885] 	 4.27% 진행
[167 / 3885] 	 4.30% 진행
[168 / 3885] 	 4.32% 진행
[169 / 3885] 	 4.35% 진행
[170 / 3885] 	 4.38% 진행
[171 / 3885] 	 4.40% 진행
[172 / 3885] 	 4.43% 진행
[173 / 3885] 	 4.45% 진행
[174 / 3885] 	 4.48% 진행
[175 / 3885] 	 4.50% 진행
[176 / 3885] 	 4.53% 진행
[177 / 3885] 	 4.56% 진행
[178 / 3885] 	 4.58% 진행
[179 / 3885] 	 4.61% 진행
[180 / 3885] 	 4.63% 진행
[181 / 3885] 	 4.66% 진행
[182 / 3885] 	 4.68% 진행
[183 / 3885] 	 4.71% 진행
[184 / 3885] 	 4.74% 진행
[185 / 3885] 	 4.76% 진행
[186 / 3885] 	 4.79% 진행
[187 / 3885] 	 4.81% 진행
[188 / 3885] 	 4.84% 진행
[189 / 3885] 	 4.86% 진행
[190 / 3885] 	 4.89% 진행
[191 / 3885] 	 4.92% 진행
[192 / 3885] 	 4.94% 진행
[193 / 3885] 	 4.97% 진행
[194 / 3885] 	 4.99% 진행
[195 / 3885] 	 5.02% 진행
[196 / 3885] 	 5.05% 진행
[197 / 3885] 	 5.07% 진행
[198 / 3885] 	 5.10% 진행
[199 / 3885] 	 5.12% 진행
[200 / 3885] 	 5.15% 진행
[201 / 3885] 	 5.17% 진행
[202 / 3885] 	 5.20% 진행
[203 / 3885] 	 5.23% 진행
[204 / 3885] 	 5.25% 진행
[205 / 3885] 	 5.28% 진행
[206 / 3885] 	 5.30% 진행
[207 / 3885] 	 5.33% 진행
[208 / 3885] 	 5.35% 진행
[209 / 3885] 	 5.38% 진행
[210 / 3885] 	 5.41% 진행
[211 / 3885] 	 5.43% 진행
[212 / 3885] 	 5.46% 진행
[213 / 3885] 	 5.48% 진행
[214 / 3885] 	 5.51% 진행
[215 / 3885] 	 5.53% 진행
[216 / 3885] 	 5.56% 진행
[217 / 3885] 	 5.59% 진행
[218 / 3885] 	 5.61% 진행
[219 / 3885] 	 5.64% 진행
[220 / 3885] 	 5.66% 진행
[221 / 3885] 	 5.69% 진행
[222 / 3885] 	 5.71% 진행
[223 / 3885] 	 5.74% 진행
[224 / 3885] 	 5.77% 진행
[225 / 3885] 	 5.79% 진행
[226 / 3885] 	 5.82% 진행
[227 / 3885] 	 5.84% 진행
[228 / 3885] 	 5.87% 진행
[229 / 3885] 	 5.89% 진행
[230 / 3885] 	 5.92% 진행
[231 / 3885] 	 5.95% 진행
[232 / 3885] 	 5.97% 진행
[233 / 3885] 	 6.00% 진행
[234 / 3885] 	 6.02% 진행
[235 / 3885] 	 6.05% 진행
[236 / 3885] 	 6.07% 진행
[237 / 3885] 	 6.10% 진행
[238 / 3885] 	 6.13% 진행
[239 / 3885] 	 6.15% 진행
[240 / 3885] 	 6.18% 진행
[241 / 3885] 	 6.20% 진행
[242 / 3885] 	 6.23% 진행
[243 / 3885] 	 6.25% 진행
[244 / 3885] 	 6.28% 진행
[245 / 3885] 	 6.31% 진행
[246 / 3885] 	 6.33% 진행
[247 / 3885] 	 6.36% 진행
[248 / 3885] 	 6.38% 진행
[249 / 3885] 	 6.41% 진행
[250 / 3885] 	 6.44% 진행
[251 / 3885] 	 6.46% 진행
[252 / 3885] 	 6.49% 진행
[253 / 3885] 	 6.51% 진행
[254 / 3885] 	 6.54% 진행
[255 / 3885] 	 6.56% 진행
[256 / 3885] 	 6.59% 진행
[257 / 3885] 	 6.62% 진행
[258 / 3885] 	 6.64% 진행
[259 / 3885] 	 6.67% 진행
[260 / 3885] 	 6.69% 진행
[261 / 3885] 	 6.72% 진행
[262 / 3885] 	 6.74% 진행
[263 / 3885] 	 6.77% 진행
[264 / 3885] 	 6.80% 진행
[265 / 3885] 	 6.82% 진행
[266 / 3885] 	 6.85% 진행
[267 / 3885] 	 6.87% 진행
[268 / 3885] 	 6.90% 진행
[269 / 3885] 	 6.92% 진행
[270 / 3885] 	 6.95% 진행
[271 / 3885] 	 6.98% 진행
[272 / 3885] 	 7.00% 진행
[273 / 3885] 	 7.03% 진행
[274 / 3885] 	 7.05% 진행
[275 / 3885] 	 7.08% 진행
[276 / 3885] 	 7.10% 진행
[277 / 3885] 	 7.13% 진행
[278 / 3885] 	 7.16% 진행
[279 / 3885] 	 7.18% 진행
[280 / 3885] 	 7.21% 진행
[281 / 3885] 	 7.23% 진행
[282 / 3885] 	 7.26% 진행
[283 / 3885] 	 7.28% 진행
[284 / 3885] 	 7.31% 진행
[285 / 3885] 	 7.34% 진행
[286 / 3885] 	 7.36% 진행
[287 / 3885] 	 7.39% 진행
[288 / 3885] 	 7.41% 진행
[289 / 3885] 	 7.44% 진행
[290 / 3885] 	 7.46% 진행
[291 / 3885] 	 7.49% 진행
[292 / 3885] 	 7.52% 진행
[293 / 3885] 	 7.54% 진행
[294 / 3885] 	 7.57% 진행
[295 / 3885] 	 7.59% 진행
[296 / 3885] 	 7.62% 진행
[297 / 3885] 	 7.64% 진행
[298 / 3885] 	 7.67% 진행
[299 / 3885] 	 7.70% 진행
[300 / 3885] 	 7.72% 진행
[301 / 3885] 	 7.75% 진행
[302 / 3885] 	 7.77% 진행
[303 / 3885] 	 7.80% 진행
[304 / 3885] 	 7.82% 진행
[305 / 3885] 	 7.85% 진행
[306 / 3885] 	 7.88% 진행
[307 / 3885] 	 7.90% 진행
[308 / 3885] 	 7.93% 진행
[309 / 3885] 	 7.95% 진행
[310 / 3885] 	 7.98% 진행
[311 / 3885] 	 8.01% 진행
[312 / 3885] 	 8.03% 진행
[313 / 3885] 	 8.06% 진행
[314 / 3885] 	 8.08% 진행
[315 / 3885] 	 8.11% 진행
[316 / 3885] 	 8.13% 진행
[317 / 3885] 	 8.16% 진행
[318 / 3885] 	 8.19% 진행
[319 / 3885] 	 8.21% 진행
[320 / 3885] 	 8.24% 진행
[321 / 3885] 	 8.26% 진행
[322 / 3885] 	 8.29% 진행
[323 / 3885] 	 8.31% 진행
[324 / 3885] 	 8.34% 진행
[325 / 3885] 	 8.37% 진행
[326 / 3885] 	 8.39% 진행
[327 / 3885] 	 8.42% 진행
[328 / 3885] 	 8.44% 진행
[329 / 3885] 	 8.47% 진행
[330 / 3885] 	 8.49% 진행
[331 / 3885] 	 8.52% 진행
[332 / 3885] 	 8.55% 진행
[333 / 3885] 	 8.57% 진행
[334 / 3885] 	 8.60% 진행
[335 / 3885] 	 8.62% 진행
[336 / 3885] 	 8.65% 진행
[337 / 3885] 	 8.67% 진행
[338 / 3885] 	 8.70% 진행
[339 / 3885] 	 8.73% 진행
[340 / 3885] 	 8.75% 진행
[341 / 3885] 	 8.78% 진행
[342 / 3885] 	 8.80% 진행
[343 / 3885] 	 8.83% 진행
[344 / 3885] 	 8.85% 진행
[345 / 3885] 	 8.88% 진행
[346 / 3885] 	 8.91% 진행
[347 / 3885] 	 8.93% 진행
[348 / 3885] 	 8.96% 진행
[349 / 3885] 	 8.98% 진행
[350 / 3885] 	 9.01% 진행
[351 / 3885] 	 9.03% 진행
[352 / 3885] 	 9.06% 진행
[353 / 3885] 	 9.09% 진행
[354 / 3885] 	 9.11% 진행
[355 / 3885] 	 9.14% 진행
[356 / 3885] 	 9.16% 진행
[357 / 3885] 	 9.19% 진행
[358 / 3885] 	 9.21% 진행
[359 / 3885] 	 9.24% 진행
[360 / 3885] 	 9.27% 진행
[361 / 3885] 	 9.29% 진행
[362 / 3885] 	 9.32% 진행
[363 / 3885] 	 9.34% 진행
[364 / 3885] 	 9.37% 진행
[365 / 3885] 	 9.40% 진행
[366 / 3885] 	 9.42% 진행
[367 / 3885] 	 9.45% 진행
[368 / 3885] 	 9.47% 진행
[369 / 3885] 	 9.50% 진행
[370 / 3885] 	 9.52% 진행
[371 / 3885] 	 9.55% 진행
[372 / 3885] 	 9.58% 진행
[373 / 3885] 	 9.60% 진행
[374 / 3885] 	 9.63% 진행
[375 / 3885] 	 9.65% 진행
[376 / 3885] 	 9.68% 진행
[377 / 3885] 	 9.70% 진행
[378 / 3885] 	 9.73% 진행
[379 / 3885] 	 9.76% 진행
[380 / 3885] 	 9.78% 진행
[381 / 3885] 	 9.81% 진행
[382 / 3885] 	 9.83% 진행
[383 / 3885] 	 9.86% 진행
[384 / 3885] 	 9.88% 진행
[385 / 3885] 	 9.91% 진행
[386 / 3885] 	 9.94% 진행
[387 / 3885] 	 9.96% 진행
[388 / 3885] 	 9.99% 진행
[389 / 3885] 	 10.01% 진행
[390 / 3885] 	 10.04% 진행
[391 / 3885] 	 10.06% 진행
[392 / 3885] 	 10.09% 진행
[393 / 3885] 	 10.12% 진행
[394 / 3885] 	 10.14% 진행
[395 / 3885] 	 10.17% 진행
[396 / 3885] 	 10.19% 진행
[397 / 3885] 	 10.22% 진행
[398 / 3885] 	 10.24% 진행
[399 / 3885] 	 10.27% 진행
[400 / 3885] 	 10.30% 진행
[401 / 3885] 	 10.32% 진행
[402 / 3885] 	 10.35% 진행
[403 / 3885] 	 10.37% 진행
[404 / 3885] 	 10.40% 진행
[405 / 3885] 	 10.42% 진행
[406 / 3885] 	 10.45% 진행
[407 / 3885] 	 10.48% 진행
[408 / 3885] 	 10.50% 진행
[409 / 3885] 	 10.53% 진행
[410 / 3885] 	 10.55% 진행
[411 / 3885] 	 10.58% 진행
[412 / 3885] 	 10.60% 진행
[413 / 3885] 	 10.63% 진행
[414 / 3885] 	 10.66% 진행
[415 / 3885] 	 10.68% 진행
[416 / 3885] 	 10.71% 진행
[417 / 3885] 	 10.73% 진행
[418 / 3885] 	 10.76% 진행
[419 / 3885] 	 10.79% 진행
[420 / 3885] 	 10.81% 진행
[421 / 3885] 	 10.84% 진행
[422 / 3885] 	 10.86% 진행
[423 / 3885] 	 10.89% 진행
[424 / 3885] 	 10.91% 진행
[425 / 3885] 	 10.94% 진행
[426 / 3885] 	 10.97% 진행
[427 / 3885] 	 10.99% 진행
[428 / 3885] 	 11.02% 진행
[429 / 3885] 	 11.04% 진행
[430 / 3885] 	 11.07% 진행
[431 / 3885] 	 11.09% 진행
[432 / 3885] 	 11.12% 진행
[433 / 3885] 	 11.15% 진행
[434 / 3885] 	 11.17% 진행
[435 / 3885] 	 11.20% 진행
[436 / 3885] 	 11.22% 진행
[437 / 3885] 	 11.25% 진행
[438 / 3885] 	 11.27% 진행
[439 / 3885] 	 11.30% 진행
[440 / 3885] 	 11.33% 진행
[441 / 3885] 	 11.35% 진행
[442 / 3885] 	 11.38% 진행
[443 / 3885] 	 11.40% 진행
[444 / 3885] 	 11.43% 진행
[445 / 3885] 	 11.45% 진행
[446 / 3885] 	 11.48% 진행
[447 / 3885] 	 11.51% 진행
[448 / 3885] 	 11.53% 진행
[449 / 3885] 	 11.56% 진행
[450 / 3885] 	 11.58% 진행
[451 / 3885] 	 11.61% 진행
[452 / 3885] 	 11.63% 진행
[453 / 3885] 	 11.66% 진행
[454 / 3885] 	 11.69% 진행
[455 / 3885] 	 11.71% 진행
[456 / 3885] 	 11.74% 진행
[457 / 3885] 	 11.76% 진행
[458 / 3885] 	 11.79% 진행
[459 / 3885] 	 11.81% 진행
[460 / 3885] 	 11.84% 진행
[461 / 3885] 	 11.87% 진행
[462 / 3885] 	 11.89% 진행
[463 / 3885] 	 11.92% 진행
[464 / 3885] 	 11.94% 진행
[465 / 3885] 	 11.97% 진행
[466 / 3885] 	 11.99% 진행
[467 / 3885] 	 12.02% 진행
[468 / 3885] 	 12.05% 진행
[469 / 3885] 	 12.07% 진행
[470 / 3885] 	 12.10% 진행
[471 / 3885] 	 12.12% 진행
[472 / 3885] 	 12.15% 진행
[473 / 3885] 	 12.18% 진행
[474 / 3885] 	 12.20% 진행
[475 / 3885] 	 12.23% 진행
[476 / 3885] 	 12.25% 진행
[477 / 3885] 	 12.28% 진행
[478 / 3885] 	 12.30% 진행
[479 / 3885] 	 12.33% 진행
[480 / 3885] 	 12.36% 진행
[481 / 3885] 	 12.38% 진행
[482 / 3885] 	 12.41% 진행
[483 / 3885] 	 12.43% 진행
[484 / 3885] 	 12.46% 진행
[485 / 3885] 	 12.48% 진행
[486 / 3885] 	 12.51% 진행
[487 / 3885] 	 12.54% 진행
[488 / 3885] 	 12.56% 진행
[489 / 3885] 	 12.59% 진행
[490 / 3885] 	 12.61% 진행
[491 / 3885] 	 12.64% 진행
[492 / 3885] 	 12.66% 진행
[493 / 3885] 	 12.69% 진행
[494 / 3885] 	 12.72% 진행
[495 / 3885] 	 12.74% 진행
[496 / 3885] 	 12.77% 진행
[497 / 3885] 	 12.79% 진행
[498 / 3885] 	 12.82% 진행
[499 / 3885] 	 12.84% 진행
[500 / 3885] 	 12.87% 진행
500
[]

In [ ]:
# 추출한 링크에 직접 방문하여 크롤링 진행 - 교수님 제공 코드 이용

# 크롤링 속도를 행상시키기 위해 time.sleep대신 WebDriverWait으로 변경 (다만 네트워크 불량 시 오래 걸릴 수 있음)
# WebDriverWait 이용 시 탐색 속도가 너무 빨라 봇 탐지 가능성 존재 -> time.sleep 이용 요망

# 진행상황 확인코드 추가

# 방문해야 하는 기사수가 3885로 매우 방대 하기 때문에 500개씩 끊어서 진행 (셀 단위)

i = 500

for link in news_links[i:1000]:
    try:
        all_results[i] = dict()

        # 실제 네이버 뉴스 웹페이지로 이동
        driver.get(link)

        # 페이지 로딩 대기
        time.sleep(0.6) 

        # 제목 추출하기
        title = driver.find_elements(By.XPATH, '/html/body/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/p')
        title = title[0].text 

        # 본문 추출하기
        body = driver.find_elements(By.CLASS_NAME, 'article_content')
        body = body[0].text.replace('\n', '') 

        # 날짜 추출하기
        pubdate_element = driver.find_elements(By.XPATH, '/html/body/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[2]')
        pubdate = pubdate_element[0].text
        pubdate = pubdate[5:24]

        all_results[i]['link'] = link
        all_results[i]['pubdate'] = pubdate
        all_results[i]['title'] = title
        all_results[i]['body'] = body

        # 진행 상황 확인용 코드
        print(f"[{i+1} / {len(news_links)}] \t {(i+1)/len(news_links)*100:.2f}% 진행")    
        i += 1

        # 봇 탐지 방지를 위해 0.8초에서 1.5초 사이에 랜덤한 시간을 기다림
        time.sleep(random.uniform(0.8, 1.5))

    # 오류 발생 시
    except:
        print('오류가 발생했습니다.')
        err_idx.append(i)

        print(f"[{i+1} / {len(news_links)}] \t {(i+1)/len(news_links)*100:.2f}% 진행 - 오류 발생")    
        i += 1

        # 봇 탐지 방지를 위해 0.8초에서 1.5초 사이에 랜덤한 시간을 기다림
        time.sleep(random.uniform(0.8, 1.5))

print(len(all_results))
print(err_idx)

[501 / 3885] 	 12.90% 진행
[502 / 3885] 	 12.92% 진행
[503 / 3885] 	 12.95% 진행
[504 / 3885] 	 12.97% 진행
[505 / 3885] 	 13.00% 진행
[506 / 3885] 	 13.02% 진행
[507 / 3885] 	 13.05% 진행
[508 / 3885] 	 13.08% 진행
[509 / 3885] 	 13.10% 진행
[510 / 3885] 	 13.13% 진행
[511 / 3885] 	 13.15% 진행
[512 / 3885] 	 13.18% 진행
[513 / 3885] 	 13.20% 진행
[514 / 3885] 	 13.23% 진행
[515 / 3885] 	 13.26% 진행
[516 / 3885] 	 13.28% 진행
[517 / 3885] 	 13.31% 진행
[518 / 3885] 	 13.33% 진행
[519 / 3885] 	 13.36% 진행
[520 / 3885] 	 13.38% 진행
[521 / 3885] 	 13.41% 진행
[522 / 3885] 	 13.44% 진행
[523 / 3885] 	 13.46% 진행
[524 / 3885] 	 13.49% 진행
[525 / 3885] 	 13.51% 진행
[526 / 3885] 	 13.54% 진행
[527 / 3885] 	 13.56% 진행
[528 / 3885] 	 13.59% 진행
[529 / 3885] 	 13.62% 진행
[530 / 3885] 	 13.64% 진행
[531 / 3885] 	 13.67% 진행
[532 / 3885] 	 13.69% 진행
[533 / 3885] 	 13.72% 진행
[534 / 3885] 	 13.75% 진행
[535 / 3885] 	 13.77% 진행
[536 / 3885] 	 13.80% 진행
[537 / 3885] 	 13.82% 진행
[538 / 3885] 	 13.85% 진행
[539 / 3885] 	 13.87% 진행
[540 / 3885] 	 13.90% 진행
[541 / 3885] 	 13.93% 진행
[542 / 3885] 	 13.95% 진행
[543 / 3885] 	 13.98% 진행
[544 / 3885] 	 14.00% 진행
[545 / 3885] 	 14.03% 진행
[546 / 3885] 	 14.05% 진행
[547 / 3885] 	 14.08% 진행
[548 / 3885] 	 14.11% 진행
[549 / 3885] 	 14.13% 진행
[550 / 3885] 	 14.16% 진행
[551 / 3885] 	 14.18% 진행
[552 / 3885] 	 14.21% 진행
[553 / 3885] 	 14.23% 진행
[554 / 3885] 	 14.26% 진행
[555 / 3885] 	 14.29% 진행
[556 / 3885] 	 14.31% 진행
[557 / 3885] 	 14.34% 진행
[558 / 3885] 	 14.36% 진행
[559 / 3885] 	 14.39% 진행
[560 / 3885] 	 14.41% 진행
[561 / 3885] 	 14.44% 진행
[562 / 3885] 	 14.47% 진행
[563 / 3885] 	 14.49% 진행
[564 / 3885] 	 14.52% 진행
[565 / 3885] 	 14.54% 진행
[566 / 3885] 	 14.57% 진행
[567 / 3885] 	 14.59% 진행
[568 / 3885] 	 14.62% 진행
[569 / 3885] 	 14.65% 진행
[570 / 3885] 	 14.67% 진행
[571 / 3885] 	 14.70% 진행
[572 / 3885] 	 14.72% 진행
[573 / 3885] 	 14.75% 진행
[574 / 3885] 	 14.77% 진행
[575 / 3885] 	 14.80% 진행
[576 / 3885] 	 14.83% 진행
[577 / 3885] 	 14.85% 진행
[578 / 3885] 	 14.88% 진행
[579 / 3885] 	 14.90% 진행
[580 / 3885] 	 14.93% 진행
[581 / 3885] 	 14.95% 진행
[582 / 3885] 	 14.98% 진행
[583 / 3885] 	 15.01% 진행
[584 / 3885] 	 15.03% 진행
[585 / 3885] 	 15.06% 진행
[586 / 3885] 	 15.08% 진행
[587 / 3885] 	 15.11% 진행
[588 / 3885] 	 15.14% 진행
[589 / 3885] 	 15.16% 진행
[590 / 3885] 	 15.19% 진행
[591 / 3885] 	 15.21% 진행
[592 / 3885] 	 15.24% 진행
[593 / 3885] 	 15.26% 진행
[594 / 3885] 	 15.29% 진행
[595 / 3885] 	 15.32% 진행
[596 / 3885] 	 15.34% 진행
[597 / 3885] 	 15.37% 진행
[598 / 3885] 	 15.39% 진행
[599 / 3885] 	 15.42% 진행
[600 / 3885] 	 15.44% 진행
[601 / 3885] 	 15.47% 진행
[602 / 3885] 	 15.50% 진행
[603 / 3885] 	 15.52% 진행
[604 / 3885] 	 15.55% 진행
[605 / 3885] 	 15.57% 진행
[606 / 3885] 	 15.60% 진행
[607 / 3885] 	 15.62% 진행
[608 / 3885] 	 15.65% 진행
[609 / 3885] 	 15.68% 진행
[610 / 3885] 	 15.70% 진행
[611 / 3885] 	 15.73% 진행
[612 / 3885] 	 15.75% 진행
[613 / 3885] 	 15.78% 진행
[614 / 3885] 	 15.80% 진행
[615 / 3885] 	 15.83% 진행
[616 / 3885] 	 15.86% 진행
[617 / 3885] 	 15.88% 진행
[618 / 3885] 	 15.91% 진행
[619 / 3885] 	 15.93% 진행
[620 / 3885] 	 15.96% 진행
[621 / 3885] 	 15.98% 진행
[622 / 3885] 	 16.01% 진행
[623 / 3885] 	 16.04% 진행
[624 / 3885] 	 16.06% 진행
[625 / 3885] 	 16.09% 진행
[626 / 3885] 	 16.11% 진행
[627 / 3885] 	 16.14% 진행
[628 / 3885] 	 16.16% 진행
[629 / 3885] 	 16.19% 진행
[630 / 3885] 	 16.22% 진행
[631 / 3885] 	 16.24% 진행
[632 / 3885] 	 16.27% 진행
[633 / 3885] 	 16.29% 진행
[634 / 3885] 	 16.32% 진행
[635 / 3885] 	 16.34% 진행
[636 / 3885] 	 16.37% 진행
[637 / 3885] 	 16.40% 진행
[638 / 3885] 	 16.42% 진행
[639 / 3885] 	 16.45% 진행
[640 / 3885] 	 16.47% 진행
[641 / 3885] 	 16.50% 진행
[642 / 3885] 	 16.53% 진행
[643 / 3885] 	 16.55% 진행
[644 / 3885] 	 16.58% 진행
[645 / 3885] 	 16.60% 진행
[646 / 3885] 	 16.63% 진행
[647 / 3885] 	 16.65% 진행
[648 / 3885] 	 16.68% 진행
[649 / 3885] 	 16.71% 진행
[650 / 3885] 	 16.73% 진행
[651 / 3885] 	 16.76% 진행
[652 / 3885] 	 16.78% 진행
[653 / 3885] 	 16.81% 진행
[654 / 3885] 	 16.83% 진행
[655 / 3885] 	 16.86% 진행
[656 / 3885] 	 16.89% 진행
[657 / 3885] 	 16.91% 진행
[658 / 3885] 	 16.94% 진행
[659 / 3885] 	 16.96% 진행
[660 / 3885] 	 16.99% 진행
[661 / 3885] 	 17.01% 진행
[662 / 3885] 	 17.04% 진행
[663 / 3885] 	 17.07% 진행
[664 / 3885] 	 17.09% 진행
[665 / 3885] 	 17.12% 진행
[666 / 3885] 	 17.14% 진행
[667 / 3885] 	 17.17% 진행
[668 / 3885] 	 17.19% 진행
[669 / 3885] 	 17.22% 진행
[670 / 3885] 	 17.25% 진행
[671 / 3885] 	 17.27% 진행
[672 / 3885] 	 17.30% 진행
[673 / 3885] 	 17.32% 진행
[674 / 3885] 	 17.35% 진행
[675 / 3885] 	 17.37% 진행
[676 / 3885] 	 17.40% 진행
[677 / 3885] 	 17.43% 진행
[678 / 3885] 	 17.45% 진행
[679 / 3885] 	 17.48% 진행
[680 / 3885] 	 17.50% 진행
[681 / 3885] 	 17.53% 진행
[682 / 3885] 	 17.55% 진행
[683 / 3885] 	 17.58% 진행
[684 / 3885] 	 17.61% 진행
[685 / 3885] 	 17.63% 진행
[686 / 3885] 	 17.66% 진행
[687 / 3885] 	 17.68% 진행
[688 / 3885] 	 17.71% 진행
[689 / 3885] 	 17.73% 진행
[690 / 3885] 	 17.76% 진행
[691 / 3885] 	 17.79% 진행
[692 / 3885] 	 17.81% 진행
[693 / 3885] 	 17.84% 진행
[694 / 3885] 	 17.86% 진행
[695 / 3885] 	 17.89% 진행
[696 / 3885] 	 17.92% 진행
[697 / 3885] 	 17.94% 진행
[698 / 3885] 	 17.97% 진행
[699 / 3885] 	 17.99% 진행
[700 / 3885] 	 18.02% 진행
[701 / 3885] 	 18.04% 진행
[702 / 3885] 	 18.07% 진행
[703 / 3885] 	 18.10% 진행
[704 / 3885] 	 18.12% 진행
[705 / 3885] 	 18.15% 진행
[706 / 3885] 	 18.17% 진행
[707 / 3885] 	 18.20% 진행
[708 / 3885] 	 18.22% 진행
[709 / 3885] 	 18.25% 진행
[710 / 3885] 	 18.28% 진행
[711 / 3885] 	 18.30% 진행
[712 / 3885] 	 18.33% 진행
[713 / 3885] 	 18.35% 진행
[714 / 3885] 	 18.38% 진행
[715 / 3885] 	 18.40% 진행
[716 / 3885] 	 18.43% 진행
[717 / 3885] 	 18.46% 진행
[718 / 3885] 	 18.48% 진행
[719 / 3885] 	 18.51% 진행
[720 / 3885] 	 18.53% 진행
[721 / 3885] 	 18.56% 진행
[722 / 3885] 	 18.58% 진행
[723 / 3885] 	 18.61% 진행
[724 / 3885] 	 18.64% 진행
[725 / 3885] 	 18.66% 진행
[726 / 3885] 	 18.69% 진행
[727 / 3885] 	 18.71% 진행
[728 / 3885] 	 18.74% 진행
[729 / 3885] 	 18.76% 진행
[730 / 3885] 	 18.79% 진행
[731 / 3885] 	 18.82% 진행
[732 / 3885] 	 18.84% 진행
[733 / 3885] 	 18.87% 진행
[734 / 3885] 	 18.89% 진행
[735 / 3885] 	 18.92% 진행
[736 / 3885] 	 18.94% 진행
[737 / 3885] 	 18.97% 진행
[738 / 3885] 	 19.00% 진행
[739 / 3885] 	 19.02% 진행
[740 / 3885] 	 19.05% 진행
[741 / 3885] 	 19.07% 진행
[742 / 3885] 	 19.10% 진행
[743 / 3885] 	 19.12% 진행
[744 / 3885] 	 19.15% 진행
[745 / 3885] 	 19.18% 진행
[746 / 3885] 	 19.20% 진행
[747 / 3885] 	 19.23% 진행
[748 / 3885] 	 19.25% 진행
[749 / 3885] 	 19.28% 진행
[750 / 3885] 	 19.31% 진행
[751 / 3885] 	 19.33% 진행
[752 / 3885] 	 19.36% 진행
[753 / 3885] 	 19.38% 진행
[754 / 3885] 	 19.41% 진행
[755 / 3885] 	 19.43% 진행
[756 / 3885] 	 19.46% 진행
[757 / 3885] 	 19.49% 진행
[758 / 3885] 	 19.51% 진행
[759 / 3885] 	 19.54% 진행
[760 / 3885] 	 19.56% 진행
[761 / 3885] 	 19.59% 진행
[762 / 3885] 	 19.61% 진행
[763 / 3885] 	 19.64% 진행
[764 / 3885] 	 19.67% 진행
[765 / 3885] 	 19.69% 진행
[766 / 3885] 	 19.72% 진행
[767 / 3885] 	 19.74% 진행
[768 / 3885] 	 19.77% 진행
[769 / 3885] 	 19.79% 진행
[770 / 3885] 	 19.82% 진행
[771 / 3885] 	 19.85% 진행
[772 / 3885] 	 19.87% 진행
[773 / 3885] 	 19.90% 진행
[774 / 3885] 	 19.92% 진행
[775 / 3885] 	 19.95% 진행
[776 / 3885] 	 19.97% 진행
오류가 발생했습니다.
[777 / 3885] 	 20.00% 진행 - 오류 발생
오류가 발생했습니다.
[778 / 3885] 	 20.03% 진행 - 오류 발생
오류가 발생했습니다.
[779 / 3885] 	 20.05% 진행 - 오류 발생
오류가 발생했습니다.
[780 / 3885] 	 20.08% 진행 - 오류 발생
오류가 발생했습니다.
[781 / 3885] 	 20.10% 진행 - 오류 발생
오류가 발생했습니다.
[782 / 3885] 	 20.13% 진행 - 오류 발생
오류가 발생했습니다.
[783 / 3885] 	 20.15% 진행 - 오류 발생
오류가 발생했습니다.
[784 / 3885] 	 20.18% 진행 - 오류 발생
오류가 발생했습니다.
[785 / 3885] 	 20.21% 진행 - 오류 발생
[786 / 3885] 	 20.23% 진행
[787 / 3885] 	 20.26% 진행
[788 / 3885] 	 20.28% 진행
[789 / 3885] 	 20.31% 진행
[790 / 3885] 	 20.33% 진행
[791 / 3885] 	 20.36% 진행
[792 / 3885] 	 20.39% 진행
[793 / 3885] 	 20.41% 진행
[794 / 3885] 	 20.44% 진행
[795 / 3885] 	 20.46% 진행
[796 / 3885] 	 20.49% 진행
[797 / 3885] 	 20.51% 진행
[798 / 3885] 	 20.54% 진행
[799 / 3885] 	 20.57% 진행
[800 / 3885] 	 20.59% 진행
[801 / 3885] 	 20.62% 진행
[802 / 3885] 	 20.64% 진행
[803 / 3885] 	 20.67% 진행
[804 / 3885] 	 20.69% 진행
[805 / 3885] 	 20.72% 진행
[806 / 3885] 	 20.75% 진행
[807 / 3885] 	 20.77% 진행
[808 / 3885] 	 20.80% 진행
[809 / 3885] 	 20.82% 진행
[810 / 3885] 	 20.85% 진행
[811 / 3885] 	 20.88% 진행
[812 / 3885] 	 20.90% 진행
[813 / 3885] 	 20.93% 진행
[814 / 3885] 	 20.95% 진행
[815 / 3885] 	 20.98% 진행
[816 / 3885] 	 21.00% 진행
[817 / 3885] 	 21.03% 진행
[818 / 3885] 	 21.06% 진행
[819 / 3885] 	 21.08% 진행
[820 / 3885] 	 21.11% 진행
[821 / 3885] 	 21.13% 진행
[822 / 3885] 	 21.16% 진행
[823 / 3885] 	 21.18% 진행
[824 / 3885] 	 21.21% 진행
[825 / 3885] 	 21.24% 진행
[826 / 3885] 	 21.26% 진행
[827 / 3885] 	 21.29% 진행
[828 / 3885] 	 21.31% 진행
[829 / 3885] 	 21.34% 진행
[830 / 3885] 	 21.36% 진행
[831 / 3885] 	 21.39% 진행
[832 / 3885] 	 21.42% 진행
[833 / 3885] 	 21.44% 진행
[834 / 3885] 	 21.47% 진행
[835 / 3885] 	 21.49% 진행
[836 / 3885] 	 21.52% 진행
[837 / 3885] 	 21.54% 진행
[838 / 3885] 	 21.57% 진행
[839 / 3885] 	 21.60% 진행
[840 / 3885] 	 21.62% 진행
[841 / 3885] 	 21.65% 진행
[842 / 3885] 	 21.67% 진행
[843 / 3885] 	 21.70% 진행
[844 / 3885] 	 21.72% 진행
[845 / 3885] 	 21.75% 진행
[846 / 3885] 	 21.78% 진행
[847 / 3885] 	 21.80% 진행
[848 / 3885] 	 21.83% 진행
[849 / 3885] 	 21.85% 진행
[850 / 3885] 	 21.88% 진행
[851 / 3885] 	 21.90% 진행
[852 / 3885] 	 21.93% 진행
[853 / 3885] 	 21.96% 진행
[854 / 3885] 	 21.98% 진행
[855 / 3885] 	 22.01% 진행
[856 / 3885] 	 22.03% 진행
[857 / 3885] 	 22.06% 진행
[858 / 3885] 	 22.08% 진행
[859 / 3885] 	 22.11% 진행
[860 / 3885] 	 22.14% 진행
[861 / 3885] 	 22.16% 진행
[862 / 3885] 	 22.19% 진행
[863 / 3885] 	 22.21% 진행
[864 / 3885] 	 22.24% 진행
[865 / 3885] 	 22.27% 진행
[866 / 3885] 	 22.29% 진행
[867 / 3885] 	 22.32% 진행
[868 / 3885] 	 22.34% 진행
[869 / 3885] 	 22.37% 진행
[870 / 3885] 	 22.39% 진행
[871 / 3885] 	 22.42% 진행
[872 / 3885] 	 22.45% 진행
[873 / 3885] 	 22.47% 진행
[874 / 3885] 	 22.50% 진행
[875 / 3885] 	 22.52% 진행
[876 / 3885] 	 22.55% 진행
[877 / 3885] 	 22.57% 진행
[878 / 3885] 	 22.60% 진행
[879 / 3885] 	 22.63% 진행
[880 / 3885] 	 22.65% 진행
[881 / 3885] 	 22.68% 진행
[882 / 3885] 	 22.70% 진행
[883 / 3885] 	 22.73% 진행
[884 / 3885] 	 22.75% 진행
[885 / 3885] 	 22.78% 진행
[886 / 3885] 	 22.81% 진행
[887 / 3885] 	 22.83% 진행
[888 / 3885] 	 22.86% 진행
[889 / 3885] 	 22.88% 진행
[890 / 3885] 	 22.91% 진행
[891 / 3885] 	 22.93% 진행
[892 / 3885] 	 22.96% 진행
[893 / 3885] 	 22.99% 진행
[894 / 3885] 	 23.01% 진행
[895 / 3885] 	 23.04% 진행
[896 / 3885] 	 23.06% 진행
[897 / 3885] 	 23.09% 진행
[898 / 3885] 	 23.11% 진행
[899 / 3885] 	 23.14% 진행
[900 / 3885] 	 23.17% 진행
[901 / 3885] 	 23.19% 진행
[902 / 3885] 	 23.22% 진행
[903 / 3885] 	 23.24% 진행
[904 / 3885] 	 23.27% 진행
[905 / 3885] 	 23.29% 진행
[906 / 3885] 	 23.32% 진행
[907 / 3885] 	 23.35% 진행
[908 / 3885] 	 23.37% 진행
[909 / 3885] 	 23.40% 진행
[910 / 3885] 	 23.42% 진행
[911 / 3885] 	 23.45% 진행
[912 / 3885] 	 23.47% 진행
[913 / 3885] 	 23.50% 진행
[914 / 3885] 	 23.53% 진행
[915 / 3885] 	 23.55% 진행
[916 / 3885] 	 23.58% 진행
[917 / 3885] 	 23.60% 진행
[918 / 3885] 	 23.63% 진행
[919 / 3885] 	 23.66% 진행
[920 / 3885] 	 23.68% 진행
[921 / 3885] 	 23.71% 진행
[922 / 3885] 	 23.73% 진행
[923 / 3885] 	 23.76% 진행
[924 / 3885] 	 23.78% 진행
[925 / 3885] 	 23.81% 진행
[926 / 3885] 	 23.84% 진행
[927 / 3885] 	 23.86% 진행
[928 / 3885] 	 23.89% 진행
[929 / 3885] 	 23.91% 진행
[930 / 3885] 	 23.94% 진행
[931 / 3885] 	 23.96% 진행
[932 / 3885] 	 23.99% 진행
[933 / 3885] 	 24.02% 진행
[934 / 3885] 	 24.04% 진행
[935 / 3885] 	 24.07% 진행
[936 / 3885] 	 24.09% 진행
[937 / 3885] 	 24.12% 진행
[938 / 3885] 	 24.14% 진행
[939 / 3885] 	 24.17% 진행
[940 / 3885] 	 24.20% 진행
[941 / 3885] 	 24.22% 진행
[942 / 3885] 	 24.25% 진행
[943 / 3885] 	 24.27% 진행
[944 / 3885] 	 24.30% 진행
[945 / 3885] 	 24.32% 진행
[946 / 3885] 	 24.35% 진행
[947 / 3885] 	 24.38% 진행
[948 / 3885] 	 24.40% 진행
[949 / 3885] 	 24.43% 진행
[950 / 3885] 	 24.45% 진행
[951 / 3885] 	 24.48% 진행
[952 / 3885] 	 24.50% 진행
[953 / 3885] 	 24.53% 진행
[954 / 3885] 	 24.56% 진행
[955 / 3885] 	 24.58% 진행
[956 / 3885] 	 24.61% 진행
[957 / 3885] 	 24.63% 진행
[958 / 3885] 	 24.66% 진행
[959 / 3885] 	 24.68% 진행
[960 / 3885] 	 24.71% 진행
[961 / 3885] 	 24.74% 진행
[962 / 3885] 	 24.76% 진행
[963 / 3885] 	 24.79% 진행
[964 / 3885] 	 24.81% 진행
[965 / 3885] 	 24.84% 진행
[966 / 3885] 	 24.86% 진행
[967 / 3885] 	 24.89% 진행
[968 / 3885] 	 24.92% 진행
[969 / 3885] 	 24.94% 진행
[970 / 3885] 	 24.97% 진행
[971 / 3885] 	 24.99% 진행
[972 / 3885] 	 25.02% 진행
[973 / 3885] 	 25.05% 진행
[974 / 3885] 	 25.07% 진행
[975 / 3885] 	 25.10% 진행
[976 / 3885] 	 25.12% 진행
[977 / 3885] 	 25.15% 진행
[978 / 3885] 	 25.17% 진행
[979 / 3885] 	 25.20% 진행
[980 / 3885] 	 25.23% 진행
[981 / 3885] 	 25.25% 진행
[982 / 3885] 	 25.28% 진행
[983 / 3885] 	 25.30% 진행
[984 / 3885] 	 25.33% 진행
[985 / 3885] 	 25.35% 진행
[986 / 3885] 	 25.38% 진행
[987 / 3885] 	 25.41% 진행
[988 / 3885] 	 25.43% 진행
[989 / 3885] 	 25.46% 진행
[990 / 3885] 	 25.48% 진행
[991 / 3885] 	 25.51% 진행
[992 / 3885] 	 25.53% 진행
[993 / 3885] 	 25.56% 진행
[994 / 3885] 	 25.59% 진행
[995 / 3885] 	 25.61% 진행
[996 / 3885] 	 25.64% 진행
[997 / 3885] 	 25.66% 진행
[998 / 3885] 	 25.69% 진행
[999 / 3885] 	 25.71% 진행
[1000 / 3885] 	 25.74% 진행
1000
[776, 777, 778, 779, 780, 781, 782, 783, 784]

In [ ]:
# 추출한 링크에 직접 방문하여 크롤링 진행 - 교수님 제공 코드 이용

# 크롤링 속도를 행상시키기 위해 time.sleep대신 WebDriverWait으로 변경 (다만 네트워크 불량 시 오래 걸릴 수 있음)
# WebDriverWait 이용 시 탐색 속도가 너무 빨라 봇 탐지 가능성 존재 -> time.sleep 이용 요망

# 진행상황 확인코드 추가

# 방문해야 하는 기사수가 3885로 매우 방대 하기 때문에 500개씩 끊어서 진행 (셀 단위)

i = 1000

for link in news_links[i:1500]:
    try:
        all_results[i] = dict()

        # 실제 네이버 뉴스 웹페이지로 이동
        driver.get(link)

        # 페이지 로딩 대기
        time.sleep(0.6) 

        # 제목 추출하기
        title = driver.find_elements(By.XPATH, '/html/body/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/p')
        title = title[0].text 

        # 본문 추출하기
        body = driver.find_elements(By.CLASS_NAME, 'article_content')
        body = body[0].text.replace('\n', '') 

        # 날짜 추출하기
        pubdate_element = driver.find_elements(By.XPATH, '/html/body/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[2]')
        pubdate = pubdate_element[0].text
        pubdate = pubdate[5:24]

        all_results[i]['link'] = link
        all_results[i]['pubdate'] = pubdate
        all_results[i]['title'] = title
        all_results[i]['body'] = body

        # 진행 상황 확인용 코드
        print(f"[{i+1} / {len(news_links)}] \t {(i+1)/len(news_links)*100:.2f}% 진행")    
        i += 1

        # 봇 탐지 방지를 위해 0.8초에서 1.5초 사이에 랜덤한 시간을 기다림
        time.sleep(random.uniform(0.8, 1.5))

    # 오류 발생 시
    except:
        print('오류가 발생했습니다.')
        err_idx.append(i)

        print(f"[{i+1} / {len(news_links)}] \t {(i+1)/len(news_links)*100:.2f}% 진행 - 오류 발생")    
        i += 1

        # 봇 탐지 방지를 위해 0.8초에서 1.5초 사이에 랜덤한 시간을 기다림
        time.sleep(random.uniform(0.8, 1.5))

print(len(all_results))
print(err_idx)

[1001 / 3885] 	 25.77% 진행
[1002 / 3885] 	 25.79% 진행
[1003 / 3885] 	 25.82% 진행
[1004 / 3885] 	 25.84% 진행
[1005 / 3885] 	 25.87% 진행
[1006 / 3885] 	 25.89% 진행
[1007 / 3885] 	 25.92% 진행
[1008 / 3885] 	 25.95% 진행
[1009 / 3885] 	 25.97% 진행
[1010 / 3885] 	 26.00% 진행
[1011 / 3885] 	 26.02% 진행
[1012 / 3885] 	 26.05% 진행
[1013 / 3885] 	 26.07% 진행
[1014 / 3885] 	 26.10% 진행
[1015 / 3885] 	 26.13% 진행
[1016 / 3885] 	 26.15% 진행
[1017 / 3885] 	 26.18% 진행
[1018 / 3885] 	 26.20% 진행
[1019 / 3885] 	 26.23% 진행
[1020 / 3885] 	 26.25% 진행
[1021 / 3885] 	 26.28% 진행
[1022 / 3885] 	 26.31% 진행
[1023 / 3885] 	 26.33% 진행
[1024 / 3885] 	 26.36% 진행
[1025 / 3885] 	 26.38% 진행
[1026 / 3885] 	 26.41% 진행
[1027 / 3885] 	 26.44% 진행
[1028 / 3885] 	 26.46% 진행
[1029 / 3885] 	 26.49% 진행
[1030 / 3885] 	 26.51% 진행
[1031 / 3885] 	 26.54% 진행
[1032 / 3885] 	 26.56% 진행
[1033 / 3885] 	 26.59% 진행
[1034 / 3885] 	 26.62% 진행
[1035 / 3885] 	 26.64% 진행
[1036 / 3885] 	 26.67% 진행
[1037 / 3885] 	 26.69% 진행
[1038 / 3885] 	 26.72% 진행
[1039 / 3885] 	 26.74% 진행
[1040 / 3885] 	 26.77% 진행
[1041 / 3885] 	 26.80% 진행
[1042 / 3885] 	 26.82% 진행
[1043 / 3885] 	 26.85% 진행
[1044 / 3885] 	 26.87% 진행
[1045 / 3885] 	 26.90% 진행
[1046 / 3885] 	 26.92% 진행
[1047 / 3885] 	 26.95% 진행
[1048 / 3885] 	 26.98% 진행
[1049 / 3885] 	 27.00% 진행
[1050 / 3885] 	 27.03% 진행
[1051 / 3885] 	 27.05% 진행
[1052 / 3885] 	 27.08% 진행
[1053 / 3885] 	 27.10% 진행
[1054 / 3885] 	 27.13% 진행
[1055 / 3885] 	 27.16% 진행
[1056 / 3885] 	 27.18% 진행
[1057 / 3885] 	 27.21% 진행
[1058 / 3885] 	 27.23% 진행
[1059 / 3885] 	 27.26% 진행
[1060 / 3885] 	 27.28% 진행
[1061 / 3885] 	 27.31% 진행
[1062 / 3885] 	 27.34% 진행
[1063 / 3885] 	 27.36% 진행
[1064 / 3885] 	 27.39% 진행
[1065 / 3885] 	 27.41% 진행
[1066 / 3885] 	 27.44% 진행
[1067 / 3885] 	 27.46% 진행
[1068 / 3885] 	 27.49% 진행
[1069 / 3885] 	 27.52% 진행
[1070 / 3885] 	 27.54% 진행
[1071 / 3885] 	 27.57% 진행
[1072 / 3885] 	 27.59% 진행
[1073 / 3885] 	 27.62% 진행
[1074 / 3885] 	 27.64% 진행
[1075 / 3885] 	 27.67% 진행
[1076 / 3885] 	 27.70% 진행
[1077 / 3885] 	 27.72% 진행
[1078 / 3885] 	 27.75% 진행
[1079 / 3885] 	 27.77% 진행
[1080 / 3885] 	 27.80% 진행
[1081 / 3885] 	 27.82% 진행
[1082 / 3885] 	 27.85% 진행
[1083 / 3885] 	 27.88% 진행
[1084 / 3885] 	 27.90% 진행
[1085 / 3885] 	 27.93% 진행
[1086 / 3885] 	 27.95% 진행
[1087 / 3885] 	 27.98% 진행
[1088 / 3885] 	 28.01% 진행
[1089 / 3885] 	 28.03% 진행
[1090 / 3885] 	 28.06% 진행
[1091 / 3885] 	 28.08% 진행
[1092 / 3885] 	 28.11% 진행
[1093 / 3885] 	 28.13% 진행
[1094 / 3885] 	 28.16% 진행
[1095 / 3885] 	 28.19% 진행
[1096 / 3885] 	 28.21% 진행
[1097 / 3885] 	 28.24% 진행
[1098 / 3885] 	 28.26% 진행
[1099 / 3885] 	 28.29% 진행
[1100 / 3885] 	 28.31% 진행
[1101 / 3885] 	 28.34% 진행
[1102 / 3885] 	 28.37% 진행
[1103 / 3885] 	 28.39% 진행
[1104 / 3885] 	 28.42% 진행
[1105 / 3885] 	 28.44% 진행
[1106 / 3885] 	 28.47% 진행
[1107 / 3885] 	 28.49% 진행
[1108 / 3885] 	 28.52% 진행
[1109 / 3885] 	 28.55% 진행
[1110 / 3885] 	 28.57% 진행
[1111 / 3885] 	 28.60% 진행
[1112 / 3885] 	 28.62% 진행
[1113 / 3885] 	 28.65% 진행
[1114 / 3885] 	 28.67% 진행
[1115 / 3885] 	 28.70% 진행
[1116 / 3885] 	 28.73% 진행
[1117 / 3885] 	 28.75% 진행
[1118 / 3885] 	 28.78% 진행
[1119 / 3885] 	 28.80% 진행
[1120 / 3885] 	 28.83% 진행
[1121 / 3885] 	 28.85% 진행
[1122 / 3885] 	 28.88% 진행
[1123 / 3885] 	 28.91% 진행
[1124 / 3885] 	 28.93% 진행
[1125 / 3885] 	 28.96% 진행
[1126 / 3885] 	 28.98% 진행
[1127 / 3885] 	 29.01% 진행
[1128 / 3885] 	 29.03% 진행
[1129 / 3885] 	 29.06% 진행
[1130 / 3885] 	 29.09% 진행
[1131 / 3885] 	 29.11% 진행
[1132 / 3885] 	 29.14% 진행
[1133 / 3885] 	 29.16% 진행
[1134 / 3885] 	 29.19% 진행
[1135 / 3885] 	 29.21% 진행
[1136 / 3885] 	 29.24% 진행
[1137 / 3885] 	 29.27% 진행
[1138 / 3885] 	 29.29% 진행
[1139 / 3885] 	 29.32% 진행
[1140 / 3885] 	 29.34% 진행
[1141 / 3885] 	 29.37% 진행
[1142 / 3885] 	 29.40% 진행
[1143 / 3885] 	 29.42% 진행
[1144 / 3885] 	 29.45% 진행
[1145 / 3885] 	 29.47% 진행
[1146 / 3885] 	 29.50% 진행
[1147 / 3885] 	 29.52% 진행
[1148 / 3885] 	 29.55% 진행
[1149 / 3885] 	 29.58% 진행
[1150 / 3885] 	 29.60% 진행
[1151 / 3885] 	 29.63% 진행
[1152 / 3885] 	 29.65% 진행
[1153 / 3885] 	 29.68% 진행
[1154 / 3885] 	 29.70% 진행
[1155 / 3885] 	 29.73% 진행
[1156 / 3885] 	 29.76% 진행
[1157 / 3885] 	 29.78% 진행
[1158 / 3885] 	 29.81% 진행
[1159 / 3885] 	 29.83% 진행
[1160 / 3885] 	 29.86% 진행
[1161 / 3885] 	 29.88% 진행
[1162 / 3885] 	 29.91% 진행
[1163 / 3885] 	 29.94% 진행
[1164 / 3885] 	 29.96% 진행
[1165 / 3885] 	 29.99% 진행
[1166 / 3885] 	 30.01% 진행
[1167 / 3885] 	 30.04% 진행
[1168 / 3885] 	 30.06% 진행
[1169 / 3885] 	 30.09% 진행
[1170 / 3885] 	 30.12% 진행
[1171 / 3885] 	 30.14% 진행
[1172 / 3885] 	 30.17% 진행
[1173 / 3885] 	 30.19% 진행
[1174 / 3885] 	 30.22% 진행
[1175 / 3885] 	 30.24% 진행
[1176 / 3885] 	 30.27% 진행
[1177 / 3885] 	 30.30% 진행
[1178 / 3885] 	 30.32% 진행
[1179 / 3885] 	 30.35% 진행
[1180 / 3885] 	 30.37% 진행
[1181 / 3885] 	 30.40% 진행
[1182 / 3885] 	 30.42% 진행
[1183 / 3885] 	 30.45% 진행
[1184 / 3885] 	 30.48% 진행
[1185 / 3885] 	 30.50% 진행
[1186 / 3885] 	 30.53% 진행
[1187 / 3885] 	 30.55% 진행
[1188 / 3885] 	 30.58% 진행
[1189 / 3885] 	 30.60% 진행
[1190 / 3885] 	 30.63% 진행
[1191 / 3885] 	 30.66% 진행
[1192 / 3885] 	 30.68% 진행
[1193 / 3885] 	 30.71% 진행
[1194 / 3885] 	 30.73% 진행
[1195 / 3885] 	 30.76% 진행
[1196 / 3885] 	 30.79% 진행
[1197 / 3885] 	 30.81% 진행
[1198 / 3885] 	 30.84% 진행
[1199 / 3885] 	 30.86% 진행
[1200 / 3885] 	 30.89% 진행
[1201 / 3885] 	 30.91% 진행
[1202 / 3885] 	 30.94% 진행
[1203 / 3885] 	 30.97% 진행
[1204 / 3885] 	 30.99% 진행
[1205 / 3885] 	 31.02% 진행
[1206 / 3885] 	 31.04% 진행
[1207 / 3885] 	 31.07% 진행
[1208 / 3885] 	 31.09% 진행
[1209 / 3885] 	 31.12% 진행
[1210 / 3885] 	 31.15% 진행
[1211 / 3885] 	 31.17% 진행
[1212 / 3885] 	 31.20% 진행
[1213 / 3885] 	 31.22% 진행
[1214 / 3885] 	 31.25% 진행
[1215 / 3885] 	 31.27% 진행
[1216 / 3885] 	 31.30% 진행
[1217 / 3885] 	 31.33% 진행
[1218 / 3885] 	 31.35% 진행
[1219 / 3885] 	 31.38% 진행
[1220 / 3885] 	 31.40% 진행
[1221 / 3885] 	 31.43% 진행
[1222 / 3885] 	 31.45% 진행
[1223 / 3885] 	 31.48% 진행
[1224 / 3885] 	 31.51% 진행
[1225 / 3885] 	 31.53% 진행
[1226 / 3885] 	 31.56% 진행
[1227 / 3885] 	 31.58% 진행
[1228 / 3885] 	 31.61% 진행
[1229 / 3885] 	 31.63% 진행
[1230 / 3885] 	 31.66% 진행
[1231 / 3885] 	 31.69% 진행
[1232 / 3885] 	 31.71% 진행
[1233 / 3885] 	 31.74% 진행
[1234 / 3885] 	 31.76% 진행
[1235 / 3885] 	 31.79% 진행
[1236 / 3885] 	 31.81% 진행
[1237 / 3885] 	 31.84% 진행
[1238 / 3885] 	 31.87% 진행
[1239 / 3885] 	 31.89% 진행
[1240 / 3885] 	 31.92% 진행
[1241 / 3885] 	 31.94% 진행
[1242 / 3885] 	 31.97% 진행
[1243 / 3885] 	 31.99% 진행
[1244 / 3885] 	 32.02% 진행
[1245 / 3885] 	 32.05% 진행
[1246 / 3885] 	 32.07% 진행
[1247 / 3885] 	 32.10% 진행
[1248 / 3885] 	 32.12% 진행
[1249 / 3885] 	 32.15% 진행
[1250 / 3885] 	 32.18% 진행
[1251 / 3885] 	 32.20% 진행
[1252 / 3885] 	 32.23% 진행
[1253 / 3885] 	 32.25% 진행
[1254 / 3885] 	 32.28% 진행
[1255 / 3885] 	 32.30% 진행
[1256 / 3885] 	 32.33% 진행
[1257 / 3885] 	 32.36% 진행
[1258 / 3885] 	 32.38% 진행
[1259 / 3885] 	 32.41% 진행
[1260 / 3885] 	 32.43% 진행
[1261 / 3885] 	 32.46% 진행
[1262 / 3885] 	 32.48% 진행
[1263 / 3885] 	 32.51% 진행
[1264 / 3885] 	 32.54% 진행
[1265 / 3885] 	 32.56% 진행
[1266 / 3885] 	 32.59% 진행
[1267 / 3885] 	 32.61% 진행
[1268 / 3885] 	 32.64% 진행
[1269 / 3885] 	 32.66% 진행
[1270 / 3885] 	 32.69% 진행
[1271 / 3885] 	 32.72% 진행
[1272 / 3885] 	 32.74% 진행
[1273 / 3885] 	 32.77% 진행
[1274 / 3885] 	 32.79% 진행
[1275 / 3885] 	 32.82% 진행
[1276 / 3885] 	 32.84% 진행
[1277 / 3885] 	 32.87% 진행
[1278 / 3885] 	 32.90% 진행
[1279 / 3885] 	 32.92% 진행
[1280 / 3885] 	 32.95% 진행
[1281 / 3885] 	 32.97% 진행
[1282 / 3885] 	 33.00% 진행
[1283 / 3885] 	 33.02% 진행
[1284 / 3885] 	 33.05% 진행
[1285 / 3885] 	 33.08% 진행
[1286 / 3885] 	 33.10% 진행
[1287 / 3885] 	 33.13% 진행
[1288 / 3885] 	 33.15% 진행
[1289 / 3885] 	 33.18% 진행
[1290 / 3885] 	 33.20% 진행
[1291 / 3885] 	 33.23% 진행
[1292 / 3885] 	 33.26% 진행
[1293 / 3885] 	 33.28% 진행
[1294 / 3885] 	 33.31% 진행
[1295 / 3885] 	 33.33% 진행
[1296 / 3885] 	 33.36% 진행
[1297 / 3885] 	 33.38% 진행
[1298 / 3885] 	 33.41% 진행
[1299 / 3885] 	 33.44% 진행
[1300 / 3885] 	 33.46% 진행
[1301 / 3885] 	 33.49% 진행
[1302 / 3885] 	 33.51% 진행
[1303 / 3885] 	 33.54% 진행
[1304 / 3885] 	 33.56% 진행
[1305 / 3885] 	 33.59% 진행
[1306 / 3885] 	 33.62% 진행
[1307 / 3885] 	 33.64% 진행
[1308 / 3885] 	 33.67% 진행
[1309 / 3885] 	 33.69% 진행
[1310 / 3885] 	 33.72% 진행
[1311 / 3885] 	 33.75% 진행
[1312 / 3885] 	 33.77% 진행
[1313 / 3885] 	 33.80% 진행
[1314 / 3885] 	 33.82% 진행
[1315 / 3885] 	 33.85% 진행
[1316 / 3885] 	 33.87% 진행
[1317 / 3885] 	 33.90% 진행
[1318 / 3885] 	 33.93% 진행
[1319 / 3885] 	 33.95% 진행
[1320 / 3885] 	 33.98% 진행
[1321 / 3885] 	 34.00% 진행
[1322 / 3885] 	 34.03% 진행
[1323 / 3885] 	 34.05% 진행
[1324 / 3885] 	 34.08% 진행
[1325 / 3885] 	 34.11% 진행
[1326 / 3885] 	 34.13% 진행
[1327 / 3885] 	 34.16% 진행
[1328 / 3885] 	 34.18% 진행
[1329 / 3885] 	 34.21% 진행
[1330 / 3885] 	 34.23% 진행
[1331 / 3885] 	 34.26% 진행
[1332 / 3885] 	 34.29% 진행
[1333 / 3885] 	 34.31% 진행
[1334 / 3885] 	 34.34% 진행
[1335 / 3885] 	 34.36% 진행
[1336 / 3885] 	 34.39% 진행
[1337 / 3885] 	 34.41% 진행
[1338 / 3885] 	 34.44% 진행
[1339 / 3885] 	 34.47% 진행
[1340 / 3885] 	 34.49% 진행
[1341 / 3885] 	 34.52% 진행
[1342 / 3885] 	 34.54% 진행
[1343 / 3885] 	 34.57% 진행
[1344 / 3885] 	 34.59% 진행
[1345 / 3885] 	 34.62% 진행
[1346 / 3885] 	 34.65% 진행
[1347 / 3885] 	 34.67% 진행
[1348 / 3885] 	 34.70% 진행
[1349 / 3885] 	 34.72% 진행
[1350 / 3885] 	 34.75% 진행
[1351 / 3885] 	 34.77% 진행
[1352 / 3885] 	 34.80% 진행
[1353 / 3885] 	 34.83% 진행
[1354 / 3885] 	 34.85% 진행
[1355 / 3885] 	 34.88% 진행
[1356 / 3885] 	 34.90% 진행
[1357 / 3885] 	 34.93% 진행
[1358 / 3885] 	 34.95% 진행
[1359 / 3885] 	 34.98% 진행
[1360 / 3885] 	 35.01% 진행
[1361 / 3885] 	 35.03% 진행
[1362 / 3885] 	 35.06% 진행
[1363 / 3885] 	 35.08% 진행
[1364 / 3885] 	 35.11% 진행
[1365 / 3885] 	 35.14% 진행
[1366 / 3885] 	 35.16% 진행
[1367 / 3885] 	 35.19% 진행
[1368 / 3885] 	 35.21% 진행
[1369 / 3885] 	 35.24% 진행
[1370 / 3885] 	 35.26% 진행
[1371 / 3885] 	 35.29% 진행
[1372 / 3885] 	 35.32% 진행
[1373 / 3885] 	 35.34% 진행
[1374 / 3885] 	 35.37% 진행
[1375 / 3885] 	 35.39% 진행
[1376 / 3885] 	 35.42% 진행
[1377 / 3885] 	 35.44% 진행
[1378 / 3885] 	 35.47% 진행
[1379 / 3885] 	 35.50% 진행
[1380 / 3885] 	 35.52% 진행
[1381 / 3885] 	 35.55% 진행
[1382 / 3885] 	 35.57% 진행
[1383 / 3885] 	 35.60% 진행
[1384 / 3885] 	 35.62% 진행
[1385 / 3885] 	 35.65% 진행
[1386 / 3885] 	 35.68% 진행
[1387 / 3885] 	 35.70% 진행
[1388 / 3885] 	 35.73% 진행
[1389 / 3885] 	 35.75% 진행
[1390 / 3885] 	 35.78% 진행
[1391 / 3885] 	 35.80% 진행
[1392 / 3885] 	 35.83% 진행
[1393 / 3885] 	 35.86% 진행
[1394 / 3885] 	 35.88% 진행
[1395 / 3885] 	 35.91% 진행
[1396 / 3885] 	 35.93% 진행
[1397 / 3885] 	 35.96% 진행
[1398 / 3885] 	 35.98% 진행
[1399 / 3885] 	 36.01% 진행
[1400 / 3885] 	 36.04% 진행
[1401 / 3885] 	 36.06% 진행
[1402 / 3885] 	 36.09% 진행
[1403 / 3885] 	 36.11% 진행
[1404 / 3885] 	 36.14% 진행
[1405 / 3885] 	 36.16% 진행
[1406 / 3885] 	 36.19% 진행
[1407 / 3885] 	 36.22% 진행
[1408 / 3885] 	 36.24% 진행
[1409 / 3885] 	 36.27% 진행
[1410 / 3885] 	 36.29% 진행
[1411 / 3885] 	 36.32% 진행
[1412 / 3885] 	 36.34% 진행
[1413 / 3885] 	 36.37% 진행
[1414 / 3885] 	 36.40% 진행
[1415 / 3885] 	 36.42% 진행
[1416 / 3885] 	 36.45% 진행
[1417 / 3885] 	 36.47% 진행
[1418 / 3885] 	 36.50% 진행
[1419 / 3885] 	 36.53% 진행
[1420 / 3885] 	 36.55% 진행
[1421 / 3885] 	 36.58% 진행
[1422 / 3885] 	 36.60% 진행
[1423 / 3885] 	 36.63% 진행
[1424 / 3885] 	 36.65% 진행
[1425 / 3885] 	 36.68% 진행
[1426 / 3885] 	 36.71% 진행
[1427 / 3885] 	 36.73% 진행
[1428 / 3885] 	 36.76% 진행
[1429 / 3885] 	 36.78% 진행
[1430 / 3885] 	 36.81% 진행
[1431 / 3885] 	 36.83% 진행
[1432 / 3885] 	 36.86% 진행
[1433 / 3885] 	 36.89% 진행
[1434 / 3885] 	 36.91% 진행
[1435 / 3885] 	 36.94% 진행
[1436 / 3885] 	 36.96% 진행
[1437 / 3885] 	 36.99% 진행
[1438 / 3885] 	 37.01% 진행
[1439 / 3885] 	 37.04% 진행
[1440 / 3885] 	 37.07% 진행
[1441 / 3885] 	 37.09% 진행
[1442 / 3885] 	 37.12% 진행
[1443 / 3885] 	 37.14% 진행
[1444 / 3885] 	 37.17% 진행
[1445 / 3885] 	 37.19% 진행
[1446 / 3885] 	 37.22% 진행
[1447 / 3885] 	 37.25% 진행
[1448 / 3885] 	 37.27% 진행
[1449 / 3885] 	 37.30% 진행
[1450 / 3885] 	 37.32% 진행
[1451 / 3885] 	 37.35% 진행
[1452 / 3885] 	 37.37% 진행
[1453 / 3885] 	 37.40% 진행
[1454 / 3885] 	 37.43% 진행
[1455 / 3885] 	 37.45% 진행
[1456 / 3885] 	 37.48% 진행
[1457 / 3885] 	 37.50% 진행
[1458 / 3885] 	 37.53% 진행
[1459 / 3885] 	 37.55% 진행
[1460 / 3885] 	 37.58% 진행
[1461 / 3885] 	 37.61% 진행
[1462 / 3885] 	 37.63% 진행
[1463 / 3885] 	 37.66% 진행
[1464 / 3885] 	 37.68% 진행
[1465 / 3885] 	 37.71% 진행
[1466 / 3885] 	 37.73% 진행
[1467 / 3885] 	 37.76% 진행
[1468 / 3885] 	 37.79% 진행
[1469 / 3885] 	 37.81% 진행
[1470 / 3885] 	 37.84% 진행
[1471 / 3885] 	 37.86% 진행
[1472 / 3885] 	 37.89% 진행
[1473 / 3885] 	 37.92% 진행
[1474 / 3885] 	 37.94% 진행
[1475 / 3885] 	 37.97% 진행
[1476 / 3885] 	 37.99% 진행
[1477 / 3885] 	 38.02% 진행
[1478 / 3885] 	 38.04% 진행
[1479 / 3885] 	 38.07% 진행
[1480 / 3885] 	 38.10% 진행
[1481 / 3885] 	 38.12% 진행
[1482 / 3885] 	 38.15% 진행
[1483 / 3885] 	 38.17% 진행
[1484 / 3885] 	 38.20% 진행
[1485 / 3885] 	 38.22% 진행
[1486 / 3885] 	 38.25% 진행
[1487 / 3885] 	 38.28% 진행
[1488 / 3885] 	 38.30% 진행
[1489 / 3885] 	 38.33% 진행
[1490 / 3885] 	 38.35% 진행
[1491 / 3885] 	 38.38% 진행
[1492 / 3885] 	 38.40% 진행
[1493 / 3885] 	 38.43% 진행
[1494 / 3885] 	 38.46% 진행
[1495 / 3885] 	 38.48% 진행
[1496 / 3885] 	 38.51% 진행
[1497 / 3885] 	 38.53% 진행
[1498 / 3885] 	 38.56% 진행
[1499 / 3885] 	 38.58% 진행
[1500 / 3885] 	 38.61% 진행
1500
[776, 777, 778, 779, 780, 781, 782, 783, 784]

In [ ]:
# 추출한 링크에 직접 방문하여 크롤링 진행 - 교수님 제공 코드 이용

# 크롤링 속도를 행상시키기 위해 time.sleep대신 WebDriverWait으로 변경 (다만 네트워크 불량 시 오래 걸릴 수 있음)
# WebDriverWait 이용 시 탐색 속도가 너무 빨라 봇 탐지 가능성 존재 -> time.sleep 이용 요망

# 진행상황 확인코드 추가

# 방문해야 하는 기사수가 3885로 매우 방대 하기 때문에 500개씩 끊어서 진행 (셀 단위)

i = 1500

for link in news_links[i:2000]:
    try:
        all_results[i] = dict()

        # 실제 네이버 뉴스 웹페이지로 이동
        driver.get(link)

        # 페이지 로딩 대기
        time.sleep(0.6) 

        # 제목 추출하기
        title = driver.find_elements(By.XPATH, '/html/body/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/p')
        title = title[0].text 

        # 본문 추출하기
        body = driver.find_elements(By.CLASS_NAME, 'article_content')
        body = body[0].text.replace('\n', '') 

        # 날짜 추출하기
        pubdate_element = driver.find_elements(By.XPATH, '/html/body/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[2]')
        pubdate = pubdate_element[0].text
        pubdate = pubdate[5:24]

        all_results[i]['link'] = link
        all_results[i]['pubdate'] = pubdate
        all_results[i]['title'] = title
        all_results[i]['body'] = body

        # 진행 상황 확인용 코드
        print(f"[{i+1} / {len(news_links)}] \t {(i+1)/len(news_links)*100:.2f}% 진행")    
        i += 1

        # 봇 탐지 방지를 위해 0.8초에서 1.5초 사이에 랜덤한 시간을 기다림
        time.sleep(random.uniform(0.8, 1.5))

    # 오류 발생 시
    except:
        print('오류가 발생했습니다.')
        err_idx.append(i)

        print(f"[{i+1} / {len(news_links)}] \t {(i+1)/len(news_links)*100:.2f}% 진행 - 오류 발생")    
        i += 1

        # 봇 탐지 방지를 위해 0.8초에서 1.5초 사이에 랜덤한 시간을 기다림
        time.sleep(random.uniform(0.8, 1.5))

print(len(all_results))
print(err_idx)

[1501 / 3885] 	 38.64% 진행
[1502 / 3885] 	 38.66% 진행
[1503 / 3885] 	 38.69% 진행
[1504 / 3885] 	 38.71% 진행
[1505 / 3885] 	 38.74% 진행
[1506 / 3885] 	 38.76% 진행
[1507 / 3885] 	 38.79% 진행
[1508 / 3885] 	 38.82% 진행
[1509 / 3885] 	 38.84% 진행
[1510 / 3885] 	 38.87% 진행
[1511 / 3885] 	 38.89% 진행
[1512 / 3885] 	 38.92% 진행
[1513 / 3885] 	 38.94% 진행
[1514 / 3885] 	 38.97% 진행
[1515 / 3885] 	 39.00% 진행
[1516 / 3885] 	 39.02% 진행
[1517 / 3885] 	 39.05% 진행
[1518 / 3885] 	 39.07% 진행
[1519 / 3885] 	 39.10% 진행
[1520 / 3885] 	 39.12% 진행
[1521 / 3885] 	 39.15% 진행
[1522 / 3885] 	 39.18% 진행
[1523 / 3885] 	 39.20% 진행
[1524 / 3885] 	 39.23% 진행
[1525 / 3885] 	 39.25% 진행
[1526 / 3885] 	 39.28% 진행
[1527 / 3885] 	 39.31% 진행
[1528 / 3885] 	 39.33% 진행
[1529 / 3885] 	 39.36% 진행
[1530 / 3885] 	 39.38% 진행
[1531 / 3885] 	 39.41% 진행
[1532 / 3885] 	 39.43% 진행
[1533 / 3885] 	 39.46% 진행
[1534 / 3885] 	 39.49% 진행
[1535 / 3885] 	 39.51% 진행
[1536 / 3885] 	 39.54% 진행
[1537 / 3885] 	 39.56% 진행
[1538 / 3885] 	 39.59% 진행
[1539 / 3885] 	 39.61% 진행
[1540 / 3885] 	 39.64% 진행
[1541 / 3885] 	 39.67% 진행
[1542 / 3885] 	 39.69% 진행
[1543 / 3885] 	 39.72% 진행
[1544 / 3885] 	 39.74% 진행
[1545 / 3885] 	 39.77% 진행
[1546 / 3885] 	 39.79% 진행
[1547 / 3885] 	 39.82% 진행
[1548 / 3885] 	 39.85% 진행
[1549 / 3885] 	 39.87% 진행
[1550 / 3885] 	 39.90% 진행
[1551 / 3885] 	 39.92% 진행
[1552 / 3885] 	 39.95% 진행
[1553 / 3885] 	 39.97% 진행
[1554 / 3885] 	 40.00% 진행
[1555 / 3885] 	 40.03% 진행
[1556 / 3885] 	 40.05% 진행
[1557 / 3885] 	 40.08% 진행
[1558 / 3885] 	 40.10% 진행
[1559 / 3885] 	 40.13% 진행
[1560 / 3885] 	 40.15% 진행
[1561 / 3885] 	 40.18% 진행
[1562 / 3885] 	 40.21% 진행
[1563 / 3885] 	 40.23% 진행
[1564 / 3885] 	 40.26% 진행
[1565 / 3885] 	 40.28% 진행
[1566 / 3885] 	 40.31% 진행
[1567 / 3885] 	 40.33% 진행
[1568 / 3885] 	 40.36% 진행
[1569 / 3885] 	 40.39% 진행
[1570 / 3885] 	 40.41% 진행
[1571 / 3885] 	 40.44% 진행
[1572 / 3885] 	 40.46% 진행
[1573 / 3885] 	 40.49% 진행
[1574 / 3885] 	 40.51% 진행
[1575 / 3885] 	 40.54% 진행
[1576 / 3885] 	 40.57% 진행
[1577 / 3885] 	 40.59% 진행
[1578 / 3885] 	 40.62% 진행
[1579 / 3885] 	 40.64% 진행
[1580 / 3885] 	 40.67% 진행
[1581 / 3885] 	 40.69% 진행
[1582 / 3885] 	 40.72% 진행
[1583 / 3885] 	 40.75% 진행
[1584 / 3885] 	 40.77% 진행
[1585 / 3885] 	 40.80% 진행
[1586 / 3885] 	 40.82% 진행
[1587 / 3885] 	 40.85% 진행
[1588 / 3885] 	 40.88% 진행
[1589 / 3885] 	 40.90% 진행
[1590 / 3885] 	 40.93% 진행
[1591 / 3885] 	 40.95% 진행
[1592 / 3885] 	 40.98% 진행
[1593 / 3885] 	 41.00% 진행
[1594 / 3885] 	 41.03% 진행
[1595 / 3885] 	 41.06% 진행
[1596 / 3885] 	 41.08% 진행
[1597 / 3885] 	 41.11% 진행
[1598 / 3885] 	 41.13% 진행
[1599 / 3885] 	 41.16% 진행
[1600 / 3885] 	 41.18% 진행
[1601 / 3885] 	 41.21% 진행
[1602 / 3885] 	 41.24% 진행
[1603 / 3885] 	 41.26% 진행
[1604 / 3885] 	 41.29% 진행
[1605 / 3885] 	 41.31% 진행
[1606 / 3885] 	 41.34% 진행
[1607 / 3885] 	 41.36% 진행
[1608 / 3885] 	 41.39% 진행
[1609 / 3885] 	 41.42% 진행
[1610 / 3885] 	 41.44% 진행
[1611 / 3885] 	 41.47% 진행
[1612 / 3885] 	 41.49% 진행
[1613 / 3885] 	 41.52% 진행
[1614 / 3885] 	 41.54% 진행
[1615 / 3885] 	 41.57% 진행
[1616 / 3885] 	 41.60% 진행
[1617 / 3885] 	 41.62% 진행
[1618 / 3885] 	 41.65% 진행
[1619 / 3885] 	 41.67% 진행
[1620 / 3885] 	 41.70% 진행
[1621 / 3885] 	 41.72% 진행
[1622 / 3885] 	 41.75% 진행
[1623 / 3885] 	 41.78% 진행
[1624 / 3885] 	 41.80% 진행
[1625 / 3885] 	 41.83% 진행
[1626 / 3885] 	 41.85% 진행
[1627 / 3885] 	 41.88% 진행
[1628 / 3885] 	 41.90% 진행
[1629 / 3885] 	 41.93% 진행
[1630 / 3885] 	 41.96% 진행
[1631 / 3885] 	 41.98% 진행
[1632 / 3885] 	 42.01% 진행
[1633 / 3885] 	 42.03% 진행
[1634 / 3885] 	 42.06% 진행
[1635 / 3885] 	 42.08% 진행
[1636 / 3885] 	 42.11% 진행
[1637 / 3885] 	 42.14% 진행
[1638 / 3885] 	 42.16% 진행
[1639 / 3885] 	 42.19% 진행
[1640 / 3885] 	 42.21% 진행
[1641 / 3885] 	 42.24% 진행
[1642 / 3885] 	 42.27% 진행
[1643 / 3885] 	 42.29% 진행
[1644 / 3885] 	 42.32% 진행
[1645 / 3885] 	 42.34% 진행
[1646 / 3885] 	 42.37% 진행
[1647 / 3885] 	 42.39% 진행
[1648 / 3885] 	 42.42% 진행
[1649 / 3885] 	 42.45% 진행
[1650 / 3885] 	 42.47% 진행
[1651 / 3885] 	 42.50% 진행
[1652 / 3885] 	 42.52% 진행
[1653 / 3885] 	 42.55% 진행
[1654 / 3885] 	 42.57% 진행
[1655 / 3885] 	 42.60% 진행
[1656 / 3885] 	 42.63% 진행
[1657 / 3885] 	 42.65% 진행
[1658 / 3885] 	 42.68% 진행
[1659 / 3885] 	 42.70% 진행
[1660 / 3885] 	 42.73% 진행
[1661 / 3885] 	 42.75% 진행
[1662 / 3885] 	 42.78% 진행
[1663 / 3885] 	 42.81% 진행
[1664 / 3885] 	 42.83% 진행
[1665 / 3885] 	 42.86% 진행
[1666 / 3885] 	 42.88% 진행
[1667 / 3885] 	 42.91% 진행
[1668 / 3885] 	 42.93% 진행
[1669 / 3885] 	 42.96% 진행
[1670 / 3885] 	 42.99% 진행
[1671 / 3885] 	 43.01% 진행
[1672 / 3885] 	 43.04% 진행
[1673 / 3885] 	 43.06% 진행
[1674 / 3885] 	 43.09% 진행
[1675 / 3885] 	 43.11% 진행
[1676 / 3885] 	 43.14% 진행
[1677 / 3885] 	 43.17% 진행
[1678 / 3885] 	 43.19% 진행
[1679 / 3885] 	 43.22% 진행
[1680 / 3885] 	 43.24% 진행
[1681 / 3885] 	 43.27% 진행
[1682 / 3885] 	 43.29% 진행
[1683 / 3885] 	 43.32% 진행
[1684 / 3885] 	 43.35% 진행
[1685 / 3885] 	 43.37% 진행
[1686 / 3885] 	 43.40% 진행
[1687 / 3885] 	 43.42% 진행
[1688 / 3885] 	 43.45% 진행
[1689 / 3885] 	 43.47% 진행
[1690 / 3885] 	 43.50% 진행
[1691 / 3885] 	 43.53% 진행
[1692 / 3885] 	 43.55% 진행
[1693 / 3885] 	 43.58% 진행
[1694 / 3885] 	 43.60% 진행
[1695 / 3885] 	 43.63% 진행
[1696 / 3885] 	 43.66% 진행
[1697 / 3885] 	 43.68% 진행
[1698 / 3885] 	 43.71% 진행
[1699 / 3885] 	 43.73% 진행
[1700 / 3885] 	 43.76% 진행
[1701 / 3885] 	 43.78% 진행
[1702 / 3885] 	 43.81% 진행
[1703 / 3885] 	 43.84% 진행
[1704 / 3885] 	 43.86% 진행
[1705 / 3885] 	 43.89% 진행
[1706 / 3885] 	 43.91% 진행
[1707 / 3885] 	 43.94% 진행
[1708 / 3885] 	 43.96% 진행
[1709 / 3885] 	 43.99% 진행
[1710 / 3885] 	 44.02% 진행
[1711 / 3885] 	 44.04% 진행
[1712 / 3885] 	 44.07% 진행
[1713 / 3885] 	 44.09% 진행
[1714 / 3885] 	 44.12% 진행
[1715 / 3885] 	 44.14% 진행
[1716 / 3885] 	 44.17% 진행
[1717 / 3885] 	 44.20% 진행
[1718 / 3885] 	 44.22% 진행
[1719 / 3885] 	 44.25% 진행
[1720 / 3885] 	 44.27% 진행
[1721 / 3885] 	 44.30% 진행
[1722 / 3885] 	 44.32% 진행
[1723 / 3885] 	 44.35% 진행
[1724 / 3885] 	 44.38% 진행
[1725 / 3885] 	 44.40% 진행
[1726 / 3885] 	 44.43% 진행
[1727 / 3885] 	 44.45% 진행
[1728 / 3885] 	 44.48% 진행
[1729 / 3885] 	 44.50% 진행
[1730 / 3885] 	 44.53% 진행
[1731 / 3885] 	 44.56% 진행
[1732 / 3885] 	 44.58% 진행
[1733 / 3885] 	 44.61% 진행
[1734 / 3885] 	 44.63% 진행
[1735 / 3885] 	 44.66% 진행
[1736 / 3885] 	 44.68% 진행
[1737 / 3885] 	 44.71% 진행
[1738 / 3885] 	 44.74% 진행
[1739 / 3885] 	 44.76% 진행
[1740 / 3885] 	 44.79% 진행
[1741 / 3885] 	 44.81% 진행
[1742 / 3885] 	 44.84% 진행
[1743 / 3885] 	 44.86% 진행
[1744 / 3885] 	 44.89% 진행
[1745 / 3885] 	 44.92% 진행
[1746 / 3885] 	 44.94% 진행
[1747 / 3885] 	 44.97% 진행
[1748 / 3885] 	 44.99% 진행
[1749 / 3885] 	 45.02% 진행
[1750 / 3885] 	 45.05% 진행
[1751 / 3885] 	 45.07% 진행
[1752 / 3885] 	 45.10% 진행
[1753 / 3885] 	 45.12% 진행
[1754 / 3885] 	 45.15% 진행
[1755 / 3885] 	 45.17% 진행
[1756 / 3885] 	 45.20% 진행
[1757 / 3885] 	 45.23% 진행
[1758 / 3885] 	 45.25% 진행
[1759 / 3885] 	 45.28% 진행
[1760 / 3885] 	 45.30% 진행
[1761 / 3885] 	 45.33% 진행
[1762 / 3885] 	 45.35% 진행
[1763 / 3885] 	 45.38% 진행
[1764 / 3885] 	 45.41% 진행
[1765 / 3885] 	 45.43% 진행
[1766 / 3885] 	 45.46% 진행
[1767 / 3885] 	 45.48% 진행
[1768 / 3885] 	 45.51% 진행
[1769 / 3885] 	 45.53% 진행
[1770 / 3885] 	 45.56% 진행
[1771 / 3885] 	 45.59% 진행
[1772 / 3885] 	 45.61% 진행
[1773 / 3885] 	 45.64% 진행
[1774 / 3885] 	 45.66% 진행
[1775 / 3885] 	 45.69% 진행
[1776 / 3885] 	 45.71% 진행
[1777 / 3885] 	 45.74% 진행
[1778 / 3885] 	 45.77% 진행
[1779 / 3885] 	 45.79% 진행
[1780 / 3885] 	 45.82% 진행
[1781 / 3885] 	 45.84% 진행
[1782 / 3885] 	 45.87% 진행
[1783 / 3885] 	 45.89% 진행
[1784 / 3885] 	 45.92% 진행
[1785 / 3885] 	 45.95% 진행
[1786 / 3885] 	 45.97% 진행
[1787 / 3885] 	 46.00% 진행
[1788 / 3885] 	 46.02% 진행
[1789 / 3885] 	 46.05% 진행
[1790 / 3885] 	 46.07% 진행
[1791 / 3885] 	 46.10% 진행
[1792 / 3885] 	 46.13% 진행
[1793 / 3885] 	 46.15% 진행
[1794 / 3885] 	 46.18% 진행
[1795 / 3885] 	 46.20% 진행
[1796 / 3885] 	 46.23% 진행
[1797 / 3885] 	 46.25% 진행
[1798 / 3885] 	 46.28% 진행
[1799 / 3885] 	 46.31% 진행
[1800 / 3885] 	 46.33% 진행
[1801 / 3885] 	 46.36% 진행
[1802 / 3885] 	 46.38% 진행
[1803 / 3885] 	 46.41% 진행
[1804 / 3885] 	 46.44% 진행
[1805 / 3885] 	 46.46% 진행
[1806 / 3885] 	 46.49% 진행
[1807 / 3885] 	 46.51% 진행
[1808 / 3885] 	 46.54% 진행
[1809 / 3885] 	 46.56% 진행
[1810 / 3885] 	 46.59% 진행
[1811 / 3885] 	 46.62% 진행
[1812 / 3885] 	 46.64% 진행
[1813 / 3885] 	 46.67% 진행
[1814 / 3885] 	 46.69% 진행
[1815 / 3885] 	 46.72% 진행
[1816 / 3885] 	 46.74% 진행
[1817 / 3885] 	 46.77% 진행
[1818 / 3885] 	 46.80% 진행
[1819 / 3885] 	 46.82% 진행
[1820 / 3885] 	 46.85% 진행
[1821 / 3885] 	 46.87% 진행
[1822 / 3885] 	 46.90% 진행
[1823 / 3885] 	 46.92% 진행
[1824 / 3885] 	 46.95% 진행
[1825 / 3885] 	 46.98% 진행
[1826 / 3885] 	 47.00% 진행
[1827 / 3885] 	 47.03% 진행
[1828 / 3885] 	 47.05% 진행
[1829 / 3885] 	 47.08% 진행
[1830 / 3885] 	 47.10% 진행
[1831 / 3885] 	 47.13% 진행
[1832 / 3885] 	 47.16% 진행
[1833 / 3885] 	 47.18% 진행
[1834 / 3885] 	 47.21% 진행
[1835 / 3885] 	 47.23% 진행
[1836 / 3885] 	 47.26% 진행
[1837 / 3885] 	 47.28% 진행
[1838 / 3885] 	 47.31% 진행
[1839 / 3885] 	 47.34% 진행
[1840 / 3885] 	 47.36% 진행
[1841 / 3885] 	 47.39% 진행
[1842 / 3885] 	 47.41% 진행
[1843 / 3885] 	 47.44% 진행
[1844 / 3885] 	 47.46% 진행
[1845 / 3885] 	 47.49% 진행
[1846 / 3885] 	 47.52% 진행
[1847 / 3885] 	 47.54% 진행
[1848 / 3885] 	 47.57% 진행
[1849 / 3885] 	 47.59% 진행
[1850 / 3885] 	 47.62% 진행
[1851 / 3885] 	 47.64% 진행
[1852 / 3885] 	 47.67% 진행
[1853 / 3885] 	 47.70% 진행
[1854 / 3885] 	 47.72% 진행
[1855 / 3885] 	 47.75% 진행
[1856 / 3885] 	 47.77% 진행
[1857 / 3885] 	 47.80% 진행
[1858 / 3885] 	 47.82% 진행
[1859 / 3885] 	 47.85% 진행
[1860 / 3885] 	 47.88% 진행
[1861 / 3885] 	 47.90% 진행
[1862 / 3885] 	 47.93% 진행
[1863 / 3885] 	 47.95% 진행
[1864 / 3885] 	 47.98% 진행
[1865 / 3885] 	 48.01% 진행
[1866 / 3885] 	 48.03% 진행
[1867 / 3885] 	 48.06% 진행
[1868 / 3885] 	 48.08% 진행
[1869 / 3885] 	 48.11% 진행
[1870 / 3885] 	 48.13% 진행
[1871 / 3885] 	 48.16% 진행
[1872 / 3885] 	 48.19% 진행
[1873 / 3885] 	 48.21% 진행
[1874 / 3885] 	 48.24% 진행
[1875 / 3885] 	 48.26% 진행
[1876 / 3885] 	 48.29% 진행
[1877 / 3885] 	 48.31% 진행
[1878 / 3885] 	 48.34% 진행
[1879 / 3885] 	 48.37% 진행
[1880 / 3885] 	 48.39% 진행
[1881 / 3885] 	 48.42% 진행
[1882 / 3885] 	 48.44% 진행
[1883 / 3885] 	 48.47% 진행
[1884 / 3885] 	 48.49% 진행
[1885 / 3885] 	 48.52% 진행
[1886 / 3885] 	 48.55% 진행
[1887 / 3885] 	 48.57% 진행
[1888 / 3885] 	 48.60% 진행
[1889 / 3885] 	 48.62% 진행
[1890 / 3885] 	 48.65% 진행
[1891 / 3885] 	 48.67% 진행
[1892 / 3885] 	 48.70% 진행
[1893 / 3885] 	 48.73% 진행
[1894 / 3885] 	 48.75% 진행
[1895 / 3885] 	 48.78% 진행
[1896 / 3885] 	 48.80% 진행
[1897 / 3885] 	 48.83% 진행
[1898 / 3885] 	 48.85% 진행
[1899 / 3885] 	 48.88% 진행
[1900 / 3885] 	 48.91% 진행
[1901 / 3885] 	 48.93% 진행
[1902 / 3885] 	 48.96% 진행
[1903 / 3885] 	 48.98% 진행
[1904 / 3885] 	 49.01% 진행
[1905 / 3885] 	 49.03% 진행
[1906 / 3885] 	 49.06% 진행
[1907 / 3885] 	 49.09% 진행
[1908 / 3885] 	 49.11% 진행
[1909 / 3885] 	 49.14% 진행
[1910 / 3885] 	 49.16% 진행
[1911 / 3885] 	 49.19% 진행
[1912 / 3885] 	 49.21% 진행
[1913 / 3885] 	 49.24% 진행
[1914 / 3885] 	 49.27% 진행
[1915 / 3885] 	 49.29% 진행
[1916 / 3885] 	 49.32% 진행
[1917 / 3885] 	 49.34% 진행
[1918 / 3885] 	 49.37% 진행
[1919 / 3885] 	 49.40% 진행
[1920 / 3885] 	 49.42% 진행
[1921 / 3885] 	 49.45% 진행
[1922 / 3885] 	 49.47% 진행
[1923 / 3885] 	 49.50% 진행
[1924 / 3885] 	 49.52% 진행
[1925 / 3885] 	 49.55% 진행
[1926 / 3885] 	 49.58% 진행
[1927 / 3885] 	 49.60% 진행
[1928 / 3885] 	 49.63% 진행
[1929 / 3885] 	 49.65% 진행
[1930 / 3885] 	 49.68% 진행
[1931 / 3885] 	 49.70% 진행
[1932 / 3885] 	 49.73% 진행
[1933 / 3885] 	 49.76% 진행
[1934 / 3885] 	 49.78% 진행
[1935 / 3885] 	 49.81% 진행
[1936 / 3885] 	 49.83% 진행
[1937 / 3885] 	 49.86% 진행
[1938 / 3885] 	 49.88% 진행
[1939 / 3885] 	 49.91% 진행
[1940 / 3885] 	 49.94% 진행
[1941 / 3885] 	 49.96% 진행
[1942 / 3885] 	 49.99% 진행
[1943 / 3885] 	 50.01% 진행
[1944 / 3885] 	 50.04% 진행
[1945 / 3885] 	 50.06% 진행
[1946 / 3885] 	 50.09% 진행
[1947 / 3885] 	 50.12% 진행
[1948 / 3885] 	 50.14% 진행
[1949 / 3885] 	 50.17% 진행
[1950 / 3885] 	 50.19% 진행
[1951 / 3885] 	 50.22% 진행
[1952 / 3885] 	 50.24% 진행
[1953 / 3885] 	 50.27% 진행
[1954 / 3885] 	 50.30% 진행
[1955 / 3885] 	 50.32% 진행
[1956 / 3885] 	 50.35% 진행
[1957 / 3885] 	 50.37% 진행
[1958 / 3885] 	 50.40% 진행
[1959 / 3885] 	 50.42% 진행
[1960 / 3885] 	 50.45% 진행
[1961 / 3885] 	 50.48% 진행
[1962 / 3885] 	 50.50% 진행
[1963 / 3885] 	 50.53% 진행
[1964 / 3885] 	 50.55% 진행
[1965 / 3885] 	 50.58% 진행
[1966 / 3885] 	 50.60% 진행
[1967 / 3885] 	 50.63% 진행
[1968 / 3885] 	 50.66% 진행
[1969 / 3885] 	 50.68% 진행
[1970 / 3885] 	 50.71% 진행
[1971 / 3885] 	 50.73% 진행
[1972 / 3885] 	 50.76% 진행
[1973 / 3885] 	 50.79% 진행
[1974 / 3885] 	 50.81% 진행
[1975 / 3885] 	 50.84% 진행
[1976 / 3885] 	 50.86% 진행
[1977 / 3885] 	 50.89% 진행
[1978 / 3885] 	 50.91% 진행
[1979 / 3885] 	 50.94% 진행
[1980 / 3885] 	 50.97% 진행
[1981 / 3885] 	 50.99% 진행
[1982 / 3885] 	 51.02% 진행
[1983 / 3885] 	 51.04% 진행
[1984 / 3885] 	 51.07% 진행
[1985 / 3885] 	 51.09% 진행
[1986 / 3885] 	 51.12% 진행
[1987 / 3885] 	 51.15% 진행
[1988 / 3885] 	 51.17% 진행
[1989 / 3885] 	 51.20% 진행
[1990 / 3885] 	 51.22% 진행
[1991 / 3885] 	 51.25% 진행
[1992 / 3885] 	 51.27% 진행
[1993 / 3885] 	 51.30% 진행
[1994 / 3885] 	 51.33% 진행
[1995 / 3885] 	 51.35% 진행
[1996 / 3885] 	 51.38% 진행
[1997 / 3885] 	 51.40% 진행
[1998 / 3885] 	 51.43% 진행
[1999 / 3885] 	 51.45% 진행
[2000 / 3885] 	 51.48% 진행
2000
[776, 777, 778, 779, 780, 781, 782, 783, 784]

In [ ]:
# 추출한 링크에 직접 방문하여 크롤링 진행 - 교수님 제공 코드 이용

# 크롤링 속도를 행상시키기 위해 time.sleep대신 WebDriverWait으로 변경 (다만 네트워크 불량 시 오래 걸릴 수 있음)
# WebDriverWait 이용 시 탐색 속도가 너무 빨라 봇 탐지 가능성 존재 -> time.sleep 이용 요망

# 진행상황 확인코드 추가

# 방문해야 하는 기사수가 3885로 매우 방대 하기 때문에 500개씩 끊어서 진행 (셀 단위)

i = 2000

for link in news_links[i:2500]:
    try:
        all_results[i] = dict()

        # 실제 네이버 뉴스 웹페이지로 이동
        driver.get(link)

        # 페이지 로딩 대기
        time.sleep(0.6) 

        # 제목 추출하기
        title = driver.find_elements(By.XPATH, '/html/body/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/p')
        title = title[0].text 

        # 본문 추출하기
        body = driver.find_elements(By.CLASS_NAME, 'article_content')
        body = body[0].text.replace('\n', '') 

        # 날짜 추출하기
        pubdate_element = driver.find_elements(By.XPATH, '/html/body/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[2]')
        pubdate = pubdate_element[0].text
        pubdate = pubdate[5:24]

        all_results[i]['link'] = link
        all_results[i]['pubdate'] = pubdate
        all_results[i]['title'] = title
        all_results[i]['body'] = body

        # 진행 상황 확인용 코드
        print(f"[{i+1} / {len(news_links)}] \t {(i+1)/len(news_links)*100:.2f}% 진행")    
        i += 1

        # 봇 탐지 방지를 위해 0.8초에서 1.5초 사이에 랜덤한 시간을 기다림
        time.sleep(random.uniform(0.8, 1.5))

    # 오류 발생 시
    except:
        print('오류가 발생했습니다.')
        err_idx.append(i)

        print(f"[{i+1} / {len(news_links)}] \t {(i+1)/len(news_links)*100:.2f}% 진행 - 오류 발생")    
        i += 1

        # 봇 탐지 방지를 위해 0.8초에서 1.5초 사이에 랜덤한 시간을 기다림
        time.sleep(random.uniform(0.8, 1.5))

print(len(all_results))
print(err_idx)

[2001 / 3885] 	 51.51% 진행
[2002 / 3885] 	 51.53% 진행
[2003 / 3885] 	 51.56% 진행
[2004 / 3885] 	 51.58% 진행
[2005 / 3885] 	 51.61% 진행
[2006 / 3885] 	 51.63% 진행
[2007 / 3885] 	 51.66% 진행
[2008 / 3885] 	 51.69% 진행
[2009 / 3885] 	 51.71% 진행
[2010 / 3885] 	 51.74% 진행
[2011 / 3885] 	 51.76% 진행
[2012 / 3885] 	 51.79% 진행
[2013 / 3885] 	 51.81% 진행
[2014 / 3885] 	 51.84% 진행
[2015 / 3885] 	 51.87% 진행
[2016 / 3885] 	 51.89% 진행
[2017 / 3885] 	 51.92% 진행
[2018 / 3885] 	 51.94% 진행
[2019 / 3885] 	 51.97% 진행
[2020 / 3885] 	 51.99% 진행
[2021 / 3885] 	 52.02% 진행
[2022 / 3885] 	 52.05% 진행
[2023 / 3885] 	 52.07% 진행
[2024 / 3885] 	 52.10% 진행
[2025 / 3885] 	 52.12% 진행
[2026 / 3885] 	 52.15% 진행
[2027 / 3885] 	 52.18% 진행
[2028 / 3885] 	 52.20% 진행
[2029 / 3885] 	 52.23% 진행
[2030 / 3885] 	 52.25% 진행
[2031 / 3885] 	 52.28% 진행
[2032 / 3885] 	 52.30% 진행
[2033 / 3885] 	 52.33% 진행
[2034 / 3885] 	 52.36% 진행
[2035 / 3885] 	 52.38% 진행
[2036 / 3885] 	 52.41% 진행
[2037 / 3885] 	 52.43% 진행
[2038 / 3885] 	 52.46% 진행
[2039 / 3885] 	 52.48% 진행
[2040 / 3885] 	 52.51% 진행
[2041 / 3885] 	 52.54% 진행
[2042 / 3885] 	 52.56% 진행
[2043 / 3885] 	 52.59% 진행
[2044 / 3885] 	 52.61% 진행
[2045 / 3885] 	 52.64% 진행
[2046 / 3885] 	 52.66% 진행
[2047 / 3885] 	 52.69% 진행
[2048 / 3885] 	 52.72% 진행
[2049 / 3885] 	 52.74% 진행
[2050 / 3885] 	 52.77% 진행
[2051 / 3885] 	 52.79% 진행
[2052 / 3885] 	 52.82% 진행
[2053 / 3885] 	 52.84% 진행
[2054 / 3885] 	 52.87% 진행
[2055 / 3885] 	 52.90% 진행
[2056 / 3885] 	 52.92% 진행
[2057 / 3885] 	 52.95% 진행
[2058 / 3885] 	 52.97% 진행
[2059 / 3885] 	 53.00% 진행
[2060 / 3885] 	 53.02% 진행
[2061 / 3885] 	 53.05% 진행
[2062 / 3885] 	 53.08% 진행
[2063 / 3885] 	 53.10% 진행
[2064 / 3885] 	 53.13% 진행
[2065 / 3885] 	 53.15% 진행
[2066 / 3885] 	 53.18% 진행
[2067 / 3885] 	 53.20% 진행
[2068 / 3885] 	 53.23% 진행
[2069 / 3885] 	 53.26% 진행
[2070 / 3885] 	 53.28% 진행
[2071 / 3885] 	 53.31% 진행
[2072 / 3885] 	 53.33% 진행
[2073 / 3885] 	 53.36% 진행
[2074 / 3885] 	 53.38% 진행
[2075 / 3885] 	 53.41% 진행
[2076 / 3885] 	 53.44% 진행
[2077 / 3885] 	 53.46% 진행
[2078 / 3885] 	 53.49% 진행
[2079 / 3885] 	 53.51% 진행
[2080 / 3885] 	 53.54% 진행
[2081 / 3885] 	 53.56% 진행
[2082 / 3885] 	 53.59% 진행
[2083 / 3885] 	 53.62% 진행
[2084 / 3885] 	 53.64% 진행
[2085 / 3885] 	 53.67% 진행
[2086 / 3885] 	 53.69% 진행
[2087 / 3885] 	 53.72% 진행
[2088 / 3885] 	 53.75% 진행
[2089 / 3885] 	 53.77% 진행
[2090 / 3885] 	 53.80% 진행
[2091 / 3885] 	 53.82% 진행
[2092 / 3885] 	 53.85% 진행
[2093 / 3885] 	 53.87% 진행
[2094 / 3885] 	 53.90% 진행
[2095 / 3885] 	 53.93% 진행
[2096 / 3885] 	 53.95% 진행
[2097 / 3885] 	 53.98% 진행
[2098 / 3885] 	 54.00% 진행
[2099 / 3885] 	 54.03% 진행
[2100 / 3885] 	 54.05% 진행
[2101 / 3885] 	 54.08% 진행
[2102 / 3885] 	 54.11% 진행
[2103 / 3885] 	 54.13% 진행
[2104 / 3885] 	 54.16% 진행
[2105 / 3885] 	 54.18% 진행
[2106 / 3885] 	 54.21% 진행
[2107 / 3885] 	 54.23% 진행
[2108 / 3885] 	 54.26% 진행
[2109 / 3885] 	 54.29% 진행
[2110 / 3885] 	 54.31% 진행
[2111 / 3885] 	 54.34% 진행
[2112 / 3885] 	 54.36% 진행
[2113 / 3885] 	 54.39% 진행
[2114 / 3885] 	 54.41% 진행
[2115 / 3885] 	 54.44% 진행
[2116 / 3885] 	 54.47% 진행
[2117 / 3885] 	 54.49% 진행
[2118 / 3885] 	 54.52% 진행
[2119 / 3885] 	 54.54% 진행
[2120 / 3885] 	 54.57% 진행
[2121 / 3885] 	 54.59% 진행
[2122 / 3885] 	 54.62% 진행
[2123 / 3885] 	 54.65% 진행
[2124 / 3885] 	 54.67% 진행
[2125 / 3885] 	 54.70% 진행
[2126 / 3885] 	 54.72% 진행
[2127 / 3885] 	 54.75% 진행
[2128 / 3885] 	 54.77% 진행
[2129 / 3885] 	 54.80% 진행
[2130 / 3885] 	 54.83% 진행
[2131 / 3885] 	 54.85% 진행
[2132 / 3885] 	 54.88% 진행
[2133 / 3885] 	 54.90% 진행
[2134 / 3885] 	 54.93% 진행
[2135 / 3885] 	 54.95% 진행
[2136 / 3885] 	 54.98% 진행
[2137 / 3885] 	 55.01% 진행
[2138 / 3885] 	 55.03% 진행
[2139 / 3885] 	 55.06% 진행
[2140 / 3885] 	 55.08% 진행
[2141 / 3885] 	 55.11% 진행
[2142 / 3885] 	 55.14% 진행
[2143 / 3885] 	 55.16% 진행
[2144 / 3885] 	 55.19% 진행
[2145 / 3885] 	 55.21% 진행
[2146 / 3885] 	 55.24% 진행
[2147 / 3885] 	 55.26% 진행
[2148 / 3885] 	 55.29% 진행
[2149 / 3885] 	 55.32% 진행
[2150 / 3885] 	 55.34% 진행
[2151 / 3885] 	 55.37% 진행
[2152 / 3885] 	 55.39% 진행
[2153 / 3885] 	 55.42% 진행
[2154 / 3885] 	 55.44% 진행
[2155 / 3885] 	 55.47% 진행
[2156 / 3885] 	 55.50% 진행
[2157 / 3885] 	 55.52% 진행
[2158 / 3885] 	 55.55% 진행
[2159 / 3885] 	 55.57% 진행
[2160 / 3885] 	 55.60% 진행
[2161 / 3885] 	 55.62% 진행
[2162 / 3885] 	 55.65% 진행
[2163 / 3885] 	 55.68% 진행
[2164 / 3885] 	 55.70% 진행
[2165 / 3885] 	 55.73% 진행
[2166 / 3885] 	 55.75% 진행
[2167 / 3885] 	 55.78% 진행
[2168 / 3885] 	 55.80% 진행
[2169 / 3885] 	 55.83% 진행
[2170 / 3885] 	 55.86% 진행
[2171 / 3885] 	 55.88% 진행
[2172 / 3885] 	 55.91% 진행
[2173 / 3885] 	 55.93% 진행
[2174 / 3885] 	 55.96% 진행
[2175 / 3885] 	 55.98% 진행
[2176 / 3885] 	 56.01% 진행
[2177 / 3885] 	 56.04% 진행
[2178 / 3885] 	 56.06% 진행
[2179 / 3885] 	 56.09% 진행
[2180 / 3885] 	 56.11% 진행
[2181 / 3885] 	 56.14% 진행
[2182 / 3885] 	 56.16% 진행
[2183 / 3885] 	 56.19% 진행
[2184 / 3885] 	 56.22% 진행
[2185 / 3885] 	 56.24% 진행
[2186 / 3885] 	 56.27% 진행
[2187 / 3885] 	 56.29% 진행
[2188 / 3885] 	 56.32% 진행
[2189 / 3885] 	 56.34% 진행
[2190 / 3885] 	 56.37% 진행
[2191 / 3885] 	 56.40% 진행
[2192 / 3885] 	 56.42% 진행
[2193 / 3885] 	 56.45% 진행
[2194 / 3885] 	 56.47% 진행
[2195 / 3885] 	 56.50% 진행
[2196 / 3885] 	 56.53% 진행
[2197 / 3885] 	 56.55% 진행
[2198 / 3885] 	 56.58% 진행
[2199 / 3885] 	 56.60% 진행
[2200 / 3885] 	 56.63% 진행
[2201 / 3885] 	 56.65% 진행
[2202 / 3885] 	 56.68% 진행
[2203 / 3885] 	 56.71% 진행
[2204 / 3885] 	 56.73% 진행
[2205 / 3885] 	 56.76% 진행
[2206 / 3885] 	 56.78% 진행
[2207 / 3885] 	 56.81% 진행
[2208 / 3885] 	 56.83% 진행
[2209 / 3885] 	 56.86% 진행
[2210 / 3885] 	 56.89% 진행
[2211 / 3885] 	 56.91% 진행
[2212 / 3885] 	 56.94% 진행
[2213 / 3885] 	 56.96% 진행
[2214 / 3885] 	 56.99% 진행
[2215 / 3885] 	 57.01% 진행
[2216 / 3885] 	 57.04% 진행
[2217 / 3885] 	 57.07% 진행
[2218 / 3885] 	 57.09% 진행
[2219 / 3885] 	 57.12% 진행
[2220 / 3885] 	 57.14% 진행
[2221 / 3885] 	 57.17% 진행
[2222 / 3885] 	 57.19% 진행
[2223 / 3885] 	 57.22% 진행
[2224 / 3885] 	 57.25% 진행
[2225 / 3885] 	 57.27% 진행
[2226 / 3885] 	 57.30% 진행
[2227 / 3885] 	 57.32% 진행
[2228 / 3885] 	 57.35% 진행
[2229 / 3885] 	 57.37% 진행
[2230 / 3885] 	 57.40% 진행
[2231 / 3885] 	 57.43% 진행
[2232 / 3885] 	 57.45% 진행
[2233 / 3885] 	 57.48% 진행
[2234 / 3885] 	 57.50% 진행
[2235 / 3885] 	 57.53% 진행
[2236 / 3885] 	 57.55% 진행
[2237 / 3885] 	 57.58% 진행
[2238 / 3885] 	 57.61% 진행
[2239 / 3885] 	 57.63% 진행
[2240 / 3885] 	 57.66% 진행
[2241 / 3885] 	 57.68% 진행
[2242 / 3885] 	 57.71% 진행
[2243 / 3885] 	 57.73% 진행
[2244 / 3885] 	 57.76% 진행
[2245 / 3885] 	 57.79% 진행
[2246 / 3885] 	 57.81% 진행
[2247 / 3885] 	 57.84% 진행
[2248 / 3885] 	 57.86% 진행
[2249 / 3885] 	 57.89% 진행
[2250 / 3885] 	 57.92% 진행
[2251 / 3885] 	 57.94% 진행
[2252 / 3885] 	 57.97% 진행
[2253 / 3885] 	 57.99% 진행
[2254 / 3885] 	 58.02% 진행
[2255 / 3885] 	 58.04% 진행
[2256 / 3885] 	 58.07% 진행
[2257 / 3885] 	 58.10% 진행
[2258 / 3885] 	 58.12% 진행
[2259 / 3885] 	 58.15% 진행
[2260 / 3885] 	 58.17% 진행
[2261 / 3885] 	 58.20% 진행
[2262 / 3885] 	 58.22% 진행
[2263 / 3885] 	 58.25% 진행
[2264 / 3885] 	 58.28% 진행
[2265 / 3885] 	 58.30% 진행
[2266 / 3885] 	 58.33% 진행
[2267 / 3885] 	 58.35% 진행
[2268 / 3885] 	 58.38% 진행
[2269 / 3885] 	 58.40% 진행
[2270 / 3885] 	 58.43% 진행
[2271 / 3885] 	 58.46% 진행
[2272 / 3885] 	 58.48% 진행
[2273 / 3885] 	 58.51% 진행
[2274 / 3885] 	 58.53% 진행
[2275 / 3885] 	 58.56% 진행
[2276 / 3885] 	 58.58% 진행
[2277 / 3885] 	 58.61% 진행
[2278 / 3885] 	 58.64% 진행
[2279 / 3885] 	 58.66% 진행
[2280 / 3885] 	 58.69% 진행
[2281 / 3885] 	 58.71% 진행
[2282 / 3885] 	 58.74% 진행
[2283 / 3885] 	 58.76% 진행
[2284 / 3885] 	 58.79% 진행
[2285 / 3885] 	 58.82% 진행
[2286 / 3885] 	 58.84% 진행
[2287 / 3885] 	 58.87% 진행
[2288 / 3885] 	 58.89% 진행
[2289 / 3885] 	 58.92% 진행
[2290 / 3885] 	 58.94% 진행
[2291 / 3885] 	 58.97% 진행
[2292 / 3885] 	 59.00% 진행
[2293 / 3885] 	 59.02% 진행
[2294 / 3885] 	 59.05% 진행
[2295 / 3885] 	 59.07% 진행
[2296 / 3885] 	 59.10% 진행
[2297 / 3885] 	 59.12% 진행
[2298 / 3885] 	 59.15% 진행
[2299 / 3885] 	 59.18% 진행
[2300 / 3885] 	 59.20% 진행
[2301 / 3885] 	 59.23% 진행
[2302 / 3885] 	 59.25% 진행
[2303 / 3885] 	 59.28% 진행
[2304 / 3885] 	 59.31% 진행
[2305 / 3885] 	 59.33% 진행
[2306 / 3885] 	 59.36% 진행
[2307 / 3885] 	 59.38% 진행
[2308 / 3885] 	 59.41% 진행
[2309 / 3885] 	 59.43% 진행
[2310 / 3885] 	 59.46% 진행
[2311 / 3885] 	 59.49% 진행
[2312 / 3885] 	 59.51% 진행
[2313 / 3885] 	 59.54% 진행
[2314 / 3885] 	 59.56% 진행
[2315 / 3885] 	 59.59% 진행
[2316 / 3885] 	 59.61% 진행
[2317 / 3885] 	 59.64% 진행
[2318 / 3885] 	 59.67% 진행
[2319 / 3885] 	 59.69% 진행
[2320 / 3885] 	 59.72% 진행
[2321 / 3885] 	 59.74% 진행
[2322 / 3885] 	 59.77% 진행
[2323 / 3885] 	 59.79% 진행
[2324 / 3885] 	 59.82% 진행
[2325 / 3885] 	 59.85% 진행
[2326 / 3885] 	 59.87% 진행
[2327 / 3885] 	 59.90% 진행
[2328 / 3885] 	 59.92% 진행
[2329 / 3885] 	 59.95% 진행
[2330 / 3885] 	 59.97% 진행
[2331 / 3885] 	 60.00% 진행
[2332 / 3885] 	 60.03% 진행
[2333 / 3885] 	 60.05% 진행
[2334 / 3885] 	 60.08% 진행
[2335 / 3885] 	 60.10% 진행
[2336 / 3885] 	 60.13% 진행
[2337 / 3885] 	 60.15% 진행
[2338 / 3885] 	 60.18% 진행
[2339 / 3885] 	 60.21% 진행
[2340 / 3885] 	 60.23% 진행
[2341 / 3885] 	 60.26% 진행
[2342 / 3885] 	 60.28% 진행
[2343 / 3885] 	 60.31% 진행
[2344 / 3885] 	 60.33% 진행
[2345 / 3885] 	 60.36% 진행
[2346 / 3885] 	 60.39% 진행
[2347 / 3885] 	 60.41% 진행
[2348 / 3885] 	 60.44% 진행
[2349 / 3885] 	 60.46% 진행
[2350 / 3885] 	 60.49% 진행
[2351 / 3885] 	 60.51% 진행
[2352 / 3885] 	 60.54% 진행
[2353 / 3885] 	 60.57% 진행
[2354 / 3885] 	 60.59% 진행
[2355 / 3885] 	 60.62% 진행
[2356 / 3885] 	 60.64% 진행
[2357 / 3885] 	 60.67% 진행
[2358 / 3885] 	 60.69% 진행
[2359 / 3885] 	 60.72% 진행
[2360 / 3885] 	 60.75% 진행
[2361 / 3885] 	 60.77% 진행
[2362 / 3885] 	 60.80% 진행
[2363 / 3885] 	 60.82% 진행
[2364 / 3885] 	 60.85% 진행
[2365 / 3885] 	 60.88% 진행
[2366 / 3885] 	 60.90% 진행
[2367 / 3885] 	 60.93% 진행
[2368 / 3885] 	 60.95% 진행
[2369 / 3885] 	 60.98% 진행
[2370 / 3885] 	 61.00% 진행
[2371 / 3885] 	 61.03% 진행
[2372 / 3885] 	 61.06% 진행
[2373 / 3885] 	 61.08% 진행
[2374 / 3885] 	 61.11% 진행
[2375 / 3885] 	 61.13% 진행
[2376 / 3885] 	 61.16% 진행
[2377 / 3885] 	 61.18% 진행
[2378 / 3885] 	 61.21% 진행
[2379 / 3885] 	 61.24% 진행
[2380 / 3885] 	 61.26% 진행
[2381 / 3885] 	 61.29% 진행
[2382 / 3885] 	 61.31% 진행
[2383 / 3885] 	 61.34% 진행
[2384 / 3885] 	 61.36% 진행
[2385 / 3885] 	 61.39% 진행
[2386 / 3885] 	 61.42% 진행
[2387 / 3885] 	 61.44% 진행
[2388 / 3885] 	 61.47% 진행
[2389 / 3885] 	 61.49% 진행
[2390 / 3885] 	 61.52% 진행
[2391 / 3885] 	 61.54% 진행
[2392 / 3885] 	 61.57% 진행
[2393 / 3885] 	 61.60% 진행
[2394 / 3885] 	 61.62% 진행
[2395 / 3885] 	 61.65% 진행
[2396 / 3885] 	 61.67% 진행
[2397 / 3885] 	 61.70% 진행
[2398 / 3885] 	 61.72% 진행
[2399 / 3885] 	 61.75% 진행
[2400 / 3885] 	 61.78% 진행
[2401 / 3885] 	 61.80% 진행
[2402 / 3885] 	 61.83% 진행
[2403 / 3885] 	 61.85% 진행
[2404 / 3885] 	 61.88% 진행
[2405 / 3885] 	 61.90% 진행
[2406 / 3885] 	 61.93% 진행
[2407 / 3885] 	 61.96% 진행
[2408 / 3885] 	 61.98% 진행
[2409 / 3885] 	 62.01% 진행
[2410 / 3885] 	 62.03% 진행
[2411 / 3885] 	 62.06% 진행
[2412 / 3885] 	 62.08% 진행
[2413 / 3885] 	 62.11% 진행
[2414 / 3885] 	 62.14% 진행
[2415 / 3885] 	 62.16% 진행
[2416 / 3885] 	 62.19% 진행
[2417 / 3885] 	 62.21% 진행
[2418 / 3885] 	 62.24% 진행
[2419 / 3885] 	 62.27% 진행
[2420 / 3885] 	 62.29% 진행
[2421 / 3885] 	 62.32% 진행
[2422 / 3885] 	 62.34% 진행
[2423 / 3885] 	 62.37% 진행
[2424 / 3885] 	 62.39% 진행
[2425 / 3885] 	 62.42% 진행
[2426 / 3885] 	 62.45% 진행
[2427 / 3885] 	 62.47% 진행
[2428 / 3885] 	 62.50% 진행
[2429 / 3885] 	 62.52% 진행
[2430 / 3885] 	 62.55% 진행
[2431 / 3885] 	 62.57% 진행
[2432 / 3885] 	 62.60% 진행
[2433 / 3885] 	 62.63% 진행
[2434 / 3885] 	 62.65% 진행
[2435 / 3885] 	 62.68% 진행
[2436 / 3885] 	 62.70% 진행
[2437 / 3885] 	 62.73% 진행
[2438 / 3885] 	 62.75% 진행
[2439 / 3885] 	 62.78% 진행
[2440 / 3885] 	 62.81% 진행
[2441 / 3885] 	 62.83% 진행
[2442 / 3885] 	 62.86% 진행
[2443 / 3885] 	 62.88% 진행
[2444 / 3885] 	 62.91% 진행
[2445 / 3885] 	 62.93% 진행
[2446 / 3885] 	 62.96% 진행
[2447 / 3885] 	 62.99% 진행
[2448 / 3885] 	 63.01% 진행
[2449 / 3885] 	 63.04% 진행
[2450 / 3885] 	 63.06% 진행
[2451 / 3885] 	 63.09% 진행
[2452 / 3885] 	 63.11% 진행
[2453 / 3885] 	 63.14% 진행
[2454 / 3885] 	 63.17% 진행
[2455 / 3885] 	 63.19% 진행
[2456 / 3885] 	 63.22% 진행
[2457 / 3885] 	 63.24% 진행
[2458 / 3885] 	 63.27% 진행
[2459 / 3885] 	 63.29% 진행
[2460 / 3885] 	 63.32% 진행
[2461 / 3885] 	 63.35% 진행
[2462 / 3885] 	 63.37% 진행
[2463 / 3885] 	 63.40% 진행
[2464 / 3885] 	 63.42% 진행
[2465 / 3885] 	 63.45% 진행
[2466 / 3885] 	 63.47% 진행
[2467 / 3885] 	 63.50% 진행
[2468 / 3885] 	 63.53% 진행
[2469 / 3885] 	 63.55% 진행
[2470 / 3885] 	 63.58% 진행
[2471 / 3885] 	 63.60% 진행
[2472 / 3885] 	 63.63% 진행
[2473 / 3885] 	 63.66% 진행
[2474 / 3885] 	 63.68% 진행
[2475 / 3885] 	 63.71% 진행
[2476 / 3885] 	 63.73% 진행
[2477 / 3885] 	 63.76% 진행
[2478 / 3885] 	 63.78% 진행
[2479 / 3885] 	 63.81% 진행
[2480 / 3885] 	 63.84% 진행
[2481 / 3885] 	 63.86% 진행
[2482 / 3885] 	 63.89% 진행
[2483 / 3885] 	 63.91% 진행
[2484 / 3885] 	 63.94% 진행
[2485 / 3885] 	 63.96% 진행
[2486 / 3885] 	 63.99% 진행
[2487 / 3885] 	 64.02% 진행
[2488 / 3885] 	 64.04% 진행
[2489 / 3885] 	 64.07% 진행
[2490 / 3885] 	 64.09% 진행
[2491 / 3885] 	 64.12% 진행
[2492 / 3885] 	 64.14% 진행
[2493 / 3885] 	 64.17% 진행
[2494 / 3885] 	 64.20% 진행
[2495 / 3885] 	 64.22% 진행
[2496 / 3885] 	 64.25% 진행
[2497 / 3885] 	 64.27% 진행
[2498 / 3885] 	 64.30% 진행
[2499 / 3885] 	 64.32% 진행
[2500 / 3885] 	 64.35% 진행
2500
[776, 777, 778, 779, 780, 781, 782, 783, 784]

In [ ]:
# 추출한 링크에 직접 방문하여 크롤링 진행 - 교수님 제공 코드 이용

# 크롤링 속도를 행상시키기 위해 time.sleep대신 WebDriverWait으로 변경 (다만 네트워크 불량 시 오래 걸릴 수 있음)
# WebDriverWait 이용 시 탐색 속도가 너무 빨라 봇 탐지 가능성 존재 -> time.sleep 이용 요망

# 진행상황 확인코드 추가

# 방문해야 하는 기사수가 3885로 매우 방대 하기 때문에 500개씩 끊어서 진행 (셀 단위)

i = 2500

for link in news_links[i:3000]:
    try:
        all_results[i] = dict()

        # 실제 네이버 뉴스 웹페이지로 이동
        driver.get(link)

        # 페이지 로딩 대기
        time.sleep(0.6) 

        # 제목 추출하기
        title = driver.find_elements(By.XPATH, '/html/body/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/p')
        title = title[0].text 

        # 본문 추출하기
        body = driver.find_elements(By.CLASS_NAME, 'article_content')
        body = body[0].text.replace('\n', '') 

        # 날짜 추출하기
        pubdate_element = driver.find_elements(By.XPATH, '/html/body/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[2]')
        pubdate = pubdate_element[0].text
        pubdate = pubdate[5:24]

        all_results[i]['link'] = link
        all_results[i]['pubdate'] = pubdate
        all_results[i]['title'] = title
        all_results[i]['body'] = body

        # 진행 상황 확인용 코드
        print(f"[{i+1} / {len(news_links)}] \t {(i+1)/len(news_links)*100:.2f}% 진행")    
        i += 1

        # 봇 탐지 방지를 위해 0.8초에서 1.5초 사이에 랜덤한 시간을 기다림
        time.sleep(random.uniform(0.8, 1.5))

    # 오류 발생 시
    except:
        print('오류가 발생했습니다.')
        err_idx.append(i)

        print(f"[{i+1} / {len(news_links)}] \t {(i+1)/len(news_links)*100:.2f}% 진행 - 오류 발생")    
        i += 1

        # 봇 탐지 방지를 위해 0.8초에서 1.5초 사이에 랜덤한 시간을 기다림
        time.sleep(random.uniform(0.8, 1.5))

print(len(all_results))
print(err_idx)

[2501 / 3885] 	 64.38% 진행
[2502 / 3885] 	 64.40% 진행
[2503 / 3885] 	 64.43% 진행
[2504 / 3885] 	 64.45% 진행
[2505 / 3885] 	 64.48% 진행
[2506 / 3885] 	 64.50% 진행
[2507 / 3885] 	 64.53% 진행
[2508 / 3885] 	 64.56% 진행
[2509 / 3885] 	 64.58% 진행
[2510 / 3885] 	 64.61% 진행
[2511 / 3885] 	 64.63% 진행
[2512 / 3885] 	 64.66% 진행
[2513 / 3885] 	 64.68% 진행
[2514 / 3885] 	 64.71% 진행
[2515 / 3885] 	 64.74% 진행
[2516 / 3885] 	 64.76% 진행
[2517 / 3885] 	 64.79% 진행
[2518 / 3885] 	 64.81% 진행
[2519 / 3885] 	 64.84% 진행
[2520 / 3885] 	 64.86% 진행
[2521 / 3885] 	 64.89% 진행
[2522 / 3885] 	 64.92% 진행
[2523 / 3885] 	 64.94% 진행
[2524 / 3885] 	 64.97% 진행
[2525 / 3885] 	 64.99% 진행
[2526 / 3885] 	 65.02% 진행
[2527 / 3885] 	 65.05% 진행
[2528 / 3885] 	 65.07% 진행
[2529 / 3885] 	 65.10% 진행
[2530 / 3885] 	 65.12% 진행
[2531 / 3885] 	 65.15% 진행
[2532 / 3885] 	 65.17% 진행
[2533 / 3885] 	 65.20% 진행
[2534 / 3885] 	 65.23% 진행
[2535 / 3885] 	 65.25% 진행
[2536 / 3885] 	 65.28% 진행
[2537 / 3885] 	 65.30% 진행
[2538 / 3885] 	 65.33% 진행
[2539 / 3885] 	 65.35% 진행
[2540 / 3885] 	 65.38% 진행
[2541 / 3885] 	 65.41% 진행
[2542 / 3885] 	 65.43% 진행
[2543 / 3885] 	 65.46% 진행
[2544 / 3885] 	 65.48% 진행
[2545 / 3885] 	 65.51% 진행
[2546 / 3885] 	 65.53% 진행
[2547 / 3885] 	 65.56% 진행
[2548 / 3885] 	 65.59% 진행
[2549 / 3885] 	 65.61% 진행
[2550 / 3885] 	 65.64% 진행
[2551 / 3885] 	 65.66% 진행
[2552 / 3885] 	 65.69% 진행
[2553 / 3885] 	 65.71% 진행
[2554 / 3885] 	 65.74% 진행
[2555 / 3885] 	 65.77% 진행
[2556 / 3885] 	 65.79% 진행
[2557 / 3885] 	 65.82% 진행
[2558 / 3885] 	 65.84% 진행
[2559 / 3885] 	 65.87% 진행
[2560 / 3885] 	 65.89% 진행
[2561 / 3885] 	 65.92% 진행
[2562 / 3885] 	 65.95% 진행
[2563 / 3885] 	 65.97% 진행
[2564 / 3885] 	 66.00% 진행
[2565 / 3885] 	 66.02% 진행
[2566 / 3885] 	 66.05% 진행
[2567 / 3885] 	 66.07% 진행
[2568 / 3885] 	 66.10% 진행
[2569 / 3885] 	 66.13% 진행
[2570 / 3885] 	 66.15% 진행
[2571 / 3885] 	 66.18% 진행
[2572 / 3885] 	 66.20% 진행
[2573 / 3885] 	 66.23% 진행
[2574 / 3885] 	 66.25% 진행
[2575 / 3885] 	 66.28% 진행
[2576 / 3885] 	 66.31% 진행
[2577 / 3885] 	 66.33% 진행
[2578 / 3885] 	 66.36% 진행
[2579 / 3885] 	 66.38% 진행
[2580 / 3885] 	 66.41% 진행
[2581 / 3885] 	 66.44% 진행
[2582 / 3885] 	 66.46% 진행
[2583 / 3885] 	 66.49% 진행
[2584 / 3885] 	 66.51% 진행
[2585 / 3885] 	 66.54% 진행
[2586 / 3885] 	 66.56% 진행
[2587 / 3885] 	 66.59% 진행
[2588 / 3885] 	 66.62% 진행
[2589 / 3885] 	 66.64% 진행
[2590 / 3885] 	 66.67% 진행
[2591 / 3885] 	 66.69% 진행
[2592 / 3885] 	 66.72% 진행
[2593 / 3885] 	 66.74% 진행
[2594 / 3885] 	 66.77% 진행
[2595 / 3885] 	 66.80% 진행
[2596 / 3885] 	 66.82% 진행
[2597 / 3885] 	 66.85% 진행
[2598 / 3885] 	 66.87% 진행
[2599 / 3885] 	 66.90% 진행
[2600 / 3885] 	 66.92% 진행
[2601 / 3885] 	 66.95% 진행
[2602 / 3885] 	 66.98% 진행
[2603 / 3885] 	 67.00% 진행
[2604 / 3885] 	 67.03% 진행
[2605 / 3885] 	 67.05% 진행
[2606 / 3885] 	 67.08% 진행
[2607 / 3885] 	 67.10% 진행
[2608 / 3885] 	 67.13% 진행
[2609 / 3885] 	 67.16% 진행
[2610 / 3885] 	 67.18% 진행
[2611 / 3885] 	 67.21% 진행
[2612 / 3885] 	 67.23% 진행
[2613 / 3885] 	 67.26% 진행
[2614 / 3885] 	 67.28% 진행
[2615 / 3885] 	 67.31% 진행
[2616 / 3885] 	 67.34% 진행
[2617 / 3885] 	 67.36% 진행
[2618 / 3885] 	 67.39% 진행
[2619 / 3885] 	 67.41% 진행
[2620 / 3885] 	 67.44% 진행
[2621 / 3885] 	 67.46% 진행
[2622 / 3885] 	 67.49% 진행
[2623 / 3885] 	 67.52% 진행
[2624 / 3885] 	 67.54% 진행
[2625 / 3885] 	 67.57% 진행
[2626 / 3885] 	 67.59% 진행
[2627 / 3885] 	 67.62% 진행
[2628 / 3885] 	 67.64% 진행
[2629 / 3885] 	 67.67% 진행
[2630 / 3885] 	 67.70% 진행
[2631 / 3885] 	 67.72% 진행
[2632 / 3885] 	 67.75% 진행
[2633 / 3885] 	 67.77% 진행
[2634 / 3885] 	 67.80% 진행
[2635 / 3885] 	 67.82% 진행
[2636 / 3885] 	 67.85% 진행
[2637 / 3885] 	 67.88% 진행
[2638 / 3885] 	 67.90% 진행
[2639 / 3885] 	 67.93% 진행
[2640 / 3885] 	 67.95% 진행
[2641 / 3885] 	 67.98% 진행
[2642 / 3885] 	 68.01% 진행
[2643 / 3885] 	 68.03% 진행
[2644 / 3885] 	 68.06% 진행
[2645 / 3885] 	 68.08% 진행
[2646 / 3885] 	 68.11% 진행
[2647 / 3885] 	 68.13% 진행
[2648 / 3885] 	 68.16% 진행
[2649 / 3885] 	 68.19% 진행
[2650 / 3885] 	 68.21% 진행
[2651 / 3885] 	 68.24% 진행
[2652 / 3885] 	 68.26% 진행
[2653 / 3885] 	 68.29% 진행
[2654 / 3885] 	 68.31% 진행
[2655 / 3885] 	 68.34% 진행
[2656 / 3885] 	 68.37% 진행
[2657 / 3885] 	 68.39% 진행
[2658 / 3885] 	 68.42% 진행
[2659 / 3885] 	 68.44% 진행
[2660 / 3885] 	 68.47% 진행
[2661 / 3885] 	 68.49% 진행
[2662 / 3885] 	 68.52% 진행
[2663 / 3885] 	 68.55% 진행
[2664 / 3885] 	 68.57% 진행
[2665 / 3885] 	 68.60% 진행
[2666 / 3885] 	 68.62% 진행
[2667 / 3885] 	 68.65% 진행
[2668 / 3885] 	 68.67% 진행
[2669 / 3885] 	 68.70% 진행
[2670 / 3885] 	 68.73% 진행
[2671 / 3885] 	 68.75% 진행
[2672 / 3885] 	 68.78% 진행
[2673 / 3885] 	 68.80% 진행
[2674 / 3885] 	 68.83% 진행
[2675 / 3885] 	 68.85% 진행
[2676 / 3885] 	 68.88% 진행
[2677 / 3885] 	 68.91% 진행
[2678 / 3885] 	 68.93% 진행
[2679 / 3885] 	 68.96% 진행
[2680 / 3885] 	 68.98% 진행
[2681 / 3885] 	 69.01% 진행
[2682 / 3885] 	 69.03% 진행
[2683 / 3885] 	 69.06% 진행
[2684 / 3885] 	 69.09% 진행
[2685 / 3885] 	 69.11% 진행
[2686 / 3885] 	 69.14% 진행
[2687 / 3885] 	 69.16% 진행
[2688 / 3885] 	 69.19% 진행
[2689 / 3885] 	 69.21% 진행
[2690 / 3885] 	 69.24% 진행
[2691 / 3885] 	 69.27% 진행
[2692 / 3885] 	 69.29% 진행
[2693 / 3885] 	 69.32% 진행
[2694 / 3885] 	 69.34% 진행
[2695 / 3885] 	 69.37% 진행
[2696 / 3885] 	 69.40% 진행
[2697 / 3885] 	 69.42% 진행
[2698 / 3885] 	 69.45% 진행
[2699 / 3885] 	 69.47% 진행
[2700 / 3885] 	 69.50% 진행
[2701 / 3885] 	 69.52% 진행
[2702 / 3885] 	 69.55% 진행
[2703 / 3885] 	 69.58% 진행
[2704 / 3885] 	 69.60% 진행
[2705 / 3885] 	 69.63% 진행
[2706 / 3885] 	 69.65% 진행
[2707 / 3885] 	 69.68% 진행
[2708 / 3885] 	 69.70% 진행
[2709 / 3885] 	 69.73% 진행
[2710 / 3885] 	 69.76% 진행
[2711 / 3885] 	 69.78% 진행
[2712 / 3885] 	 69.81% 진행
[2713 / 3885] 	 69.83% 진행
[2714 / 3885] 	 69.86% 진행
[2715 / 3885] 	 69.88% 진행
[2716 / 3885] 	 69.91% 진행
[2717 / 3885] 	 69.94% 진행
[2718 / 3885] 	 69.96% 진행
[2719 / 3885] 	 69.99% 진행
[2720 / 3885] 	 70.01% 진행
[2721 / 3885] 	 70.04% 진행
[2722 / 3885] 	 70.06% 진행
[2723 / 3885] 	 70.09% 진행
[2724 / 3885] 	 70.12% 진행
[2725 / 3885] 	 70.14% 진행
[2726 / 3885] 	 70.17% 진행
[2727 / 3885] 	 70.19% 진행
[2728 / 3885] 	 70.22% 진행
[2729 / 3885] 	 70.24% 진행
[2730 / 3885] 	 70.27% 진행
[2731 / 3885] 	 70.30% 진행
[2732 / 3885] 	 70.32% 진행
[2733 / 3885] 	 70.35% 진행
[2734 / 3885] 	 70.37% 진행
[2735 / 3885] 	 70.40% 진행
[2736 / 3885] 	 70.42% 진행
[2737 / 3885] 	 70.45% 진행
[2738 / 3885] 	 70.48% 진행
[2739 / 3885] 	 70.50% 진행
[2740 / 3885] 	 70.53% 진행
[2741 / 3885] 	 70.55% 진행
[2742 / 3885] 	 70.58% 진행
[2743 / 3885] 	 70.60% 진행
[2744 / 3885] 	 70.63% 진행
[2745 / 3885] 	 70.66% 진행
[2746 / 3885] 	 70.68% 진행
[2747 / 3885] 	 70.71% 진행
[2748 / 3885] 	 70.73% 진행
[2749 / 3885] 	 70.76% 진행
[2750 / 3885] 	 70.79% 진행
[2751 / 3885] 	 70.81% 진행
[2752 / 3885] 	 70.84% 진행
[2753 / 3885] 	 70.86% 진행
[2754 / 3885] 	 70.89% 진행
[2755 / 3885] 	 70.91% 진행
[2756 / 3885] 	 70.94% 진행
[2757 / 3885] 	 70.97% 진행
[2758 / 3885] 	 70.99% 진행
[2759 / 3885] 	 71.02% 진행
[2760 / 3885] 	 71.04% 진행
[2761 / 3885] 	 71.07% 진행
[2762 / 3885] 	 71.09% 진행
[2763 / 3885] 	 71.12% 진행
[2764 / 3885] 	 71.15% 진행
[2765 / 3885] 	 71.17% 진행
[2766 / 3885] 	 71.20% 진행
[2767 / 3885] 	 71.22% 진행
[2768 / 3885] 	 71.25% 진행
[2769 / 3885] 	 71.27% 진행
[2770 / 3885] 	 71.30% 진행
[2771 / 3885] 	 71.33% 진행
[2772 / 3885] 	 71.35% 진행
[2773 / 3885] 	 71.38% 진행
[2774 / 3885] 	 71.40% 진행
[2775 / 3885] 	 71.43% 진행
[2776 / 3885] 	 71.45% 진행
[2777 / 3885] 	 71.48% 진행
[2778 / 3885] 	 71.51% 진행
[2779 / 3885] 	 71.53% 진행
[2780 / 3885] 	 71.56% 진행
[2781 / 3885] 	 71.58% 진행
[2782 / 3885] 	 71.61% 진행
[2783 / 3885] 	 71.63% 진행
[2784 / 3885] 	 71.66% 진행
[2785 / 3885] 	 71.69% 진행
[2786 / 3885] 	 71.71% 진행
[2787 / 3885] 	 71.74% 진행
[2788 / 3885] 	 71.76% 진행
[2789 / 3885] 	 71.79% 진행
[2790 / 3885] 	 71.81% 진행
[2791 / 3885] 	 71.84% 진행
[2792 / 3885] 	 71.87% 진행
[2793 / 3885] 	 71.89% 진행
[2794 / 3885] 	 71.92% 진행
[2795 / 3885] 	 71.94% 진행
[2796 / 3885] 	 71.97% 진행
[2797 / 3885] 	 71.99% 진행
[2798 / 3885] 	 72.02% 진행
[2799 / 3885] 	 72.05% 진행
[2800 / 3885] 	 72.07% 진행
[2801 / 3885] 	 72.10% 진행
[2802 / 3885] 	 72.12% 진행
[2803 / 3885] 	 72.15% 진행
[2804 / 3885] 	 72.18% 진행
[2805 / 3885] 	 72.20% 진행
[2806 / 3885] 	 72.23% 진행
[2807 / 3885] 	 72.25% 진행
[2808 / 3885] 	 72.28% 진행
[2809 / 3885] 	 72.30% 진행
[2810 / 3885] 	 72.33% 진행
[2811 / 3885] 	 72.36% 진행
[2812 / 3885] 	 72.38% 진행
[2813 / 3885] 	 72.41% 진행
[2814 / 3885] 	 72.43% 진행
[2815 / 3885] 	 72.46% 진행
[2816 / 3885] 	 72.48% 진행
[2817 / 3885] 	 72.51% 진행
[2818 / 3885] 	 72.54% 진행
[2819 / 3885] 	 72.56% 진행
[2820 / 3885] 	 72.59% 진행
[2821 / 3885] 	 72.61% 진행
[2822 / 3885] 	 72.64% 진행
[2823 / 3885] 	 72.66% 진행
[2824 / 3885] 	 72.69% 진행
[2825 / 3885] 	 72.72% 진행
[2826 / 3885] 	 72.74% 진행
[2827 / 3885] 	 72.77% 진행
[2828 / 3885] 	 72.79% 진행
[2829 / 3885] 	 72.82% 진행
[2830 / 3885] 	 72.84% 진행
[2831 / 3885] 	 72.87% 진행
[2832 / 3885] 	 72.90% 진행
[2833 / 3885] 	 72.92% 진행
[2834 / 3885] 	 72.95% 진행
[2835 / 3885] 	 72.97% 진행
[2836 / 3885] 	 73.00% 진행
[2837 / 3885] 	 73.02% 진행
[2838 / 3885] 	 73.05% 진행
[2839 / 3885] 	 73.08% 진행
[2840 / 3885] 	 73.10% 진행
[2841 / 3885] 	 73.13% 진행
[2842 / 3885] 	 73.15% 진행
[2843 / 3885] 	 73.18% 진행
[2844 / 3885] 	 73.20% 진행
[2845 / 3885] 	 73.23% 진행
[2846 / 3885] 	 73.26% 진행
[2847 / 3885] 	 73.28% 진행
[2848 / 3885] 	 73.31% 진행
[2849 / 3885] 	 73.33% 진행
[2850 / 3885] 	 73.36% 진행
[2851 / 3885] 	 73.38% 진행
[2852 / 3885] 	 73.41% 진행
[2853 / 3885] 	 73.44% 진행
[2854 / 3885] 	 73.46% 진행
[2855 / 3885] 	 73.49% 진행
[2856 / 3885] 	 73.51% 진행
[2857 / 3885] 	 73.54% 진행
[2858 / 3885] 	 73.56% 진행
[2859 / 3885] 	 73.59% 진행
[2860 / 3885] 	 73.62% 진행
[2861 / 3885] 	 73.64% 진행
[2862 / 3885] 	 73.67% 진행
[2863 / 3885] 	 73.69% 진행
[2864 / 3885] 	 73.72% 진행
[2865 / 3885] 	 73.75% 진행
[2866 / 3885] 	 73.77% 진행
[2867 / 3885] 	 73.80% 진행
[2868 / 3885] 	 73.82% 진행
[2869 / 3885] 	 73.85% 진행
[2870 / 3885] 	 73.87% 진행
[2871 / 3885] 	 73.90% 진행
[2872 / 3885] 	 73.93% 진행
[2873 / 3885] 	 73.95% 진행
[2874 / 3885] 	 73.98% 진행
[2875 / 3885] 	 74.00% 진행
[2876 / 3885] 	 74.03% 진행
[2877 / 3885] 	 74.05% 진행
[2878 / 3885] 	 74.08% 진행
[2879 / 3885] 	 74.11% 진행
[2880 / 3885] 	 74.13% 진행
[2881 / 3885] 	 74.16% 진행
[2882 / 3885] 	 74.18% 진행
[2883 / 3885] 	 74.21% 진행
[2884 / 3885] 	 74.23% 진행
[2885 / 3885] 	 74.26% 진행
[2886 / 3885] 	 74.29% 진행
[2887 / 3885] 	 74.31% 진행
[2888 / 3885] 	 74.34% 진행
[2889 / 3885] 	 74.36% 진행
[2890 / 3885] 	 74.39% 진행
[2891 / 3885] 	 74.41% 진행
[2892 / 3885] 	 74.44% 진행
[2893 / 3885] 	 74.47% 진행
[2894 / 3885] 	 74.49% 진행
[2895 / 3885] 	 74.52% 진행
[2896 / 3885] 	 74.54% 진행
[2897 / 3885] 	 74.57% 진행
[2898 / 3885] 	 74.59% 진행
[2899 / 3885] 	 74.62% 진행
[2900 / 3885] 	 74.65% 진행
[2901 / 3885] 	 74.67% 진행
[2902 / 3885] 	 74.70% 진행
[2903 / 3885] 	 74.72% 진행
[2904 / 3885] 	 74.75% 진행
[2905 / 3885] 	 74.77% 진행
[2906 / 3885] 	 74.80% 진행
[2907 / 3885] 	 74.83% 진행
[2908 / 3885] 	 74.85% 진행
[2909 / 3885] 	 74.88% 진행
[2910 / 3885] 	 74.90% 진행
[2911 / 3885] 	 74.93% 진행
[2912 / 3885] 	 74.95% 진행
[2913 / 3885] 	 74.98% 진행
[2914 / 3885] 	 75.01% 진행
[2915 / 3885] 	 75.03% 진행
[2916 / 3885] 	 75.06% 진행
[2917 / 3885] 	 75.08% 진행
[2918 / 3885] 	 75.11% 진행
[2919 / 3885] 	 75.14% 진행
[2920 / 3885] 	 75.16% 진행
[2921 / 3885] 	 75.19% 진행
[2922 / 3885] 	 75.21% 진행
[2923 / 3885] 	 75.24% 진행
[2924 / 3885] 	 75.26% 진행
[2925 / 3885] 	 75.29% 진행
[2926 / 3885] 	 75.32% 진행
[2927 / 3885] 	 75.34% 진행
[2928 / 3885] 	 75.37% 진행
[2929 / 3885] 	 75.39% 진행
[2930 / 3885] 	 75.42% 진행
[2931 / 3885] 	 75.44% 진행
[2932 / 3885] 	 75.47% 진행
[2933 / 3885] 	 75.50% 진행
[2934 / 3885] 	 75.52% 진행
[2935 / 3885] 	 75.55% 진행
[2936 / 3885] 	 75.57% 진행
[2937 / 3885] 	 75.60% 진행
[2938 / 3885] 	 75.62% 진행
[2939 / 3885] 	 75.65% 진행
[2940 / 3885] 	 75.68% 진행
[2941 / 3885] 	 75.70% 진행
[2942 / 3885] 	 75.73% 진행
[2943 / 3885] 	 75.75% 진행
[2944 / 3885] 	 75.78% 진행
[2945 / 3885] 	 75.80% 진행
[2946 / 3885] 	 75.83% 진행
[2947 / 3885] 	 75.86% 진행
[2948 / 3885] 	 75.88% 진행
[2949 / 3885] 	 75.91% 진행
[2950 / 3885] 	 75.93% 진행
[2951 / 3885] 	 75.96% 진행
[2952 / 3885] 	 75.98% 진행
[2953 / 3885] 	 76.01% 진행
[2954 / 3885] 	 76.04% 진행
[2955 / 3885] 	 76.06% 진행
[2956 / 3885] 	 76.09% 진행
[2957 / 3885] 	 76.11% 진행
[2958 / 3885] 	 76.14% 진행
[2959 / 3885] 	 76.16% 진행
[2960 / 3885] 	 76.19% 진행
[2961 / 3885] 	 76.22% 진행
[2962 / 3885] 	 76.24% 진행
[2963 / 3885] 	 76.27% 진행
[2964 / 3885] 	 76.29% 진행
[2965 / 3885] 	 76.32% 진행
[2966 / 3885] 	 76.34% 진행
[2967 / 3885] 	 76.37% 진행
[2968 / 3885] 	 76.40% 진행
[2969 / 3885] 	 76.42% 진행
[2970 / 3885] 	 76.45% 진행
[2971 / 3885] 	 76.47% 진행
[2972 / 3885] 	 76.50% 진행
[2973 / 3885] 	 76.53% 진행
[2974 / 3885] 	 76.55% 진행
[2975 / 3885] 	 76.58% 진행
[2976 / 3885] 	 76.60% 진행
[2977 / 3885] 	 76.63% 진행
[2978 / 3885] 	 76.65% 진행
[2979 / 3885] 	 76.68% 진행
[2980 / 3885] 	 76.71% 진행
[2981 / 3885] 	 76.73% 진행
[2982 / 3885] 	 76.76% 진행
[2983 / 3885] 	 76.78% 진행
[2984 / 3885] 	 76.81% 진행
[2985 / 3885] 	 76.83% 진행
[2986 / 3885] 	 76.86% 진행
[2987 / 3885] 	 76.89% 진행
[2988 / 3885] 	 76.91% 진행
[2989 / 3885] 	 76.94% 진행
[2990 / 3885] 	 76.96% 진행
[2991 / 3885] 	 76.99% 진행
[2992 / 3885] 	 77.01% 진행
[2993 / 3885] 	 77.04% 진행
[2994 / 3885] 	 77.07% 진행
[2995 / 3885] 	 77.09% 진행
[2996 / 3885] 	 77.12% 진행
[2997 / 3885] 	 77.14% 진행
[2998 / 3885] 	 77.17% 진행
[2999 / 3885] 	 77.19% 진행
[3000 / 3885] 	 77.22% 진행
3000
[776, 777, 778, 779, 780, 781, 782, 783, 784]

In [ ]:
# 추출한 링크에 직접 방문하여 크롤링 진행 - 교수님 제공 코드 이용

# 크롤링 속도를 행상시키기 위해 time.sleep대신 WebDriverWait으로 변경 (다만 네트워크 불량 시 오래 걸릴 수 있음)
# WebDriverWait 이용 시 탐색 속도가 너무 빨라 봇 탐지 가능성 존재 -> time.sleep 이용 요망

# 진행상황 확인코드 추가

# 방문해야 하는 기사수가 3885로 매우 방대 하기 때문에 500개씩 끊어서 진행 (셀 단위)

i = 3000

for link in news_links[i:3500]:
    try:
        all_results[i] = dict()

        # 실제 네이버 뉴스 웹페이지로 이동
        driver.get(link)

        # 페이지 로딩 대기
        time.sleep(0.6) 

        # 제목 추출하기
        title = driver.find_elements(By.XPATH, '/html/body/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/p')
        title = title[0].text 

        # 본문 추출하기
        body = driver.find_elements(By.CLASS_NAME, 'article_content')
        body = body[0].text.replace('\n', '') 

        # 날짜 추출하기
        pubdate_element = driver.find_elements(By.XPATH, '/html/body/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[2]')
        pubdate = pubdate_element[0].text
        pubdate = pubdate[5:24]

        all_results[i]['link'] = link
        all_results[i]['pubdate'] = pubdate
        all_results[i]['title'] = title
        all_results[i]['body'] = body

        # 진행 상황 확인용 코드
        print(f"[{i+1} / {len(news_links)}] \t {(i+1)/len(news_links)*100:.2f}% 진행")    
        i += 1

        # 봇 탐지 방지를 위해 0.8초에서 1.5초 사이에 랜덤한 시간을 기다림
        time.sleep(random.uniform(0.8, 1.5))

    # 오류 발생 시
    except:
        print('오류가 발생했습니다.')
        err_idx.append(i)

        print(f"[{i+1} / {len(news_links)}] \t {(i+1)/len(news_links)*100:.2f}% 진행 - 오류 발생")    
        i += 1

        # 봇 탐지 방지를 위해 0.8초에서 1.5초 사이에 랜덤한 시간을 기다림
        time.sleep(random.uniform(0.8, 1.5))

print(len(all_results))
print(err_idx)

[3001 / 3885] 	 77.25% 진행
[3002 / 3885] 	 77.27% 진행
[3003 / 3885] 	 77.30% 진행
[3004 / 3885] 	 77.32% 진행
[3005 / 3885] 	 77.35% 진행
[3006 / 3885] 	 77.37% 진행
[3007 / 3885] 	 77.40% 진행
[3008 / 3885] 	 77.43% 진행
[3009 / 3885] 	 77.45% 진행
[3010 / 3885] 	 77.48% 진행
[3011 / 3885] 	 77.50% 진행
[3012 / 3885] 	 77.53% 진행
[3013 / 3885] 	 77.55% 진행
[3014 / 3885] 	 77.58% 진행
[3015 / 3885] 	 77.61% 진행
[3016 / 3885] 	 77.63% 진행
[3017 / 3885] 	 77.66% 진행
[3018 / 3885] 	 77.68% 진행
[3019 / 3885] 	 77.71% 진행
[3020 / 3885] 	 77.73% 진행
[3021 / 3885] 	 77.76% 진행
[3022 / 3885] 	 77.79% 진행
[3023 / 3885] 	 77.81% 진행
[3024 / 3885] 	 77.84% 진행
[3025 / 3885] 	 77.86% 진행
[3026 / 3885] 	 77.89% 진행
[3027 / 3885] 	 77.92% 진행
[3028 / 3885] 	 77.94% 진행
[3029 / 3885] 	 77.97% 진행
[3030 / 3885] 	 77.99% 진행
[3031 / 3885] 	 78.02% 진행
[3032 / 3885] 	 78.04% 진행
[3033 / 3885] 	 78.07% 진행
[3034 / 3885] 	 78.10% 진행
[3035 / 3885] 	 78.12% 진행
[3036 / 3885] 	 78.15% 진행
[3037 / 3885] 	 78.17% 진행
[3038 / 3885] 	 78.20% 진행
[3039 / 3885] 	 78.22% 진행
[3040 / 3885] 	 78.25% 진행
[3041 / 3885] 	 78.28% 진행
[3042 / 3885] 	 78.30% 진행
[3043 / 3885] 	 78.33% 진행
[3044 / 3885] 	 78.35% 진행
[3045 / 3885] 	 78.38% 진행
[3046 / 3885] 	 78.40% 진행
[3047 / 3885] 	 78.43% 진행
[3048 / 3885] 	 78.46% 진행
[3049 / 3885] 	 78.48% 진행
[3050 / 3885] 	 78.51% 진행
[3051 / 3885] 	 78.53% 진행
[3052 / 3885] 	 78.56% 진행
[3053 / 3885] 	 78.58% 진행
[3054 / 3885] 	 78.61% 진행
[3055 / 3885] 	 78.64% 진행
[3056 / 3885] 	 78.66% 진행
[3057 / 3885] 	 78.69% 진행
[3058 / 3885] 	 78.71% 진행
[3059 / 3885] 	 78.74% 진행
[3060 / 3885] 	 78.76% 진행
[3061 / 3885] 	 78.79% 진행
[3062 / 3885] 	 78.82% 진행
[3063 / 3885] 	 78.84% 진행
[3064 / 3885] 	 78.87% 진행
[3065 / 3885] 	 78.89% 진행
[3066 / 3885] 	 78.92% 진행
[3067 / 3885] 	 78.94% 진행
[3068 / 3885] 	 78.97% 진행
[3069 / 3885] 	 79.00% 진행
[3070 / 3885] 	 79.02% 진행
[3071 / 3885] 	 79.05% 진행
[3072 / 3885] 	 79.07% 진행
[3073 / 3885] 	 79.10% 진행
[3074 / 3885] 	 79.12% 진행
[3075 / 3885] 	 79.15% 진행
[3076 / 3885] 	 79.18% 진행
[3077 / 3885] 	 79.20% 진행
[3078 / 3885] 	 79.23% 진행
[3079 / 3885] 	 79.25% 진행
[3080 / 3885] 	 79.28% 진행
[3081 / 3885] 	 79.31% 진행
[3082 / 3885] 	 79.33% 진행
[3083 / 3885] 	 79.36% 진행
[3084 / 3885] 	 79.38% 진행
[3085 / 3885] 	 79.41% 진행
[3086 / 3885] 	 79.43% 진행
[3087 / 3885] 	 79.46% 진행
[3088 / 3885] 	 79.49% 진행
[3089 / 3885] 	 79.51% 진행
[3090 / 3885] 	 79.54% 진행
[3091 / 3885] 	 79.56% 진행
[3092 / 3885] 	 79.59% 진행
[3093 / 3885] 	 79.61% 진행
[3094 / 3885] 	 79.64% 진행
[3095 / 3885] 	 79.67% 진행
[3096 / 3885] 	 79.69% 진행
[3097 / 3885] 	 79.72% 진행
[3098 / 3885] 	 79.74% 진행
[3099 / 3885] 	 79.77% 진행
[3100 / 3885] 	 79.79% 진행
[3101 / 3885] 	 79.82% 진행
[3102 / 3885] 	 79.85% 진행
[3103 / 3885] 	 79.87% 진행
[3104 / 3885] 	 79.90% 진행
[3105 / 3885] 	 79.92% 진행
[3106 / 3885] 	 79.95% 진행
[3107 / 3885] 	 79.97% 진행
[3108 / 3885] 	 80.00% 진행
[3109 / 3885] 	 80.03% 진행
[3110 / 3885] 	 80.05% 진행
[3111 / 3885] 	 80.08% 진행
[3112 / 3885] 	 80.10% 진행
[3113 / 3885] 	 80.13% 진행
[3114 / 3885] 	 80.15% 진행
[3115 / 3885] 	 80.18% 진행
[3116 / 3885] 	 80.21% 진행
[3117 / 3885] 	 80.23% 진행
[3118 / 3885] 	 80.26% 진행
[3119 / 3885] 	 80.28% 진행
[3120 / 3885] 	 80.31% 진행
[3121 / 3885] 	 80.33% 진행
[3122 / 3885] 	 80.36% 진행
[3123 / 3885] 	 80.39% 진행
[3124 / 3885] 	 80.41% 진행
[3125 / 3885] 	 80.44% 진행
[3126 / 3885] 	 80.46% 진행
[3127 / 3885] 	 80.49% 진행
[3128 / 3885] 	 80.51% 진행
[3129 / 3885] 	 80.54% 진행
[3130 / 3885] 	 80.57% 진행
[3131 / 3885] 	 80.59% 진행
[3132 / 3885] 	 80.62% 진행
[3133 / 3885] 	 80.64% 진행
[3134 / 3885] 	 80.67% 진행
[3135 / 3885] 	 80.69% 진행
[3136 / 3885] 	 80.72% 진행
[3137 / 3885] 	 80.75% 진행
[3138 / 3885] 	 80.77% 진행
[3139 / 3885] 	 80.80% 진행
[3140 / 3885] 	 80.82% 진행
[3141 / 3885] 	 80.85% 진행
[3142 / 3885] 	 80.88% 진행
[3143 / 3885] 	 80.90% 진행
[3144 / 3885] 	 80.93% 진행
[3145 / 3885] 	 80.95% 진행
[3146 / 3885] 	 80.98% 진행
[3147 / 3885] 	 81.00% 진행
[3148 / 3885] 	 81.03% 진행
[3149 / 3885] 	 81.06% 진행
[3150 / 3885] 	 81.08% 진행
[3151 / 3885] 	 81.11% 진행
[3152 / 3885] 	 81.13% 진행
[3153 / 3885] 	 81.16% 진행
[3154 / 3885] 	 81.18% 진행
[3155 / 3885] 	 81.21% 진행
[3156 / 3885] 	 81.24% 진행
[3157 / 3885] 	 81.26% 진행
[3158 / 3885] 	 81.29% 진행
[3159 / 3885] 	 81.31% 진행
[3160 / 3885] 	 81.34% 진행
[3161 / 3885] 	 81.36% 진행
[3162 / 3885] 	 81.39% 진행
[3163 / 3885] 	 81.42% 진행
[3164 / 3885] 	 81.44% 진행
[3165 / 3885] 	 81.47% 진행
[3166 / 3885] 	 81.49% 진행
[3167 / 3885] 	 81.52% 진행
[3168 / 3885] 	 81.54% 진행
[3169 / 3885] 	 81.57% 진행
[3170 / 3885] 	 81.60% 진행
[3171 / 3885] 	 81.62% 진행
[3172 / 3885] 	 81.65% 진행
[3173 / 3885] 	 81.67% 진행
[3174 / 3885] 	 81.70% 진행
[3175 / 3885] 	 81.72% 진행
[3176 / 3885] 	 81.75% 진행
[3177 / 3885] 	 81.78% 진행
[3178 / 3885] 	 81.80% 진행
[3179 / 3885] 	 81.83% 진행
[3180 / 3885] 	 81.85% 진행
[3181 / 3885] 	 81.88% 진행
[3182 / 3885] 	 81.90% 진행
[3183 / 3885] 	 81.93% 진행
[3184 / 3885] 	 81.96% 진행
[3185 / 3885] 	 81.98% 진행
[3186 / 3885] 	 82.01% 진행
[3187 / 3885] 	 82.03% 진행
[3188 / 3885] 	 82.06% 진행
[3189 / 3885] 	 82.08% 진행
[3190 / 3885] 	 82.11% 진행
[3191 / 3885] 	 82.14% 진행
[3192 / 3885] 	 82.16% 진행
[3193 / 3885] 	 82.19% 진행
[3194 / 3885] 	 82.21% 진행
[3195 / 3885] 	 82.24% 진행
[3196 / 3885] 	 82.27% 진행
[3197 / 3885] 	 82.29% 진행
[3198 / 3885] 	 82.32% 진행
[3199 / 3885] 	 82.34% 진행
[3200 / 3885] 	 82.37% 진행
[3201 / 3885] 	 82.39% 진행
[3202 / 3885] 	 82.42% 진행
[3203 / 3885] 	 82.45% 진행
[3204 / 3885] 	 82.47% 진행
[3205 / 3885] 	 82.50% 진행
[3206 / 3885] 	 82.52% 진행
[3207 / 3885] 	 82.55% 진행
[3208 / 3885] 	 82.57% 진행
[3209 / 3885] 	 82.60% 진행
[3210 / 3885] 	 82.63% 진행
[3211 / 3885] 	 82.65% 진행
[3212 / 3885] 	 82.68% 진행
[3213 / 3885] 	 82.70% 진행
[3214 / 3885] 	 82.73% 진행
[3215 / 3885] 	 82.75% 진행
[3216 / 3885] 	 82.78% 진행
[3217 / 3885] 	 82.81% 진행
[3218 / 3885] 	 82.83% 진행
[3219 / 3885] 	 82.86% 진행
[3220 / 3885] 	 82.88% 진행
[3221 / 3885] 	 82.91% 진행
[3222 / 3885] 	 82.93% 진행
[3223 / 3885] 	 82.96% 진행
[3224 / 3885] 	 82.99% 진행
[3225 / 3885] 	 83.01% 진행
[3226 / 3885] 	 83.04% 진행
[3227 / 3885] 	 83.06% 진행
[3228 / 3885] 	 83.09% 진행
[3229 / 3885] 	 83.11% 진행
[3230 / 3885] 	 83.14% 진행
[3231 / 3885] 	 83.17% 진행
[3232 / 3885] 	 83.19% 진행
[3233 / 3885] 	 83.22% 진행
[3234 / 3885] 	 83.24% 진행
[3235 / 3885] 	 83.27% 진행
[3236 / 3885] 	 83.29% 진행
[3237 / 3885] 	 83.32% 진행
[3238 / 3885] 	 83.35% 진행
[3239 / 3885] 	 83.37% 진행
[3240 / 3885] 	 83.40% 진행
[3241 / 3885] 	 83.42% 진행
[3242 / 3885] 	 83.45% 진행
[3243 / 3885] 	 83.47% 진행
[3244 / 3885] 	 83.50% 진행
[3245 / 3885] 	 83.53% 진행
[3246 / 3885] 	 83.55% 진행
[3247 / 3885] 	 83.58% 진행
[3248 / 3885] 	 83.60% 진행
[3249 / 3885] 	 83.63% 진행
[3250 / 3885] 	 83.66% 진행
[3251 / 3885] 	 83.68% 진행
[3252 / 3885] 	 83.71% 진행
[3253 / 3885] 	 83.73% 진행
[3254 / 3885] 	 83.76% 진행
[3255 / 3885] 	 83.78% 진행
[3256 / 3885] 	 83.81% 진행
[3257 / 3885] 	 83.84% 진행
[3258 / 3885] 	 83.86% 진행
[3259 / 3885] 	 83.89% 진행
[3260 / 3885] 	 83.91% 진행
[3261 / 3885] 	 83.94% 진행
[3262 / 3885] 	 83.96% 진행
[3263 / 3885] 	 83.99% 진행
[3264 / 3885] 	 84.02% 진행
[3265 / 3885] 	 84.04% 진행
[3266 / 3885] 	 84.07% 진행
[3267 / 3885] 	 84.09% 진행
[3268 / 3885] 	 84.12% 진행
[3269 / 3885] 	 84.14% 진행
[3270 / 3885] 	 84.17% 진행
[3271 / 3885] 	 84.20% 진행
[3272 / 3885] 	 84.22% 진행
[3273 / 3885] 	 84.25% 진행
[3274 / 3885] 	 84.27% 진행
[3275 / 3885] 	 84.30% 진행
[3276 / 3885] 	 84.32% 진행
[3277 / 3885] 	 84.35% 진행
[3278 / 3885] 	 84.38% 진행
[3279 / 3885] 	 84.40% 진행
[3280 / 3885] 	 84.43% 진행
[3281 / 3885] 	 84.45% 진행
[3282 / 3885] 	 84.48% 진행
[3283 / 3885] 	 84.50% 진행
[3284 / 3885] 	 84.53% 진행
[3285 / 3885] 	 84.56% 진행
[3286 / 3885] 	 84.58% 진행
[3287 / 3885] 	 84.61% 진행
[3288 / 3885] 	 84.63% 진행
[3289 / 3885] 	 84.66% 진행
[3290 / 3885] 	 84.68% 진행
[3291 / 3885] 	 84.71% 진행
[3292 / 3885] 	 84.74% 진행
[3293 / 3885] 	 84.76% 진행
[3294 / 3885] 	 84.79% 진행
[3295 / 3885] 	 84.81% 진행
[3296 / 3885] 	 84.84% 진행
[3297 / 3885] 	 84.86% 진행
[3298 / 3885] 	 84.89% 진행
[3299 / 3885] 	 84.92% 진행
[3300 / 3885] 	 84.94% 진행
[3301 / 3885] 	 84.97% 진행
[3302 / 3885] 	 84.99% 진행
[3303 / 3885] 	 85.02% 진행
[3304 / 3885] 	 85.05% 진행
[3305 / 3885] 	 85.07% 진행
[3306 / 3885] 	 85.10% 진행
[3307 / 3885] 	 85.12% 진행
[3308 / 3885] 	 85.15% 진행
[3309 / 3885] 	 85.17% 진행
[3310 / 3885] 	 85.20% 진행
[3311 / 3885] 	 85.23% 진행
[3312 / 3885] 	 85.25% 진행
[3313 / 3885] 	 85.28% 진행
[3314 / 3885] 	 85.30% 진행
[3315 / 3885] 	 85.33% 진행
[3316 / 3885] 	 85.35% 진행
[3317 / 3885] 	 85.38% 진행
[3318 / 3885] 	 85.41% 진행
[3319 / 3885] 	 85.43% 진행
[3320 / 3885] 	 85.46% 진행
[3321 / 3885] 	 85.48% 진행
[3322 / 3885] 	 85.51% 진행
[3323 / 3885] 	 85.53% 진행
[3324 / 3885] 	 85.56% 진행
[3325 / 3885] 	 85.59% 진행
[3326 / 3885] 	 85.61% 진행
[3327 / 3885] 	 85.64% 진행
[3328 / 3885] 	 85.66% 진행
[3329 / 3885] 	 85.69% 진행
[3330 / 3885] 	 85.71% 진행
[3331 / 3885] 	 85.74% 진행
[3332 / 3885] 	 85.77% 진행
[3333 / 3885] 	 85.79% 진행
[3334 / 3885] 	 85.82% 진행
[3335 / 3885] 	 85.84% 진행
[3336 / 3885] 	 85.87% 진행
[3337 / 3885] 	 85.89% 진행
[3338 / 3885] 	 85.92% 진행
[3339 / 3885] 	 85.95% 진행
[3340 / 3885] 	 85.97% 진행
[3341 / 3885] 	 86.00% 진행
[3342 / 3885] 	 86.02% 진행
[3343 / 3885] 	 86.05% 진행
[3344 / 3885] 	 86.07% 진행
[3345 / 3885] 	 86.10% 진행
[3346 / 3885] 	 86.13% 진행
[3347 / 3885] 	 86.15% 진행
[3348 / 3885] 	 86.18% 진행
[3349 / 3885] 	 86.20% 진행
[3350 / 3885] 	 86.23% 진행
[3351 / 3885] 	 86.25% 진행
[3352 / 3885] 	 86.28% 진행
[3353 / 3885] 	 86.31% 진행
[3354 / 3885] 	 86.33% 진행
[3355 / 3885] 	 86.36% 진행
[3356 / 3885] 	 86.38% 진행
[3357 / 3885] 	 86.41% 진행
[3358 / 3885] 	 86.44% 진행
[3359 / 3885] 	 86.46% 진행
[3360 / 3885] 	 86.49% 진행
[3361 / 3885] 	 86.51% 진행
[3362 / 3885] 	 86.54% 진행
[3363 / 3885] 	 86.56% 진행
[3364 / 3885] 	 86.59% 진행
[3365 / 3885] 	 86.62% 진행
[3366 / 3885] 	 86.64% 진행
[3367 / 3885] 	 86.67% 진행
[3368 / 3885] 	 86.69% 진행
[3369 / 3885] 	 86.72% 진행
[3370 / 3885] 	 86.74% 진행
[3371 / 3885] 	 86.77% 진행
[3372 / 3885] 	 86.80% 진행
[3373 / 3885] 	 86.82% 진행
[3374 / 3885] 	 86.85% 진행
[3375 / 3885] 	 86.87% 진행
[3376 / 3885] 	 86.90% 진행
[3377 / 3885] 	 86.92% 진행
[3378 / 3885] 	 86.95% 진행
[3379 / 3885] 	 86.98% 진행
[3380 / 3885] 	 87.00% 진행
[3381 / 3885] 	 87.03% 진행
[3382 / 3885] 	 87.05% 진행
[3383 / 3885] 	 87.08% 진행
[3384 / 3885] 	 87.10% 진행
[3385 / 3885] 	 87.13% 진행
[3386 / 3885] 	 87.16% 진행
[3387 / 3885] 	 87.18% 진행
[3388 / 3885] 	 87.21% 진행
[3389 / 3885] 	 87.23% 진행
[3390 / 3885] 	 87.26% 진행
[3391 / 3885] 	 87.28% 진행
[3392 / 3885] 	 87.31% 진행
[3393 / 3885] 	 87.34% 진행
[3394 / 3885] 	 87.36% 진행
[3395 / 3885] 	 87.39% 진행
[3396 / 3885] 	 87.41% 진행
[3397 / 3885] 	 87.44% 진행
[3398 / 3885] 	 87.46% 진행
[3399 / 3885] 	 87.49% 진행
[3400 / 3885] 	 87.52% 진행
[3401 / 3885] 	 87.54% 진행
[3402 / 3885] 	 87.57% 진행
[3403 / 3885] 	 87.59% 진행
[3404 / 3885] 	 87.62% 진행
[3405 / 3885] 	 87.64% 진행
[3406 / 3885] 	 87.67% 진행
[3407 / 3885] 	 87.70% 진행
[3408 / 3885] 	 87.72% 진행
[3409 / 3885] 	 87.75% 진행
[3410 / 3885] 	 87.77% 진행
[3411 / 3885] 	 87.80% 진행
[3412 / 3885] 	 87.82% 진행
[3413 / 3885] 	 87.85% 진행
[3414 / 3885] 	 87.88% 진행
[3415 / 3885] 	 87.90% 진행
[3416 / 3885] 	 87.93% 진행
[3417 / 3885] 	 87.95% 진행
[3418 / 3885] 	 87.98% 진행
[3419 / 3885] 	 88.01% 진행
[3420 / 3885] 	 88.03% 진행
[3421 / 3885] 	 88.06% 진행
[3422 / 3885] 	 88.08% 진행
[3423 / 3885] 	 88.11% 진행
[3424 / 3885] 	 88.13% 진행
[3425 / 3885] 	 88.16% 진행
[3426 / 3885] 	 88.19% 진행
[3427 / 3885] 	 88.21% 진행
[3428 / 3885] 	 88.24% 진행
[3429 / 3885] 	 88.26% 진행
[3430 / 3885] 	 88.29% 진행
[3431 / 3885] 	 88.31% 진행
[3432 / 3885] 	 88.34% 진행
[3433 / 3885] 	 88.37% 진행
[3434 / 3885] 	 88.39% 진행
[3435 / 3885] 	 88.42% 진행
[3436 / 3885] 	 88.44% 진행
[3437 / 3885] 	 88.47% 진행
[3438 / 3885] 	 88.49% 진행
[3439 / 3885] 	 88.52% 진행
[3440 / 3885] 	 88.55% 진행
[3441 / 3885] 	 88.57% 진행
[3442 / 3885] 	 88.60% 진행
[3443 / 3885] 	 88.62% 진행
[3444 / 3885] 	 88.65% 진행
[3445 / 3885] 	 88.67% 진행
[3446 / 3885] 	 88.70% 진행
[3447 / 3885] 	 88.73% 진행
[3448 / 3885] 	 88.75% 진행
[3449 / 3885] 	 88.78% 진행
[3450 / 3885] 	 88.80% 진행
[3451 / 3885] 	 88.83% 진행
[3452 / 3885] 	 88.85% 진행
[3453 / 3885] 	 88.88% 진행
[3454 / 3885] 	 88.91% 진행
[3455 / 3885] 	 88.93% 진행
[3456 / 3885] 	 88.96% 진행
[3457 / 3885] 	 88.98% 진행
[3458 / 3885] 	 89.01% 진행
[3459 / 3885] 	 89.03% 진행
[3460 / 3885] 	 89.06% 진행
[3461 / 3885] 	 89.09% 진행
[3462 / 3885] 	 89.11% 진행
오류가 발생했습니다.
[3463 / 3885] 	 89.14% 진행 - 오류 발생
오류가 발생했습니다.
[3464 / 3885] 	 89.16% 진행 - 오류 발생
오류가 발생했습니다.
[3465 / 3885] 	 89.19% 진행 - 오류 발생
오류가 발생했습니다.
[3466 / 3885] 	 89.21% 진행 - 오류 발생
오류가 발생했습니다.
[3467 / 3885] 	 89.24% 진행 - 오류 발생
오류가 발생했습니다.
[3468 / 3885] 	 89.27% 진행 - 오류 발생
오류가 발생했습니다.
[3469 / 3885] 	 89.29% 진행 - 오류 발생
오류가 발생했습니다.
[3470 / 3885] 	 89.32% 진행 - 오류 발생
오류가 발생했습니다.
[3471 / 3885] 	 89.34% 진행 - 오류 발생
오류가 발생했습니다.
[3472 / 3885] 	 89.37% 진행 - 오류 발생
오류가 발생했습니다.
[3473 / 3885] 	 89.40% 진행 - 오류 발생
오류가 발생했습니다.
[3474 / 3885] 	 89.42% 진행 - 오류 발생
오류가 발생했습니다.
[3475 / 3885] 	 89.45% 진행 - 오류 발생
오류가 발생했습니다.
[3476 / 3885] 	 89.47% 진행 - 오류 발생
오류가 발생했습니다.
[3477 / 3885] 	 89.50% 진행 - 오류 발생
[3478 / 3885] 	 89.52% 진행
[3479 / 3885] 	 89.55% 진행
[3480 / 3885] 	 89.58% 진행
[3481 / 3885] 	 89.60% 진행
[3482 / 3885] 	 89.63% 진행
[3483 / 3885] 	 89.65% 진행
[3484 / 3885] 	 89.68% 진행
[3485 / 3885] 	 89.70% 진행
[3486 / 3885] 	 89.73% 진행
[3487 / 3885] 	 89.76% 진행
[3488 / 3885] 	 89.78% 진행
[3489 / 3885] 	 89.81% 진행
[3490 / 3885] 	 89.83% 진행
[3491 / 3885] 	 89.86% 진행
[3492 / 3885] 	 89.88% 진행
[3493 / 3885] 	 89.91% 진행
[3494 / 3885] 	 89.94% 진행
[3495 / 3885] 	 89.96% 진행
[3496 / 3885] 	 89.99% 진행
[3497 / 3885] 	 90.01% 진행
[3498 / 3885] 	 90.04% 진행
[3499 / 3885] 	 90.06% 진행
[3500 / 3885] 	 90.09% 진행
3500
[776, 777, 778, 779, 780, 781, 782, 783, 784, 3462, 3463, 3464, 3465, 3466, 3467, 3468, 3469, 3470, 3471, 3472, 3473, 3474, 3475, 3476]

In [ ]:
# 추출한 링크에 직접 방문하여 크롤링 진행 - 교수님 제공 코드 이용

# 크롤링 속도를 행상시키기 위해 time.sleep대신 WebDriverWait으로 변경 (다만 네트워크 불량 시 오래 걸릴 수 있음)
# WebDriverWait 이용 시 탐색 속도가 너무 빨라 봇 탐지 가능성 존재 -> time.sleep 이용 요망

# 진행상황 확인코드 추가

# 방문해야 하는 기사수가 3885로 매우 방대 하기 때문에 500개씩 끊어서 진행 (셀 단위)

i = 3500

for link in news_links[i:]:
    try:
        all_results[i] = dict()

        # 실제 네이버 뉴스 웹페이지로 이동
        driver.get(link)

        # 페이지 로딩 대기
        time.sleep(0.6) 

        # 제목 추출하기
        title = driver.find_elements(By.XPATH, '/html/body/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/p')
        title = title[0].text 

        # 본문 추출하기
        body = driver.find_elements(By.CLASS_NAME, 'article_content')
        body = body[0].text.replace('\n', '') 

        # 날짜 추출하기
        pubdate_element = driver.find_elements(By.XPATH, '/html/body/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[2]')
        pubdate = pubdate_element[0].text
        pubdate = pubdate[5:24]

        all_results[i]['link'] = link
        all_results[i]['pubdate'] = pubdate
        all_results[i]['title'] = title
        all_results[i]['body'] = body

        # 진행 상황 확인용 코드
        print(f"[{i+1} / {len(news_links)}] \t {(i+1)/len(news_links)*100:.2f}% 진행")    
        i += 1

        # 봇 탐지 방지를 위해 0.8초에서 1.5초 사이에 랜덤한 시간을 기다림
        time.sleep(random.uniform(0.8, 1.5))

    # 오류 발생 시
    except:
        print('오류가 발생했습니다.')
        err_idx.append(i)

        print(f"[{i+1} / {len(news_links)}] \t {(i+1)/len(news_links)*100:.2f}% 진행 - 오류 발생")    
        i += 1

        # 봇 탐지 방지를 위해 0.8초에서 1.5초 사이에 랜덤한 시간을 기다림
        time.sleep(random.uniform(0.8, 1.5))

print(len(all_results))
print(err_idx)

[3501 / 3885] 	 90.12% 진행
[3502 / 3885] 	 90.14% 진행
[3503 / 3885] 	 90.17% 진행
[3504 / 3885] 	 90.19% 진행
[3505 / 3885] 	 90.22% 진행
[3506 / 3885] 	 90.24% 진행
[3507 / 3885] 	 90.27% 진행
[3508 / 3885] 	 90.30% 진행
[3509 / 3885] 	 90.32% 진행
[3510 / 3885] 	 90.35% 진행
[3511 / 3885] 	 90.37% 진행
[3512 / 3885] 	 90.40% 진행
[3513 / 3885] 	 90.42% 진행
[3514 / 3885] 	 90.45% 진행
[3515 / 3885] 	 90.48% 진행
[3516 / 3885] 	 90.50% 진행
[3517 / 3885] 	 90.53% 진행
[3518 / 3885] 	 90.55% 진행
[3519 / 3885] 	 90.58% 진행
[3520 / 3885] 	 90.60% 진행
[3521 / 3885] 	 90.63% 진행
[3522 / 3885] 	 90.66% 진행
[3523 / 3885] 	 90.68% 진행
[3524 / 3885] 	 90.71% 진행
[3525 / 3885] 	 90.73% 진행
[3526 / 3885] 	 90.76% 진행
[3527 / 3885] 	 90.79% 진행
[3528 / 3885] 	 90.81% 진행
[3529 / 3885] 	 90.84% 진행
[3530 / 3885] 	 90.86% 진행
[3531 / 3885] 	 90.89% 진행
[3532 / 3885] 	 90.91% 진행
[3533 / 3885] 	 90.94% 진행
[3534 / 3885] 	 90.97% 진행
[3535 / 3885] 	 90.99% 진행
[3536 / 3885] 	 91.02% 진행
[3537 / 3885] 	 91.04% 진행
[3538 / 3885] 	 91.07% 진행
[3539 / 3885] 	 91.09% 진행
[3540 / 3885] 	 91.12% 진행
[3541 / 3885] 	 91.15% 진행
[3542 / 3885] 	 91.17% 진행
[3543 / 3885] 	 91.20% 진행
[3544 / 3885] 	 91.22% 진행
[3545 / 3885] 	 91.25% 진행
[3546 / 3885] 	 91.27% 진행
[3547 / 3885] 	 91.30% 진행
[3548 / 3885] 	 91.33% 진행
[3549 / 3885] 	 91.35% 진행
[3550 / 3885] 	 91.38% 진행
[3551 / 3885] 	 91.40% 진행
[3552 / 3885] 	 91.43% 진행
[3553 / 3885] 	 91.45% 진행
[3554 / 3885] 	 91.48% 진행
[3555 / 3885] 	 91.51% 진행
[3556 / 3885] 	 91.53% 진행
[3557 / 3885] 	 91.56% 진행
[3558 / 3885] 	 91.58% 진행
[3559 / 3885] 	 91.61% 진행
[3560 / 3885] 	 91.63% 진행
[3561 / 3885] 	 91.66% 진행
[3562 / 3885] 	 91.69% 진행
[3563 / 3885] 	 91.71% 진행
[3564 / 3885] 	 91.74% 진행
[3565 / 3885] 	 91.76% 진행
[3566 / 3885] 	 91.79% 진행
[3567 / 3885] 	 91.81% 진행
[3568 / 3885] 	 91.84% 진행
[3569 / 3885] 	 91.87% 진행
[3570 / 3885] 	 91.89% 진행
[3571 / 3885] 	 91.92% 진행
[3572 / 3885] 	 91.94% 진행
[3573 / 3885] 	 91.97% 진행
[3574 / 3885] 	 91.99% 진행
[3575 / 3885] 	 92.02% 진행
[3576 / 3885] 	 92.05% 진행
[3577 / 3885] 	 92.07% 진행
[3578 / 3885] 	 92.10% 진행
[3579 / 3885] 	 92.12% 진행
[3580 / 3885] 	 92.15% 진행
[3581 / 3885] 	 92.18% 진행
[3582 / 3885] 	 92.20% 진행
[3583 / 3885] 	 92.23% 진행
[3584 / 3885] 	 92.25% 진행
[3585 / 3885] 	 92.28% 진행
[3586 / 3885] 	 92.30% 진행
[3587 / 3885] 	 92.33% 진행
[3588 / 3885] 	 92.36% 진행
[3589 / 3885] 	 92.38% 진행
[3590 / 3885] 	 92.41% 진행
[3591 / 3885] 	 92.43% 진행
[3592 / 3885] 	 92.46% 진행
[3593 / 3885] 	 92.48% 진행
[3594 / 3885] 	 92.51% 진행
[3595 / 3885] 	 92.54% 진행
[3596 / 3885] 	 92.56% 진행
[3597 / 3885] 	 92.59% 진행
[3598 / 3885] 	 92.61% 진행
[3599 / 3885] 	 92.64% 진행
[3600 / 3885] 	 92.66% 진행
[3601 / 3885] 	 92.69% 진행
[3602 / 3885] 	 92.72% 진행
[3603 / 3885] 	 92.74% 진행
[3604 / 3885] 	 92.77% 진행
[3605 / 3885] 	 92.79% 진행
[3606 / 3885] 	 92.82% 진행
[3607 / 3885] 	 92.84% 진행
[3608 / 3885] 	 92.87% 진행
[3609 / 3885] 	 92.90% 진행
[3610 / 3885] 	 92.92% 진행
[3611 / 3885] 	 92.95% 진행
[3612 / 3885] 	 92.97% 진행
[3613 / 3885] 	 93.00% 진행
[3614 / 3885] 	 93.02% 진행
[3615 / 3885] 	 93.05% 진행
[3616 / 3885] 	 93.08% 진행
[3617 / 3885] 	 93.10% 진행
[3618 / 3885] 	 93.13% 진행
[3619 / 3885] 	 93.15% 진행
[3620 / 3885] 	 93.18% 진행
[3621 / 3885] 	 93.20% 진행
[3622 / 3885] 	 93.23% 진행
[3623 / 3885] 	 93.26% 진행
[3624 / 3885] 	 93.28% 진행
[3625 / 3885] 	 93.31% 진행
[3626 / 3885] 	 93.33% 진행
[3627 / 3885] 	 93.36% 진행
[3628 / 3885] 	 93.38% 진행
[3629 / 3885] 	 93.41% 진행
[3630 / 3885] 	 93.44% 진행
[3631 / 3885] 	 93.46% 진행
[3632 / 3885] 	 93.49% 진행
[3633 / 3885] 	 93.51% 진행
[3634 / 3885] 	 93.54% 진행
[3635 / 3885] 	 93.56% 진행
[3636 / 3885] 	 93.59% 진행
[3637 / 3885] 	 93.62% 진행
[3638 / 3885] 	 93.64% 진행
[3639 / 3885] 	 93.67% 진행
[3640 / 3885] 	 93.69% 진행
[3641 / 3885] 	 93.72% 진행
[3642 / 3885] 	 93.75% 진행
[3643 / 3885] 	 93.77% 진행
[3644 / 3885] 	 93.80% 진행
[3645 / 3885] 	 93.82% 진행
[3646 / 3885] 	 93.85% 진행
[3647 / 3885] 	 93.87% 진행
[3648 / 3885] 	 93.90% 진행
[3649 / 3885] 	 93.93% 진행
[3650 / 3885] 	 93.95% 진행
[3651 / 3885] 	 93.98% 진행
[3652 / 3885] 	 94.00% 진행
[3653 / 3885] 	 94.03% 진행
[3654 / 3885] 	 94.05% 진행
[3655 / 3885] 	 94.08% 진행
[3656 / 3885] 	 94.11% 진행
[3657 / 3885] 	 94.13% 진행
[3658 / 3885] 	 94.16% 진행
[3659 / 3885] 	 94.18% 진행
[3660 / 3885] 	 94.21% 진행
[3661 / 3885] 	 94.23% 진행
[3662 / 3885] 	 94.26% 진행
[3663 / 3885] 	 94.29% 진행
[3664 / 3885] 	 94.31% 진행
[3665 / 3885] 	 94.34% 진행
[3666 / 3885] 	 94.36% 진행
[3667 / 3885] 	 94.39% 진행
[3668 / 3885] 	 94.41% 진행
[3669 / 3885] 	 94.44% 진행
[3670 / 3885] 	 94.47% 진행
[3671 / 3885] 	 94.49% 진행
[3672 / 3885] 	 94.52% 진행
[3673 / 3885] 	 94.54% 진행
[3674 / 3885] 	 94.57% 진행
[3675 / 3885] 	 94.59% 진행
[3676 / 3885] 	 94.62% 진행
[3677 / 3885] 	 94.65% 진행
[3678 / 3885] 	 94.67% 진행
[3679 / 3885] 	 94.70% 진행
[3680 / 3885] 	 94.72% 진행
[3681 / 3885] 	 94.75% 진행
[3682 / 3885] 	 94.77% 진행
[3683 / 3885] 	 94.80% 진행
[3684 / 3885] 	 94.83% 진행
[3685 / 3885] 	 94.85% 진행
[3686 / 3885] 	 94.88% 진행
[3687 / 3885] 	 94.90% 진행
[3688 / 3885] 	 94.93% 진행
[3689 / 3885] 	 94.95% 진행
[3690 / 3885] 	 94.98% 진행
[3691 / 3885] 	 95.01% 진행
[3692 / 3885] 	 95.03% 진행
[3693 / 3885] 	 95.06% 진행
[3694 / 3885] 	 95.08% 진행
[3695 / 3885] 	 95.11% 진행
[3696 / 3885] 	 95.14% 진행
[3697 / 3885] 	 95.16% 진행
[3698 / 3885] 	 95.19% 진행
[3699 / 3885] 	 95.21% 진행
[3700 / 3885] 	 95.24% 진행
[3701 / 3885] 	 95.26% 진행
[3702 / 3885] 	 95.29% 진행
[3703 / 3885] 	 95.32% 진행
[3704 / 3885] 	 95.34% 진행
[3705 / 3885] 	 95.37% 진행
[3706 / 3885] 	 95.39% 진행
[3707 / 3885] 	 95.42% 진행
[3708 / 3885] 	 95.44% 진행
[3709 / 3885] 	 95.47% 진행
[3710 / 3885] 	 95.50% 진행
[3711 / 3885] 	 95.52% 진행
[3712 / 3885] 	 95.55% 진행
[3713 / 3885] 	 95.57% 진행
[3714 / 3885] 	 95.60% 진행
[3715 / 3885] 	 95.62% 진행
[3716 / 3885] 	 95.65% 진행
[3717 / 3885] 	 95.68% 진행
[3718 / 3885] 	 95.70% 진행
[3719 / 3885] 	 95.73% 진행
[3720 / 3885] 	 95.75% 진행
[3721 / 3885] 	 95.78% 진행
[3722 / 3885] 	 95.80% 진행
[3723 / 3885] 	 95.83% 진행
[3724 / 3885] 	 95.86% 진행
[3725 / 3885] 	 95.88% 진행
[3726 / 3885] 	 95.91% 진행
[3727 / 3885] 	 95.93% 진행
[3728 / 3885] 	 95.96% 진행
[3729 / 3885] 	 95.98% 진행
[3730 / 3885] 	 96.01% 진행
[3731 / 3885] 	 96.04% 진행
[3732 / 3885] 	 96.06% 진행
[3733 / 3885] 	 96.09% 진행
[3734 / 3885] 	 96.11% 진행
[3735 / 3885] 	 96.14% 진행
[3736 / 3885] 	 96.16% 진행
[3737 / 3885] 	 96.19% 진행
[3738 / 3885] 	 96.22% 진행
[3739 / 3885] 	 96.24% 진행
[3740 / 3885] 	 96.27% 진행
[3741 / 3885] 	 96.29% 진행
[3742 / 3885] 	 96.32% 진행
[3743 / 3885] 	 96.34% 진행
[3744 / 3885] 	 96.37% 진행
[3745 / 3885] 	 96.40% 진행
[3746 / 3885] 	 96.42% 진행
[3747 / 3885] 	 96.45% 진행
[3748 / 3885] 	 96.47% 진행
[3749 / 3885] 	 96.50% 진행
[3750 / 3885] 	 96.53% 진행
[3751 / 3885] 	 96.55% 진행
[3752 / 3885] 	 96.58% 진행
[3753 / 3885] 	 96.60% 진행
[3754 / 3885] 	 96.63% 진행
[3755 / 3885] 	 96.65% 진행
[3756 / 3885] 	 96.68% 진행
[3757 / 3885] 	 96.71% 진행
[3758 / 3885] 	 96.73% 진행
[3759 / 3885] 	 96.76% 진행
[3760 / 3885] 	 96.78% 진행
[3761 / 3885] 	 96.81% 진행
[3762 / 3885] 	 96.83% 진행
[3763 / 3885] 	 96.86% 진행
[3764 / 3885] 	 96.89% 진행
[3765 / 3885] 	 96.91% 진행
[3766 / 3885] 	 96.94% 진행
[3767 / 3885] 	 96.96% 진행
[3768 / 3885] 	 96.99% 진행
[3769 / 3885] 	 97.01% 진행
[3770 / 3885] 	 97.04% 진행
[3771 / 3885] 	 97.07% 진행
[3772 / 3885] 	 97.09% 진행
[3773 / 3885] 	 97.12% 진행
[3774 / 3885] 	 97.14% 진행
[3775 / 3885] 	 97.17% 진행
[3776 / 3885] 	 97.19% 진행
[3777 / 3885] 	 97.22% 진행
[3778 / 3885] 	 97.25% 진행
[3779 / 3885] 	 97.27% 진행
[3780 / 3885] 	 97.30% 진행
[3781 / 3885] 	 97.32% 진행
[3782 / 3885] 	 97.35% 진행
[3783 / 3885] 	 97.37% 진행
[3784 / 3885] 	 97.40% 진행
[3785 / 3885] 	 97.43% 진행
[3786 / 3885] 	 97.45% 진행
[3787 / 3885] 	 97.48% 진행
[3788 / 3885] 	 97.50% 진행
[3789 / 3885] 	 97.53% 진행
[3790 / 3885] 	 97.55% 진행
[3791 / 3885] 	 97.58% 진행
[3792 / 3885] 	 97.61% 진행
[3793 / 3885] 	 97.63% 진행
[3794 / 3885] 	 97.66% 진행
[3795 / 3885] 	 97.68% 진행
[3796 / 3885] 	 97.71% 진행
[3797 / 3885] 	 97.73% 진행
[3798 / 3885] 	 97.76% 진행
[3799 / 3885] 	 97.79% 진행
[3800 / 3885] 	 97.81% 진행
[3801 / 3885] 	 97.84% 진행
[3802 / 3885] 	 97.86% 진행
[3803 / 3885] 	 97.89% 진행
[3804 / 3885] 	 97.92% 진행
[3805 / 3885] 	 97.94% 진행
[3806 / 3885] 	 97.97% 진행
[3807 / 3885] 	 97.99% 진행
[3808 / 3885] 	 98.02% 진행
[3809 / 3885] 	 98.04% 진행
[3810 / 3885] 	 98.07% 진행
[3811 / 3885] 	 98.10% 진행
[3812 / 3885] 	 98.12% 진행
[3813 / 3885] 	 98.15% 진행
[3814 / 3885] 	 98.17% 진행
[3815 / 3885] 	 98.20% 진행
[3816 / 3885] 	 98.22% 진행
[3817 / 3885] 	 98.25% 진행
[3818 / 3885] 	 98.28% 진행
[3819 / 3885] 	 98.30% 진행
[3820 / 3885] 	 98.33% 진행
[3821 / 3885] 	 98.35% 진행
[3822 / 3885] 	 98.38% 진행
[3823 / 3885] 	 98.40% 진행
[3824 / 3885] 	 98.43% 진행
[3825 / 3885] 	 98.46% 진행
[3826 / 3885] 	 98.48% 진행
[3827 / 3885] 	 98.51% 진행
[3828 / 3885] 	 98.53% 진행
[3829 / 3885] 	 98.56% 진행
[3830 / 3885] 	 98.58% 진행
[3831 / 3885] 	 98.61% 진행
[3832 / 3885] 	 98.64% 진행
[3833 / 3885] 	 98.66% 진행
[3834 / 3885] 	 98.69% 진행
[3835 / 3885] 	 98.71% 진행
[3836 / 3885] 	 98.74% 진행
[3837 / 3885] 	 98.76% 진행
[3838 / 3885] 	 98.79% 진행
[3839 / 3885] 	 98.82% 진행
[3840 / 3885] 	 98.84% 진행
[3841 / 3885] 	 98.87% 진행
[3842 / 3885] 	 98.89% 진행
[3843 / 3885] 	 98.92% 진행
[3844 / 3885] 	 98.94% 진행
[3845 / 3885] 	 98.97% 진행
[3846 / 3885] 	 99.00% 진행
[3847 / 3885] 	 99.02% 진행
[3848 / 3885] 	 99.05% 진행
[3849 / 3885] 	 99.07% 진행
[3850 / 3885] 	 99.10% 진행
[3851 / 3885] 	 99.12% 진행
[3852 / 3885] 	 99.15% 진행
[3853 / 3885] 	 99.18% 진행
[3854 / 3885] 	 99.20% 진행
[3855 / 3885] 	 99.23% 진행
[3856 / 3885] 	 99.25% 진행
[3857 / 3885] 	 99.28% 진행
[3858 / 3885] 	 99.31% 진행
[3859 / 3885] 	 99.33% 진행
[3860 / 3885] 	 99.36% 진행
[3861 / 3885] 	 99.38% 진행
[3862 / 3885] 	 99.41% 진행
[3863 / 3885] 	 99.43% 진행
[3864 / 3885] 	 99.46% 진행
[3865 / 3885] 	 99.49% 진행
[3866 / 3885] 	 99.51% 진행
[3867 / 3885] 	 99.54% 진행
[3868 / 3885] 	 99.56% 진행
[3869 / 3885] 	 99.59% 진행
[3870 / 3885] 	 99.61% 진행
[3871 / 3885] 	 99.64% 진행
[3872 / 3885] 	 99.67% 진행
[3873 / 3885] 	 99.69% 진행
[3874 / 3885] 	 99.72% 진행
[3875 / 3885] 	 99.74% 진행
[3876 / 3885] 	 99.77% 진행
[3877 / 3885] 	 99.79% 진행
[3878 / 3885] 	 99.82% 진행
[3879 / 3885] 	 99.85% 진행
[3880 / 3885] 	 99.87% 진행
[3881 / 3885] 	 99.90% 진행
[3882 / 3885] 	 99.92% 진행
[3883 / 3885] 	 99.95% 진행
[3884 / 3885] 	 99.97% 진행
[3885 / 3885] 	 100.00% 진행
3885
[776, 777, 778, 779, 780, 781, 782, 783, 784, 3462, 3463, 3464, 3465, 3466, 3467, 3468, 3469, 3470, 3471, 3472, 3473, 3474, 3475, 3476]

In [ ]:
if len(err_idx) != 0:
    re_err_idx = []

    for i in err_idx:
        try:
            all_results[i] = dict()

            link = news_links[i]
            
            # 실제 네이버 뉴스 웹페이지로 이동
            driver.get(link)

            # 페이지 로딩 대기
            time.sleep(0.6) 

            # 제목 추출하기
            title = driver.find_elements(By.XPATH, '/html/body/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/p')
            title = title[0].text 

            # 본문 추출하기
            body = driver.find_elements(By.CLASS_NAME, 'article_content')
            body = body[0].text.replace('\n', '') 

            # 날짜 추출하기
            pubdate_element = driver.find_elements(By.XPATH, '/html/body/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[2]')
            pubdate = pubdate_element[0].text
            pubdate = pubdate[5:24]

            all_results[i]['link'] = link
            all_results[i]['pubdate'] = pubdate
            all_results[i]['title'] = title
            all_results[i]['body'] = body

            # 진행 상황 확인용 코드
            print(f"[{i+1} / {len(news_links)}] \t {(i+1)/len(news_links)*100:.2f}% 진행")    
            i += 1

            time.sleep(random.uniform(0.8, 1.5))

        except:
            print('오류가 발생했습니다.')
            re_err_idx.append(i)

            print(f"[{i+1} / {len(news_links)}] \t {(i+1)/len(news_links)*100:.2f}% 진행 - 오류 발생")    
            i += 1

            time.sleep(random.uniform(0.8, 1.5))

    print(len(all_results))
    print(re_err_idx)

[777 / 3885] 	 20.00% 진행
[778 / 3885] 	 20.03% 진행
[779 / 3885] 	 20.05% 진행
[780 / 3885] 	 20.08% 진행
[781 / 3885] 	 20.10% 진행
[782 / 3885] 	 20.13% 진행
[783 / 3885] 	 20.15% 진행
[784 / 3885] 	 20.18% 진행
[785 / 3885] 	 20.21% 진행
[3463 / 3885] 	 89.14% 진행
[3464 / 3885] 	 89.16% 진행
[3465 / 3885] 	 89.19% 진행
[3466 / 3885] 	 89.21% 진행
[3467 / 3885] 	 89.24% 진행
[3468 / 3885] 	 89.27% 진행
[3469 / 3885] 	 89.29% 진행
[3470 / 3885] 	 89.32% 진행
[3471 / 3885] 	 89.34% 진행
[3472 / 3885] 	 89.37% 진행
[3473 / 3885] 	 89.40% 진행
[3474 / 3885] 	 89.42% 진행
[3475 / 3885] 	 89.45% 진행
[3476 / 3885] 	 89.47% 진행
[3477 / 3885] 	 89.50% 진행
3885
[]

### 개별 기사 수집 끝 / datrame으로 저장

In [ ]:
# 수집한 정보들을 dataframe으로 변환
df = pd.DataFrame(all_results).T
df

,link,pubdate,title,body
0,https://www.busan.com/view/busan/view.php?code...,2022-01-05 10:38:05,"밀키트 판매 1위는 '양식'…마이셰프 분석, 고기류 판매 최다","마이셰프가 지난 한 해 판매 데이터를 통해 밀키트 트렌드(사진)를 결산하고, 올해 ..."
1,https://www.busan.com/view/busan/view.php?code...,2022-01-07 11:44:43,[유럽 인문학 기행] 베르사유 궁전에 흐르는 마리 앙투아네트의 사랑,[유럽 인문학 기행-프랑스] 베르사유 궁전(2)베르사유 궁전.■호프부르크의 마리아 ...
2,https://www.busan.com/view/busan/view.php?code...,2022-01-07 15:00:04,"수민동 새마을금고, 취약계층 1인 가구에 전기매트 지원",동래구 수민동 새마을금고(이사장 직무대행 강형기)는 지난 6일 수민동 행정복지센터(...
3,https://www.busan.com/view/busan/view.php?code...,2022-01-11 14:01:59,"남구, 쾌적한 생활환경을 위한 미세먼지 차단숲 조성","황령터널 ~ 대남교차로 구간 미세먼지 차단숲 6,020㎡ 조성부산시 남구가 황령터널..."
4,https://www.busan.com/view/busan/view.php?code...,2022-01-13 18:56:45,"아이가 ‘호’ 하고 불어 주자, 눈아이가 눈물을 흘렸다",눈아이/안녕달안녕달 작가는 그림책에서 눈아이가 아이의 따뜻한 위로에 눈물 흘리는 장...
...,...,...,...,...
3880,https://www.busan.com/view/busan/view.php?code...,2024-12-26 09:48:12,"'연인 폭행' 황철순 ""23kg 빠져 배만 볼록… 맨몸 운동도 금지라 사형선고와 같아""",보디빌더 황철순. 유튜브 영상 갈무리코미디 프로그램에서 징을 치는 '징맨'으로 이름...
3881,https://www.busan.com/view/busan/view.php?code...,2024-12-26 18:12:23,[부산일보 선정 2024년 10대 뉴스-국내] 대한민국 충격 빠뜨린 계엄,"1. 윤 대통령 비상계엄 선포와 해제, 탄핵소추연말 발생한 비상계엄 사태는 대한민국..."
3882,https://www.busan.com/view/busan/view.php?code...,2024-12-30 17:24:02,"[젊어지는 이야기] 갑상선 호르몬, 항노화에 도움?",김미경 해운대백병원 내분비내과 교수/동남권항노화의학회 사무총장2024년 12월 23...
3883,https://www.busan.com/view/busan/view.php?code...,2024-12-30 18:53:06,올해 최고 철도서비스 ‘실시간 열차 위치안내’ 1위 선정,코레일 베스트 서비스 투표 결과 발표여름철 KTX 무지연 청룡 운행 등 이어올해 최...
3884,https://www.busan.com/view/busan/view.php?code...,2024-12-31 11:34:59,12월 소비자물가 1.9% 올라…환율상승에 연초 물가 불안 우려,음식숙박 2.8% 외식 2.9% 등 각각 올라연간 물가 상승률은 2.3% 4년만에 ...

In [ ]:
# 수집한 기사들 중 중복인 경우 이를 제거
df_no_duplicates = df.drop_duplicates().reset_index(drop=True)
df_no_duplicates

,link,pubdate,title,body
0,https://www.busan.com/view/busan/view.php?code...,2022-01-05 10:38:05,"밀키트 판매 1위는 '양식'…마이셰프 분석, 고기류 판매 최다","마이셰프가 지난 한 해 판매 데이터를 통해 밀키트 트렌드(사진)를 결산하고, 올해 ..."
1,https://www.busan.com/view/busan/view.php?code...,2022-01-07 11:44:43,[유럽 인문학 기행] 베르사유 궁전에 흐르는 마리 앙투아네트의 사랑,[유럽 인문학 기행-프랑스] 베르사유 궁전(2)베르사유 궁전.■호프부르크의 마리아 ...
2,https://www.busan.com/view/busan/view.php?code...,2022-01-07 15:00:04,"수민동 새마을금고, 취약계층 1인 가구에 전기매트 지원",동래구 수민동 새마을금고(이사장 직무대행 강형기)는 지난 6일 수민동 행정복지센터(...
3,https://www.busan.com/view/busan/view.php?code...,2022-01-11 14:01:59,"남구, 쾌적한 생활환경을 위한 미세먼지 차단숲 조성","황령터널 ~ 대남교차로 구간 미세먼지 차단숲 6,020㎡ 조성부산시 남구가 황령터널..."
4,https://www.busan.com/view/busan/view.php?code...,2022-01-13 18:56:45,"아이가 ‘호’ 하고 불어 주자, 눈아이가 눈물을 흘렸다",눈아이/안녕달안녕달 작가는 그림책에서 눈아이가 아이의 따뜻한 위로에 눈물 흘리는 장...
...,...,...,...,...
3869,https://www.busan.com/view/busan/view.php?code...,2024-12-26 09:48:12,"'연인 폭행' 황철순 ""23kg 빠져 배만 볼록… 맨몸 운동도 금지라 사형선고와 같아""",보디빌더 황철순. 유튜브 영상 갈무리코미디 프로그램에서 징을 치는 '징맨'으로 이름...
3870,https://www.busan.com/view/busan/view.php?code...,2024-12-26 18:12:23,[부산일보 선정 2024년 10대 뉴스-국내] 대한민국 충격 빠뜨린 계엄,"1. 윤 대통령 비상계엄 선포와 해제, 탄핵소추연말 발생한 비상계엄 사태는 대한민국..."
3871,https://www.busan.com/view/busan/view.php?code...,2024-12-30 17:24:02,"[젊어지는 이야기] 갑상선 호르몬, 항노화에 도움?",김미경 해운대백병원 내분비내과 교수/동남권항노화의학회 사무총장2024년 12월 23...
3872,https://www.busan.com/view/busan/view.php?code...,2024-12-30 18:53:06,올해 최고 철도서비스 ‘실시간 열차 위치안내’ 1위 선정,코레일 베스트 서비스 투표 결과 발표여름철 KTX 무지연 청룡 운행 등 이어올해 최...
3873,https://www.busan.com/view/busan/view.php?code...,2024-12-31 11:34:59,12월 소비자물가 1.9% 올라…환율상승에 연초 물가 불안 우려,음식숙박 2.8% 외식 2.9% 등 각각 올라연간 물가 상승률은 2.3% 4년만에 ...

In [ ]:
# 중복인 기사 확인
df_duplicates = df[df.duplicated(keep=False)]
df_duplicates

,link,pubdate,title,body
1608,https://www.busan.com/view/busan/view.php?code...,2023-08-01 15:01:50,"[르포] 펄펄 끓는 물속, 애끓는 어민 속… “이러다 다 죽는다”",폭염 덮친 통영 양식장 가보니진해만 고수온 주의보→경보 격상양식 어류 2~3일 노출...
1609,https://www.busan.com/view/busan/view.php?code...,2023-08-01 15:01:50,"[르포] 펄펄 끓는 물속, 애끓는 어민 속… “이러다 다 죽는다”",폭염 덮친 통영 양식장 가보니진해만 고수온 주의보→경보 격상양식 어류 2~3일 노출...
2303,https://www.busan.com/view/busan/view.php?code...,2024-05-21 11:00:00,"부산 해운대·송정 해수욕장, 6월 1일 조기 개장…사전 현장점검","부산 7개 해수욕장 모두 전면 개장은 7월 1일해수부, 해수욕장 개장 전 사전점검…..."
2304,https://www.busan.com/view/busan/view.php?code...,2024-05-21 11:00:00,"부산 해운대·송정 해수욕장, 6월 1일 조기 개장…사전 현장점검","부산 7개 해수욕장 모두 전면 개장은 7월 1일해수부, 해수욕장 개장 전 사전점검…..."
2305,https://www.busan.com/view/busan/view.php?code...,2024-05-21 14:42:55,"안방서 1·2위 만나는 롯데, 탈꼴찌 넘어 중위권 도약 최대 고비",이번 주 KIA·삼성과 사직 6경기상위팀 상대 반등 계기 마련해야전준우·정훈 등 부...
2306,https://www.busan.com/view/busan/view.php?code...,2024-05-21 14:42:55,"안방서 1·2위 만나는 롯데, 탈꼴찌 넘어 중위권 도약 최대 고비",이번 주 KIA·삼성과 사직 6경기상위팀 상대 반등 계기 마련해야전준우·정훈 등 부...
2307,https://www.busan.com/view/busan/view.php?code...,2024-05-21 17:12:59,"대청동 지사협, ‘바람 솔솔~ 여름나기 지원’... 여름 이불․베개 전달","중구 대청동지역사회보장협의체(공동위원장 윤영숙․김지영, 이하 지사협)는 지난 20일..."
2308,https://www.busan.com/view/busan/view.php?code...,2024-05-21 17:12:59,"대청동 지사협, ‘바람 솔솔~ 여름나기 지원’... 여름 이불․베개 전달","중구 대청동지역사회보장협의체(공동위원장 윤영숙․김지영, 이하 지사협)는 지난 20일..."
2309,https://www.busan.com/view/busan/view.php?code...,2024-05-21 18:14:29,"[포토뉴스] 벌써 여름, 양산 '불티'",롯데백화점 부산본점 지하 1층 ‘아테스토니’ 매장에서는 다양한 양산 제품을 선보이고...
2310,https://www.busan.com/view/busan/view.php?code...,2024-05-21 18:14:29,"[포토뉴스] 벌써 여름, 양산 '불티'",롯데백화점 부산본점 지하 1층 ‘아테스토니’ 매장에서는 다양한 양산 제품을 선보이고...
2311,https://www.busan.com/view/busan/view.php?code...,2024-05-22 15:27:28,부산진역·시장 등에 ‘쿨링 포그’ 확대… 관광지 이어 원도심 폭염 대비,"동구, 3곳 추가 설치 예정유동 인구 많은 지역 선정‘쿨링 포그’ 시설을 설치할 부..."
2312,https://www.busan.com/view/busan/view.php?code...,2024-05-22 15:27:28,부산진역·시장 등에 ‘쿨링 포그’ 확대… 관광지 이어 원도심 폭염 대비,"동구, 3곳 추가 설치 예정유동 인구 많은 지역 선정‘쿨링 포그’ 시설을 설치할 부..."
2313,https://www.busan.com/view/busan/view.php?code...,2024-05-22 16:18:07,"명륜동 새마을부녀회, 어르신 경로잔치 개최",부산 동래구 명륜동(동장 성영신)은 지난 14일 새마을부녀회(회장 정송자) 주관으로...
2314,https://www.busan.com/view/busan/view.php?code...,2024-05-22 16:18:07,"명륜동 새마을부녀회, 어르신 경로잔치 개최",부산 동래구 명륜동(동장 성영신)은 지난 14일 새마을부녀회(회장 정송자) 주관으로...
2315,https://www.busan.com/view/busan/view.php?code...,2024-05-22 18:20:22,부산 3곳·울산 2곳으로 기상특보 세분화,서울·제주 이어 전국 세 번째시민 편의·방재 효율 상승 기대22일 오후 부산 기장군...
2316,https://www.busan.com/view/busan/view.php?code...,2024-05-22 18:20:22,부산 3곳·울산 2곳으로 기상특보 세분화,서울·제주 이어 전국 세 번째시민 편의·방재 효율 상승 기대22일 오후 부산 기장군...
2317,https://www.busan.com/view/busan/view.php?code...,2024-05-23 11:26:17,부산대 박물관 열린 복합문화공간 '가온나래' 개장… 단오 맞아 민속체험 행사도,"부산대학교 박물관 내 열린 복합문화공간 '가온나래'가온나래, 전문서적 열람 및 학습..."
2318,https://www.busan.com/view/busan/view.php?code...,2024-05-23 11:26:17,부산대 박물관 열린 복합문화공간 '가온나래' 개장… 단오 맞아 민속체험 행사도,"부산대학교 박물관 내 열린 복합문화공간 '가온나래'가온나래, 전문서적 열람 및 학습..."
2319,https://www.busan.com/view/busan/view.php?code...,2024-05-23 16:05:47,노무현 전 대통령 서거 15주기 추도식 현장,노무현 전 대통령 서거 15주기 추도식이 열리는 23일 오후 한 시민이 경남 김해시...
2320,https://www.busan.com/view/busan/view.php?code...,2024-05-23 16:05:47,노무현 전 대통령 서거 15주기 추도식 현장,노무현 전 대통령 서거 15주기 추도식이 열리는 23일 오후 한 시민이 경남 김해시...
2321,https://www.busan.com/view/busan/view.php?code...,2024-05-23 17:17:43,"해운대수목원, 폭염 피해 예방 위해 쿨링포그 16개 설치 완료",부산시 푸른도시가꾸기사업소(이하 푸도사)는 해운대수목원 주진입로에 안개형 냉각수(쿨...
2322,https://www.busan.com/view/busan/view.php?code...,2024-05-23 17:17:43,"해운대수목원, 폭염 피해 예방 위해 쿨링포그 16개 설치 완료",부산시 푸른도시가꾸기사업소(이하 푸도사)는 해운대수목원 주진입로에 안개형 냉각수(쿨...

In [ ]:
# 수집한 정보들을 csv로 저장 (이때 인코딩 형식은 utf8)
df_no_duplicates.to_csv(f'부산 뉴스.csv', index = False, encoding='utf-8-sig')