### 지자체 파일읽기

In [ ]:
import pandas as pd
import numpy as np

# 1. 대구 뉴스 데이터 로드 및 키워드 추가
df = pd.read_csv("대구 뉴스.csv", encoding='utf-8-sig')  # UTF-8 BOM 인코딩으로 대구 뉴스 CSV 파일 읽기
df['keyword'] = '대구 뉴스'  # 데이터 출처 구분을 위한 키워드 컬럼 추가

# 2. 부산 뉴스 데이터 로드 및 키워드 추가
df1 = pd.read_csv("부산 뉴스.csv", encoding='utf-8-sig')  # UTF-8 BOM 인코딩으로 부산 뉴스 CSV 파일 읽기
df1['keyword'] = '부산 뉴스'  # 데이터 출처 구분을 위한 키워드 컬럼 추가

# 3. 서울 뉴스 데이터 로드 및 키워드 추가
df2 = pd.read_csv("서울 뉴스.csv", encoding='utf-8-sig')  # UTF-8 BOM 인코딩으로 서울 뉴스 CSV 파일 읽기
df2['keyword'] = '서울 뉴스'  # 데이터 출처 구분을 위한 키워드 컬럼 추가

# 4. 중복 데이터 제거 및 인덱스 재설정
df = df.drop_duplicates().reset_index(drop=True)    # 대구: 중복 행 제거 후 인덱스를 0부터 다시 설정
df1 = df1.drop_duplicates().reset_index(drop=True)  # 부산: 중복 행 제거 후 인덱스를 0부터 다시 설정
df2 = df2.drop_duplicates().reset_index(drop=True)  # 서울: 중복 행 제거 후 인덱스를 0부터 다시 설정

# 5. 발행일(pubdate) 컬럼을 datetime 형식으로 변환 후 시간순 정렬
df['pubdate'] = pd.to_datetime(df['pubdate'])   # 대구: 문자열 형태의 날짜를 datetime 객체로 변환
df = df.sort_values(by='pubdate')               # 대구: 발행일 기준으로 오름차순 정렬

df1['pubdate'] = pd.to_datetime(df1['pubdate']) # 부산: 문자열 형태의 날짜를 datetime 객체로 변환
df1 = df1.sort_values(by='pubdate')             # 부산: 발행일 기준으로 오름차순 정렬

df2['pubdate'] = pd.to_datetime(df2['pubdate']) # 서울: 문자열 형태의 날짜를 datetime 객체로 변환
df2 = df2.sort_values(by='pubdate')             # 서울: 발행일 기준으로 오름차순 정렬

# 6. 데이터 행 수 확인 및 출력
print("서울:", len(df2), "행")  # 서울 뉴스 데이터의 총 행 수 출력
print("대구:", len(df),  "행")  # 대구 뉴스 데이터의 총 행 수 출력
print("부산:", len(df1),  "행") # 부산 뉴스 데이터의 총 행 수 출력

# 7. 변수명 통일 (가독성을 위한 명확한 변수명으로 재할당)
df_seoul = df2  # 서울 데이터를 명확한 변수명으로 할당
df_daegu = df   # 대구 데이터를 명확한 변수명으로 할당
df_busan = df1  # 부산 데이터를 명확한 변수명으로 할당

서울: 282 행
대구: 205 행
부산: 3874 행

네이버 뉴스 파일 읽기

In [ ]:
import pandas as pd
import numpy as np

# 1. 폭염 관련 세 가지 카테고리별 네이버 뉴스 데이터 로드
df = pd.read_csv("폭염 피해_통합본.csv", encoding='utf-8-sig')  # UTF-8 BOM 인코딩으로 폭염 피해 뉴스 데이터 읽기
df['keyword'] = '폭염 피해'  # 뉴스 카테고리 구분을 위한 키워드 컬럼 추가

df1 = pd.read_csv("폭염 대책_통합본.csv", encoding='utf-8-sig')  # UTF-8 BOM 인코딩으로 폭염 대책 뉴스 데이터 읽기
df1['keyword'] = '폭염 대책'  # 뉴스 카테고리 구분을 위한 키워드 컬럼 추가

df2 = pd.read_csv("폭염 취약_통합본.csv", encoding='cp949')  # CP949 인코딩으로 폭염 취약 뉴스 데이터 읽기
df2['keyword'] = '폭염 취약'  # 뉴스 카테고리 구분을 위한 키워드 컬럼 추가

# 2. 각 데이터프레임별로 중복 기사 제거 및 인덱스 재설정
df = df.drop_duplicates().reset_index(drop=True)    # 폭염 피해: 중복 행 제거 후 인덱스 초기화
df1 = df1.drop_duplicates().reset_index(drop=True)  # 폭염 대책: 중복 행 제거 후 인덱스 초기화
df2 = df2.drop_duplicates().reset_index(drop=True)  # 폭염 취약: 중복 행 제거 후 인덱스 초기화

# 3. 발행일(pubdate) 컬럼을 datetime 형식으로 변환 후 시간순 정렬
df['pubdate'] = pd.to_datetime(df['pubdate'])   # 폭염 피해: 날짜 문자열을 datetime 객체로 변환
df = df.sort_values(by='pubdate')               # 폭염 피해: 발행일 기준 오름차순 정렬

df1['pubdate'] = pd.to_datetime(df1['pubdate']) # 폭염 대책: 날짜 문자열을 datetime 객체로 변환
df1 = df1.sort_values(by='pubdate')             # 폭염 대책: 발행일 기준 오름차순 정렬

df2['pubdate'] = pd.to_datetime(df2['pubdate']) # 폭염 취약: 날짜 문자열을 datetime 객체로 변환
df2 = df2.sort_values(by='pubdate')             # 폭염 취약: 발행일 기준 오름차순 정렬

# 4. 세 개의 데이터프레임을 하나로 통합
df = pd.concat([df, df1, df2], ignore_index=True)  # 세 데이터프레임을 수직으로 합치고 인덱스 재설정
df = df.drop_duplicates().reset_index(drop=True)   # 통합 후 중복 기사 최종 제거 및 인덱스 초기화

# 5. 뉴스 본문(body)에서 지역명 키워드를 찾기 위한 조건 설정
conditions = [
        df['body'].str.contains('서울', na=False),  # 본문에 '서울' 포함 여부 (결측치는 False 처리)
        df['body'].str.contains('부산', na=False),  # 본문에 '부산' 포함 여부
        df['body'].str.contains('인천', na=False),  # 본문에 '인천' 포함 여부
        df['body'].str.contains('대구', na=False),  # 본문에 '대구' 포함 여부
        df['body'].str.contains('대전', na=False),  # 본문에 '대전' 포함 여부
        df['body'].str.contains('광주', na=False),  # 본문에 '광주' 포함 여부
        df['body'].str.contains('울산', na=False),  # 본문에 '울산' 포함 여부
        df['body'].str.contains('세종', na=False),  # 본문에 '세종' 포함 여부
        df['body'].str.contains('경기', na=False),  # 본문에 '경기' 포함 여부
        df['body'].str.contains('충청', na=False),  # 본문에 '충청' 포함 여부
        df['body'].str.contains('전라', na=False),  # 본문에 '전라' 포함 여부
        df['body'].str.contains('경상', na=False),  # 본문에 '경상' 포함 여부
        df['body'].str.contains('강원', na=False),  # 본문에 '강원' 포함 여부
        df['body'].str.contains('제주', na=False)   # 본문에 '제주' 포함 여부
]

# 6. 조건에 맞는 지역명 레이블 설정
choices = ['서울', '부산', '인천', '대구', '대전', '광주', '울산', '세종',
           '경기', '충청', '전라', '경상', '강원', '제주']

# 7. 조건에 따라 지역 분류하여 새로운 컬럼 생성
df['city'] = np.select(conditions, choices, default='없음')  # 조건 만족 시 해당 지역명, 아니면 '없음'

# 8. 주요 도시별로 데이터 분리 저장
df_seoul = df[df['city'] == '서울'].reset_index(drop=True)  # 서울 관련 뉴스만 필터링하여 별도 저장
df_daegu = df[df['city'] == '대구'].reset_index(drop=True)  # 대구 관련 뉴스만 필터링하여 별도 저장
df_busan = df[df['city'] == '부산'].reset_index(drop=True)  # 부산 관련 뉴스만 필터링하여 별도 저장

# 9. 각 도시별 뉴스 데이터 행 수 확인
print("서울:", len(df_seoul), "행")  # 서울 관련 폭염 뉴스 총 개수 출력
print("대구:", len(df_daegu),  "행")  # 대구 관련 폭염 뉴스 총 개수 출력
print("부산:", len(df_busan),  "행")  # 부산 관련 폭염 뉴스 총 개수 출력

### 전처리 및 토큰화 진행

In [ ]:
# ============================================================
# 0. 모듈 import - 텍스트 전처리 및 자연어 처리에 필요한 라이브러리들
# ============================================================
import re, html, logging, emoji, os, random
import pandas as pd
from bs4 import BeautifulSoup        # HTML 태그 제거용
from kiwipiepy import Kiwi            # 한국어 형태소 분석기
from kiwipiepy.utils import Stopwords  # 불용어 처리
from tqdm.auto import tqdm            # 진행률 표시
from collections import Counter       # 빈도 계산
import matplotlib.pyplot as plt       # 시각화
from wordcloud import WordCloud       # 워드클라우드 생성
import itertools                      # 반복자 도구

# 한글 폰트 설정 (matplotlib에서 한글 깨짐 방지)
plt.rcParams['font.family'] = 'Malgun Gothic'
plt.rcParams['axes.unicode_minus'] = False

# ============================================================
# 1. 로깅 - 처리 과정을 추적하기 위한 로그 설정
# ============================================================
logging.basicConfig(level=logging.INFO,
                    format="%(asctime)s %(levelname)s %(message)s",
                    datefmt="%H:%M:%S")
logger = logging.getLogger(__name__)

# ============================================================
# 2. 사전·토크나이저 세팅 - 한국어 처리를 위한 도구들 초기화
# ============================================================
kiwi      = Kiwi(typos='basic')  # 기본 오타 교정 기능이 있는 Kiwi 형태소 분석기
stopwords = Stopwords()          # 기본 불용어 사전

# 2-1) 사용자 정의 불용어 사전 로드
sw_path = r"C:\Users\zxsa0\Downloads\환데\불용어_사전_폭염피해.xlsx"
custom_sw = (pd.read_excel(sw_path, engine="openpyxl")['불용어']  # 엑셀에서 불용어 컬럼 읽기
               .dropna().astype(str).str.strip()                    # 결측치 제거 및 공백 정리
               .str.replace(r'\s+', '', regex=True))                # 내부 공백 제거

# 2-2) Stopwords 객체와 set 동시 갱신
for w in custom_sw:
    stopwords.add(w)  # Stopwords 객체에 사용자 정의 불용어 추가

# Stopwords 객체를 set으로 변환 (빠른 검색을 위해)
stopwords_set = (set(stopwords.words)                # 버전에 따라 words 속성 사용
                 if hasattr(stopwords, "words")
                 else set(stopwords.stopwords))      # 또는 stopwords 속성 사용
stopwords_set.update(custom_sw)                      # 사용자 정의 불용어 추가

# 2-3) 핵심 키워드 사전 로드 (보존해야 할 중요한 단어들)
kw_path   = r"C:\Users\zxsa0\Downloads\환데\heatwave_nouns_final.xlsx"
keep_terms = (pd.read_excel(kw_path, engine="openpyxl").iloc[:, 0]  # 첫 번째 컬럼 읽기
              .dropna().astype(str).str.strip())                    # 결측치 제거 및 공백 정리
keep_terms_set = set(keep_terms)                                   # set으로 변환

# 2-3.5) 불용어와 핵심 키워드 간 충돌 제거 및 Kiwi 사용자 사전 등록
stopwords_set.difference_update(keep_terms_set)      # 핵심 키워드가 불용어에 있으면 제거
for term in keep_terms_set:
    kiwi.add_user_word(term, tag='NNG')              # 핵심 키워드를 일반명사로 사용자 사전에 등록

# A. 불용어·핵심키워드 로딩 확인
print("custom_sw size:", len(custom_sw))                           # 사용자 정의 불용어 개수
print("'기자' in custom_sw ?", '기자' in custom_sw.values)         # '기자' 단어가 불용어에 포함되는지 확인
print("keep_terms size:", len(keep_terms_set))                     # 핵심 키워드 개수
print("stopwords_set size:", len(stopwords_set))                   # 전체 불용어 개수

# B. 필터 동작 확인
print("'기자' in stopwords_set ?", '기자' in stopwords_set)        # '기자'가 최종 불용어 세트에 있는지 확인
print("'폭염현상' in keep_terms_set ?", '폭염현상' in keep_terms_set)  # '폭염현상'이 핵심 키워드에 있는지 확인

# ============================================================
# 3. 전처리·토큰화 함수 - 텍스트 정제 및 토큰화를 위한 함수들
# ============================================================
hangeul_only = re.compile(r'[^ㄱ-ㅎㅏ-ㅣ가-힣 ]')  # 한글과 공백만 남기는 정규식

def clean_html(txt):   
    """HTML 태그 제거"""
    return BeautifulSoup(txt, 'lxml').get_text()

def remove_emoji(txt): 
    """이모지 제거"""
    return emoji.replace_emoji(txt, replace='')

def clean_text(text):
    """텍스트 전처리 메인 함수"""
    try:
        txt = clean_html(text)                           # HTML 태그 제거
        txt = remove_emoji(txt)                          # 이모지 제거
        txt = html.unescape(txt)                         # HTML 엔티티 디코딩 (&amp; → &)
        txt = re.sub(r'\[광고\].*$', '', txt)           # 광고 관련 내용 제거
        txt = kiwi.space(txt.replace('\n', ' '))         # 줄바꿈을 공백으로 변환 후 띄어쓰기 교정
        
        # 문장 단위로 분리하여 처리
        sents = kiwi.split_into_sents(txt)
        res   = []
        for s in sents:
            # 각 문장을 토큰화한 후 불용어 제거하고 다시 결합
            joined = kiwi.join(kiwi.tokenize(s.text, stopwords=stopwords))
            res.append(hangeul_only.sub('', joined))     # 한글 이외 문자 제거
        
        return re.sub(r' {2,}', ' ', ' '.join(res)).strip()  # 연속 공백 제거 및 양끝 공백 제거
    except Exception as e:
        logger.error(f"clean_text 실패: {e}")
        return ""

def tokenize_clean(text):
    """정제된 텍스트를 토큰화하고 필터링"""
    tokens = [tok.form for tok in kiwi.tokenize(text)]   # 형태소 분석하여 토큰 추출
    out = []
    for t in tokens:
        if t in keep_terms_set:                          # 핵심 키워드는 무조건 보존
            out.append(t)                 
        elif len(t) > 1 and t not in stopwords_set:      # 길이 2 이상이고 불용어가 아닌 경우만 포함
            out.append(t)                 
    return out

# C. 실제 토큰화 결과 샘플 테스트
sample = "부산일보 기자가 폭염현상을 집중 보도했다."
print("tokenize_clean →", tokenize_clean(sample))

# ============================================================
# 4. 디버깅 함수 - 실제 분석 전 전처리 파이프라인 테스트
# ============================================================
def debug_stopword_pipeline(df_sample, n=5):
    """무작위 n개 샘플에서 불용어·키워드 적용 여부 점검"""
    sample_rows = df_sample.sample(n=min(n, len(df_sample)), random_state=0)
    
    # 각 샘플에 대해 전처리 과정 확인
    for idx, row in sample_rows.iterrows():
        original = row['body'][:80].replace('\n',' ')    # 원본 텍스트 일부
        body_c   = clean_text(row['body'])               # 전처리된 텍스트
        tokens   = tokenize_clean(body_c)                # 토큰화 결과
        logger.info(f"\n▶ 샘플 {idx}\n  원문  : {original}...\n"
                    f"  body_c: {body_c[:80]}...\n"
                    f"  tokens: {tokens[:30]}")

    # 핵심 키워드 & 불용어 적용 여부 요약
    tests = {
        '기자 in stopwords_set': '기자' in stopwords_set,
        '기자 removed': all('기자' not in t for t in itertools.chain.from_iterable(sample_rows['tokens'] if 'tokens' in sample_rows else [])),
        '핵심키워드 보존 여부 (예: 폭염현상)': '폭염현상' in keep_terms_set
    }
    logger.info("=== 간단 테스트 결과 ===")
    for k, v in tests.items():
        logger.info(f"{k}: {v}")

# ============================================================
# 5. DataFrame 전처리 함수 - 데이터프레임 전체에 전처리 적용
# ============================================================
def preprocess_df(df, name=None, verbose=True):
    """데이터프레임 전체에 전처리 파이프라인 적용"""
    if name: 
        logger.info(f"─── [{name}] 전처리 시작: {len(df)} rows ───")

    # 0) 중복·결측 제거
    before = len(df)
    df = ( df.drop_duplicates(subset=['title','body'])   # 제목과 본문이 동일한 중복 기사 제거
             .dropna(subset=['title','body'])            # 제목이나 본문이 없는 행 제거
             .reset_index(drop=True) )                   # 인덱스 재설정
    after = len(df)
    if verbose:
        logger.info(f"[{name}] 0단계 중복/결측: {before} → {after}")

    # 1) 본문 전처리 (진행률 표시와 함께)
    tqdm.pandas(desc=f"{name} 클리닝")
    df['body_clean'] = df['body'].progress_map(clean_text)  # 모든 행의 본문에 clean_text 적용

    # 2) 토큰화 열 추가
    df['tokens'] = df['body_clean'].map(tokenize_clean)     # 정제된 본문을 토큰화

    if verbose:
        logger.info(f"[{name}] 전처리 후 샘플")
        display(df[['title','body_clean','tokens']].head(2))  # 결과 확인용 샘플 출력
        logger.info(f"[{name}] 전처리 완료: {len(df)} rows")

    return df

# ─────────────────────────────────────────────────────────────
# 6. 도시별 데이터프레임 전처리 실행
# ─────────────────────────────────────────────────────────────
# 서울, 대구, 부산 각 도시별 데이터에 전처리 파이프라인 적용
for city, df_city in [('서울', df_seoul), ('대구', df_daegu), ('부산', df_busan)]:
    vars()[f"df_{city}"] = preprocess_df(df_city, name=city)  # 동적 변수명으로 결과 저장

# ─────────────────────────────────────────────────────────────
# 7. 최종 검증 & CSV 저장 (UTF-8-SIG → 한글 Excel 호환)
# ─────────────────────────────────────────────────────────────
for city in ['서울','대구','부산']:
    df_c = vars()[f"df_{city}"]                          # 전처리된 데이터프레임 가져오기
    logger.info(f"{city} 최종 rows: {len(df_c)}")        # 최종 데이터 개수 확인
    display(df_c.info())                                 # 데이터프레임 정보 출력
    csv_path = f"{city.lower()}.csv"                     # 저장할 파일명 생성
    df_c.to_csv(csv_path, index=False, encoding='utf-8-sig')  # UTF-8-SIG로 저장 (한글 엑셀 호환)
    logger.info(f"{city} CSV 저장 완료 → {csv_path}")    # 저장 완료 메시지

00:02:06 INFO ─── [서울] 전처리 시작: 282 rows ───
00:02:06 INFO [서울] 0단계 중복/결측: 282 → 180

custom_sw size: 174
'기자' in custom_sw ? True
keep_terms size: 500
stopwords_set size: 436
'기자' in stopwords_set ? True
'폭염현상' in keep_terms_set ? True
tokenize_clean → ['부산일보', '폭염현상', '집중', '보도']

서울 클리닝:   0%|          | 0/180 [00:00<?, ?it/s]

00:03:32 INFO [서울] 전처리 후 샘플

,title,body_clean,tokens
0,"2026년까지 저탄소건물 100만호, 전기차 40만대 늘린다",올해 간 기후 변화 대응 종합 계획 추진 온실가스 줄이 기후 위기로부터 안전 도시 ...,"[올해, 기후, 변화, 대응, 종합, 계획, 추진, 온실가스, 기후, 위기, 로부터..."
1,'서울형 긴급복지' 기준 완화 연장…코로나 '심각' 해제까지,코로나 감염병 심각 단계가 해제 시 형 긴급 복지 기준 완화 연장 현재 최고 단계 ...,"[코로나, 감염병, 심각, 단계, 해제, 긴급, 복지, 기준, 완화, 연장, 최고,..."

00:03:32 INFO [서울] 전처리 완료: 180 rows
00:03:32 INFO ─── [대구] 전처리 시작: 205 rows ───
00:03:32 INFO [대구] 0단계 중복/결측: 205 → 205

대구 클리닝:   0%|          | 0/205 [00:00<?, ?it/s]

00:04:12 INFO [대구] 전처리 후 샘플

,title,body_clean,tokens
0,사회취약계층 건강보호 위한 환경보건서비스 강화,올해 취약 가구 대상 실내 환경 진단 시설 개선 병원 진료 지원 환경부 장관 한정애...,"[올해, 취약, 가구, 대상, 실내, 환경, 진단, 시설, 개선, 병원, 진료, 지..."
1,"대구시, 전국 최초 ‘스마트시티 데이터허브’ 운영",수성 알파 시티 내 스마트시티 데이터 허브 센터 개소대구시 스마트시티 기술 핵심 요...,"[수성, 알파, 시티, 스마트시티, 데이터, 허브, 센터, 개소대구시, 스마트시티,..."

00:04:12 INFO [대구] 전처리 완료: 205 rows
00:04:12 INFO ─── [부산] 전처리 시작: 3874 rows ───
00:04:12 INFO [부산] 0단계 중복/결측: 3874 → 3871

부산 클리닝:   0%|          | 0/3871 [00:00<?, ?it/s]

C:\Users\zxsa0\AppData\Local\Temp\ipykernel_36876\667033734.py:71: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  def clean_html(txt):   return BeautifulSoup(txt, 'lxml').get_text()
00:14:34 INFO [부산] 전처리 후 샘플

,title,body_clean,tokens
0,"밀키트 판매 1위는 '양식'…마이셰프 분석, 고기류 판매 최다",마이 셰프 지나 해 판매 데이터 밀 키트 트렌드 사진 결산 올해 밀 키트 전망 발표...,"[마이, 셰프, 판매, 데이터, 키트, 트렌드, 사진, 결산, 올해, 키트, 전망,..."
1,[유럽 인문학 기행] 베르사유 궁전에 흐르는 마리 앙투아네트의 사랑,유럽 인문학 기행 프랑스 베르사유 궁전 베르사유 궁전 호프부르크 마리아 앙투앙 응 ...,"[유럽, 인문학, 기행, 프랑스, 베르사유, 궁전, 베르사유, 궁전, 호프부르크, ..."

00:14:34 INFO [부산] 전처리 완료: 3871 rows
00:14:34 INFO 서울 최종 rows: 180

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       180 non-null    object
 1   pubdate     180 non-null    datetime64[ns]
 2   body        180 non-null    object
 3   link        180 non-null    object
 4   keyword     180 non-null    object
 5   body_clean  180 non-null    object
 6   tokens      180 non-null    object
dtypes: datetime64[ns](1), object(6)
memory usage: 10.0+ KB

None

00:14:34 INFO 서울 CSV 저장 완료 → 서울.csv
00:14:34 INFO 대구 최종 rows: 205

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   link        205 non-null    object
 1   pubdate     205 non-null    datetime64[ns]
 2   title       205 non-null    object
 3   body        205 non-null    object
 4   keyword     205 non-null    object
 5   body_clean  205 non-null    object
 6   tokens      205 non-null    object
dtypes: datetime64[ns](1), object(6)
memory usage: 11.3+ KB

None

00:14:34 INFO 대구 CSV 저장 완료 → 대구.csv
00:14:34 INFO 부산 최종 rows: 3871

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3871 entries, 0 to 3870
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   link        3871 non-null   object
 1   pubdate     3871 non-null   datetime64[ns]
 2   title       3871 non-null   object
 3   body        3871 non-null   object
 4   keyword     3871 non-null   object
 5   body_clean  3871 non-null   object
 6   tokens      3871 non-null   object
dtypes: datetime64[ns](1), object(6)
memory usage: 211.8+ KB

None

00:14:35 INFO 부산 CSV 저장 완료 → 부산.csv

### 지자체 뉴스 데이터 워드클라우드 및 빈도 분석

In [ ]:
# ─────────────────────────────────────────────────────────────
# 지자체 뉴스 데이터 워드클라우드 및 빈도 분석
# ─────────────────────────────────────────────────────────────

# ─────────────────────────────────────────────────────────────
# 0) 모듈 import - 텍스트 분석 및 시각화에 필요한 라이브러리들
#    (추가 설치: pip install wordcloud matplotlib)
# ─────────────────────────────────────────────────────────────
from collections import Counter      # 단어 빈도 계산용
import pandas as pd                  # 데이터프레임 처리
import matplotlib.pyplot as plt      # 그래프 시각화
from wordcloud import WordCloud      # 워드클라우드 생성
import os, itertools                 # 파일 시스템 및 반복자 도구

# ─ 그래프·워드클라우드용 한글 폰트 설정 ─
plt.rcParams['font.family'] = 'Malgun Gothic'     # 한글 폰트 설정 (Windows 환경)
plt.rcParams['axes.unicode_minus'] = False        # 마이너스 기호 깨짐 방지

# ─────────────────────────────────────────────────────────────
# 1) 분석 대상 DataFrame 딕셔너리
#    (전처리 완료된 df_서울·df_대구·df_부산이 메모리에 존재한다고 가정)
# ─────────────────────────────────────────────────────────────
city_dfs = {'서울': df_서울, '대구': df_대구, '부산': df_부산}  # 도시별 데이터프레임 매핑

# 결과 저장 폴더 생성
out_dir = "results_city"                          # 분석 결과 저장할 폴더명
os.makedirs(out_dir, exist_ok=True)              # 폴더가 없으면 생성

# 분석 설정값
TOP_N = 30          # 상위 단어 개수 (막대그래프 및 CSV 저장용)
WC_TOP_ALL = 50     # 통합 워드클라우드에 포함할 단어 수

# ─────────────────────────────────────────────────────────────
# 2) 단어 빈도 집계 함수
#    - tokens 열: 각 행이 단어 리스트 형태 → 모든 단어를 납작하게 펼쳐 Counter 생성
# ─────────────────────────────────────────────────────────────
def get_word_freq(tokens_series: pd.Series) -> Counter:
    """
    토큰화된 단어 리스트들을 하나로 합쳐서 빈도 계산
    
    Args:
        tokens_series: 각 행이 [단어1, 단어2, ...] 형태인 pandas Series
    
    Returns:
        Counter: {단어: 빈도} 형태의 빈도 사전
    """
    # itertools.chain.from_iterable: 중첩된 리스트를 하나의 평면 리스트로 변환
    # 예: [[단어1, 단어2], [단어3, 단어4]] → [단어1, 단어2, 단어3, 단어4]
    flat = itertools.chain.from_iterable(tokens_series.dropna())  # 결측치 제거 후 펼치기
    return Counter(flat)  # 단어별 등장 횟수 계산

# ─────────────────────────────────────────────────────────────
# 3) 도시별 빈도 분석 + 시각화 루프
#    각 도시마다 빈도 분석, CSV 저장, 막대그래프, 워드클라우드 생성
# ─────────────────────────────────────────────────────────────
for city, df in city_dfs.items():
    print(f"📊 {city} 분석 시작...")
    
    # 3-1) 빈도 계산 및 상위 TOP_N개 추출
    freq_cnt = get_word_freq(df['tokens'])            # 전체 단어 빈도 계산
    freq_df  = (pd.DataFrame(freq_cnt.items(), columns=['word', 'count'])  # 데이터프레임으로 변환
                .nlargest(TOP_N, 'count'))            # 빈도 기준 상위 TOP_N개 선택

    # 3-2) CSV 저장 (한글 엑셀 호환)
    freq_df.to_csv(f"{out_dir}/{city}_freq_top{TOP_N}.csv",
                   index=False, encoding='utf-8-sig')  # UTF-8-SIG로 저장하여 엑셀에서 한글 깨짐 방지

    # 3-3) 막대 그래프 생성 (가로형)
    plt.figure(figsize=(10, 6))                       # 그래프 크기 설정
    plt.barh(freq_df['word'], freq_df['count'])       # 가로 막대그래프 생성
    plt.gca().invert_yaxis()                          # Y축 뒤집기 (높은 빈도를 위쪽에 배치)
    plt.title(f"{city} 상위 {TOP_N} 키워드 빈도")      # 그래프 제목
    plt.xlabel("등장 횟수")                           # X축 레이블
    plt.tight_layout()                                # 레이아웃 자동 조정
    plt.savefig(f"{out_dir}/{city}_bar_top{TOP_N}.png", dpi=300)  # 고해상도로 저장
    plt.close()                                       # 메모리 절약을 위해 그래프 닫기

    # 3-4) 워드클라우드 생성
    wc = WordCloud(
        font_path="C:/Windows/Fonts/malgun.ttf",      # 한글 폰트 파일 경로 (시스템 폰트)
        width=1200, height=800,                       # 워드클라우드 크기
        background_color="white"                      # 배경색
    ).generate_from_frequencies(freq_cnt)             # 빈도 사전으로부터 워드클라우드 생성
    
    plt.figure(figsize=(12, 8))                       # 출력 이미지 크기
    plt.imshow(wc, interpolation="bilinear")          # 워드클라우드 이미지 표시
    plt.axis("off")                                   # 축 눈금 제거
    plt.title(f"{city} 워드클라우드", size=18)         # 제목 설정
    plt.tight_layout()                                # 레이아웃 조정
    plt.savefig(f"{out_dir}/{city}_wordcloud.png", dpi=300)  # 고해상도로 저장
    plt.close()                                       # 메모리 해제

    print(f"✅ {city}: CSV·그래프·워드클라우드 저장 완료")

# ─────────────────────────────────────────────────────────────
# 4) 전체 도시 통합 워드클라우드
#    서울, 대구, 부산의 모든 단어를 합쳐서 통합 분석
# ─────────────────────────────────────────────────────────────
print("🔄 전체 도시 통합 분석 시작...")

freq_all = Counter()                                  # 전체 도시 통합 빈도 카운터 초기화
for df in city_dfs.values():                          # 각 도시 데이터프레임을 순회
    freq_all.update(get_word_freq(df['tokens']))      # 해당 도시의 단어 빈도를 통합 카운터에 누적

# 상위 WC_TOP_ALL개 단어만 선별하여 워드클라우드 생성
top_all_dict = dict(Counter(freq_all).most_common(WC_TOP_ALL))  # 상위 단어들만 딕셔너리로 변환

wc_all = WordCloud(
    font_path="C:/Windows/Fonts/malgun.ttf",          # 한글 폰트
    width=1400, height=900,                           # 통합 워드클라우드는 더 큰 크기
    background_color="white"                          # 흰색 배경
).generate_from_frequencies(top_all_dict)            # 상위 단어들로 워드클라우드 생성

plt.figure(figsize=(14, 9))                           # 큰 출력 크기
plt.imshow(wc_all, interpolation="bilinear")          # 워드클라우드 표시
plt.axis("off")                                       # 축 제거
plt.title(f"전체 도시 통합 워드클라우드 (Top {WC_TOP_ALL})", size=20)  # 제목
plt.tight_layout()                                    # 레이아웃 조정
plt.savefig(f"{out_dir}/ALL_wordcloud_top{WC_TOP_ALL}.png", dpi=300)  # 저장
plt.close()                                           # 메모리 해제

print("🎉 통합 워드클라우드까지 완료!")
print(f"📁 모든 결과는 '{out_dir}' 폴더에 저장되었습니다.")

✅ 서울: CSV·그래프·워드클라우드 저장 완료
✅ 대구: CSV·그래프·워드클라우드 저장 완료
✅ 부산: CSV·그래프·워드클라우드 저장 완료
🎉 통합 워드클라우드까지 완료!

### 네이버 뉴스 데이터 워드클라우드 및 빈도 분석(지역별, 키워드별, 통합)

In [ ]:
# ============================================================
# 네이버 뉴스 데이터 워드클라우드 및 빈도 분석
# (지역별, 키워드별, 통합 분석)
# ============================================================

# ============================================================
# 0) 모듈 import - 텍스트 분석 및 시각화 도구
#    (추가 설치: pip install wordcloud matplotlib)
# ============================================================
from collections import Counter        # 단어 빈도 계산
import pandas as pd                    # 데이터프레임 처리
import matplotlib.pyplot as plt        # 그래프 시각화
from wordcloud import WordCloud        # 워드클라우드 생성
import os, itertools, datetime, pathlib  # 파일 시스템, 반복자, 날짜, 경로 처리
import ast                            # 문자열을 안전하게 파이썬 객체로 변환

# 한글 폰트 설정 (그래프와 워드클라우드에서 한글 깨짐 방지)
plt.rcParams['font.family'] = 'Malgun Gothic'
plt.rcParams['axes.unicode_minus'] = False

# ============================================================
# 1) 파라미터 설정 - 분석 조건 및 대상 데이터 정의
# ============================================================
TOP_N        = 30   # 단어 빈도표·막대그래프에 표시할 상위 N개 단어
WC_TOP_ALL   = 50   # 통합 워드클라우드에 포함할 단어 수
OUT_ROOT     = "results_navernews"     # 결과 저장할 최상위 폴더명
cities       = ['서울', '대구', '부산']                       # 분석 대상 도시 목록
keywords     = ['폭염 피해', '폭염 대책', '폭염 취약']         # 분석할 키워드 카테고리

# 전처리 완료된 DataFrame들(메모리에 이미 존재한다고 가정)
city_dfs = {'서울': df_서울, '대구': df_대구, '부산': df_부산}

# 결과 저장 폴더 생성
os.makedirs(OUT_ROOT, exist_ok=True)

# ────────────────────────────────────────────────────────────────────────────
# 0.5) 토큰 데이터 타입 변환
#      CSV 저장 후 다시 읽을 때 tokens 열이 문자열로 저장될 수 있으므로 리스트로 변환
# ────────────────────────────────────────────────────────────────────────────
def str_to_list(x):
    """
    tokens 열의 문자열을 안전하게 리스트로 변환하는 함수
    
    Args:
        x: tokens 열의 각 셀 값 (문자열, 리스트, 또는 기타)
    
    Returns:
        list: 변환된 토큰 리스트
    """
    if isinstance(x, str):
        try:
            # ast.literal_eval: 문자열 형태의 파이썬 리터럴을 안전하게 평가
            # 예: "['단어1', '단어2']" → ['단어1', '단어2']
            return ast.literal_eval(x)
        except Exception:
            # 예상치 못한 문자열 포맷이면 빈 리스트로 처리
            return []
    elif isinstance(x, list):
        # 이미 리스트 타입이면 그대로 반환
        return x
    else:
        # 나머지 경우 (None, 숫자 등)에도 빈 리스트로 처리
        return []

# 각 도시 DataFrame의 tokens 열을 리스트 타입으로 변환
df_서울['tokens'] = df_서울['tokens'].apply(str_to_list)
df_대구['tokens'] = df_대구['tokens'].apply(str_to_list)
df_부산['tokens'] = df_부산['tokens'].apply(str_to_list)

# 변환 결과 확인 (디버깅용)
for idx, toks in enumerate(df_서울['tokens'].head(3)):
    print(idx, "번째 tokens:", toks, "→ type:", type(toks))

# 추가 불용어 설정 (형태소 분석 시 자주 나타나는 불필요한 어미 등)
stopwords_set_2 = {
    '은', '는', '이', '가', '하다', '입니다', '합니다',  # 기본 조사·어미
    '폭염', '피해',                                    # 주제어 (너무 일반적)
    '니다', 'ㅂ니다',                                   # 어미 잔재
    'ᆸ니다'                                           # 형태소 분석 시 나타나는 어미 'ᆸ니다'
}

# ============================================================
# 2) 공통 유틸리티 함수들
# ============================================================
def get_word_freq(tokens_series: pd.Series) -> Counter:
    """
    토큰 시리즈에서 단어 빈도를 계산하는 함수
    
    Args:
        tokens_series: 각 행이 토큰 리스트인 pandas Series
    
    Returns:
        Counter: 정제된 단어들의 빈도 사전
    """
    # 모든 토큰 리스트를 하나로 펼치기
    flat_iter = itertools.chain.from_iterable(tokens_series.dropna())
    
    # 단어 필터링: 길이 2이상, 불용어 제외, 알파벳만 (한글 포함)
    clean_iter = (t for t in flat_iter
                    if len(t) > 1                    # 한 글자 단어 제외
                    and t not in stopwords_set      # 기본 불용어 제외
                    and t not in stopwords_set_2    # 추가 불용어 제외
                    and t.isalpha())                 # 숫자나 특수문자 포함 단어 제외
    
    return Counter(clean_iter)

def save_bar(freq_df: pd.DataFrame, title: str, path: str):
    """가로 막대그래프를 생성하고 저장하는 함수"""
    plt.figure(figsize=(10, 6))                      # 그래프 크기 설정
    plt.barh(freq_df['word'], freq_df['count'])      # 가로 막대그래프 생성
    plt.gca().invert_yaxis()                         # Y축 뒤집기 (높은 빈도를 위에)
    plt.title(title)                                 # 그래프 제목
    plt.xlabel("등장 횟수")                          # X축 레이블
    plt.tight_layout()                               # 레이아웃 자동 조정
    plt.savefig(path, dpi=300)                       # 고해상도로 저장
    plt.close()                                      # 메모리 해제

def save_wc(freq: Counter, title: str, path: str):
    """워드클라우드를 생성하고 저장하는 함수"""
    wc = WordCloud(
        font_path="C:/Windows/Fonts/malgun.ttf",     # 한글 폰트 경로
        width=1200, height=800,                      # 워드클라우드 크기
        background_color="white"                     # 배경색
    ).generate_from_frequencies(freq)                # 빈도 사전으로부터 생성
    
    plt.figure(figsize=(12, 8))                      # 출력 이미지 크기
    plt.imshow(wc, interpolation='bilinear')         # 워드클라우드 표시
    plt.axis('off')                                  # 축 눈금 제거
    plt.title(title, size=18)                        # 제목 설정
    plt.tight_layout()                               # 레이아웃 조정
    plt.savefig(path, dpi=300)                       # 고해상도로 저장
    plt.close()                                      # 메모리 해제

# ============================================================
# 3) (A) 도시 전체 분석 - 각 도시별 전체 뉴스 통합 분석
# ============================================================
print("📊 도시별 전체 분석 시작...")

for city, df in city_dfs.items():
    print(f"🔄 {city} 전체 분석 중...")
    
    # 1) 해당 도시의 모든 뉴스에서 단어 빈도 계산
    freq = get_word_freq(df['tokens'])
    
    # 디버깅: 빈도 계산 결과 확인
    debug_freq = get_word_freq(df['tokens'])
    print("최종 Counter 예시:", debug_freq.most_common(5))
    
    # 2) Counter 객체를 DataFrame으로 변환
    freq_df = pd.DataFrame(freq.items(), columns=['word', 'count'])
    
    # 3) count 열을 정수형으로 명시적 변환 (nlargest 함수 사용을 위해 필수)
    freq_df['count'] = freq_df['count'].astype(int)
    
    # 4) 빈도 기준 상위 TOP_N개 추출
    top_freq_df = freq_df.nlargest(TOP_N, 'count')
    
    # 5) 저장 디렉토리 생성 (도시명/ALL 구조)
    city_dir = pathlib.Path(OUT_ROOT) / city / "ALL"
    city_dir.mkdir(parents=True, exist_ok=True)
    
    # 6) 결과 저장: CSV, 막대그래프, 워드클라우드
    # CSV 저장 (엑셀 호환을 위해 UTF-8-SIG 인코딩)
    top_freq_df.to_csv(city_dir / f"{city}_freq_top{TOP_N}.csv",
                       index=False, encoding='utf-8-sig')
    
    # 가로 막대그래프 저장
    save_bar(top_freq_df,
             f"[{city}] 상위 {TOP_N} 키워드 빈도",
             city_dir / f"{city}_bar_top{TOP_N}.png")
    
    # 워드클라우드 저장
    save_wc(freq,
            f"[{city}] 워드클라우드",
            city_dir / f"{city}_wordcloud.png")
    
    print(f"✅ {city} 전체 분석 완료")

# ============================================================
# 4) (B) 도시 × 키워드 세부 분석 - 각 도시별, 키워드별 세분화 분석
# ============================================================
print("🔍 도시별×키워드별 세부 분석 시작...")

for city, df in city_dfs.items():
    for kw in keywords:
        print(f"🔄 {city}-{kw} 분석 중...")
        
        # 해당 도시에서 특정 키워드만 필터링
        sub = df[df['keyword'] == kw]
        if sub.empty:                                # 데이터가 없으면 스킵
            print(f"⚠️ {city}-{kw}: 데이터 없음")
            continue
        
        # 필터링된 데이터에서 단어 빈도 계산
        freq = get_word_freq(sub['tokens'])
        freq_df = pd.DataFrame(freq.items(), columns=['word','count'])
        
        # count 열을 정수형으로 변환
        freq_df['count'] = freq_df['count'].astype(int)
        
        # 상위 TOP_N개 추출
        top_freq_df = freq_df.nlargest(TOP_N, 'count')
        
        # 저장 경로 생성 (키워드에서 공백 제거하여 폴더명으로 사용)
        safe_kw = kw.replace(' ', '')                # '폭염 피해' → '폭염피해'
        ck_dir = pathlib.Path(OUT_ROOT) / city / safe_kw
        ck_dir.mkdir(parents=True, exist_ok=True)
        
        # 결과 저장: CSV, 막대그래프, 워드클라우드
        top_freq_df.to_csv(ck_dir / f"{city}_{safe_kw}_freq_top{TOP_N}.csv",
                           index=False, encoding='utf-8-sig')
        save_bar(top_freq_df,
                 f"[{city}·{kw}] 상위 {TOP_N}",
                 ck_dir / f"{city}_{safe_kw}_bar.png")
        save_wc(freq,
                f"[{city}·{kw}] 워드클라우드",
                ck_dir / f"{city}_{safe_kw}_wc.png")
        print(f"✅ {city}-{kw} 분석 완료")

# ============================================================
# 5) (C) 전체 도시 통합 워드클라우드 - 모든 도시 데이터 통합 분석
# ============================================================
print("🌐 전체 도시 통합 분석 시작...")

# 모든 도시의 단어 빈도를 하나로 합치기
freq_all = Counter()
for df in city_dfs.values():
    freq_all.update(get_word_freq(df['tokens']))    # 각 도시 빈도를 누적

# 상위 단어들만 선별하여 워드클라우드 생성
top_all_dict = dict(freq_all.most_common(WC_TOP_ALL))
save_wc(top_all_dict,
        f"전체 도시 통합 워드클라우드 (Top {WC_TOP_ALL})",
        pathlib.Path(OUT_ROOT) / f"ALL_wordcloud_top{WC_TOP_ALL}.png")
print("🎉 통합 워드클라우드까지 완료!")

# ============================================================
# 6) (옵션) 키워드별 통합 워드클라우드 - 키워드별로 모든 도시 통합
# ============================================================
print("🏷️ 키워드별 통합 분석 시작...")

for kw in keywords:
    print(f"🔄 키워드 [{kw}] 통합 분석 중...")
    
    # 해당 키워드에 대해 모든 도시의 데이터를 통합
    freq_kw = Counter()
    for city, df in city_dfs.items():
        # 각 도시에서 해당 키워드만 필터링하여 빈도 누적
        freq_kw.update(get_word_freq(df[df['keyword']==kw]['tokens']))
    
    # 해당 키워드에 대한 데이터가 있으면 워드클라우드 생성
    if freq_kw:
        safe_kw = kw.replace(' ','')                # 공백 제거
        save_wc(dict(freq_kw.most_common(WC_TOP_ALL)),
                f"키워드 [{kw}] 통합 WC",
                pathlib.Path(OUT_ROOT) / f"{safe_kw}_ALL_wc.png")
        print(f"🔄 키워드 [{kw}] 통합 워드클라우드 완료")

print("🎊 모든 분석 완료!")
print(f"📁 결과는 '{OUT_ROOT}' 폴더에 저장되었습니다.")
print("📂 폴더 구조:")
print("   ├── 도시명/ALL/ (도시별 전체 분석)")
print("   ├── 도시명/키워드명/ (도시별×키워드별 분석)")
print("   ├── ALL_wordcloud_top50.png (전체 통합)")
print("   └── 키워드명_ALL_wc.png (키워드별 통합)")